### ISSUE TITLE
Container does not start when GitHub API limit reached: updateManager.py line 50 undefined publish_time.

### ISSUE THREAD

**Issue by rossowl** [diyhue/diyHue#1019]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

No

### Description

UnboundLocalError: cannot access local variable 'publish_time' where it is not associated with a value

logging.info("publish_time  diyHue : " + str(publish_time))

GitHub API: {"message":"API rate limit exceeded for .....

### Errorlog:

`2024-06-01 13:23:21,617 - services.updateManager - INFO - creation_time diyHue : 2024-05-28 19

Traceback (most recent call last):

  File "/opt/hue-emulator/HueEmulator3.py", line 115, in <module>

    updateManager.startupCheck()

  File "/opt/hue-emulator/services/updateManager.py", line 110, in startupCheck

    githubCheck()

  File "/opt/hue-emulator/services/updateManager.py", line 50, in githubCheck

    logging.info("publish_time  diyHue : " + str(publish_time))

                                                 ^^^^^^^^^^^^

UnboundLocalError: cannot access local variable 'publish_time' where it is not associated with a value

Exception ignored in: <function Group.__del__ at 0xf67ec5c8>

Traceback (most recent call last):

  File "/opt/hue-emulator/HueObjects/__init__.py", line 1051, in __del__

ImportError: sys.meta_path is None, Python is likely shutting down`

### Steps to reproduce

start container

### Please enter your operating system details here

Debian

### What DiyHue version(branch) are you using?

master (latest)

**Comment by hendriksen-mark** [comment]
Hi,

Do you still have this problem?
This is not a diyhue issue.
Github limits the request per hour per user.
https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

How did you get this error to occur?
The rate limit is 60 request per hour.

Mark

**Comment by rossowl** [comment]
I had hass rest sensor for zigbee2mqtt latest version with frequency 30 sec.
After half of every hour github returns message with status code != 200.
The is publish_time undefined.

def githubCheck():
    creation_time = subprocess.run("stat -c %y HueEmulator3.py", shell=True, capture_output=True, text=True)#2024-02-18 19:50:15.000000000 +0100\n

    #...
    response = requests.get(url)

    # status code is not 200, this code is skipped
    if response.status_code == 200:
        #...
        device_data = json.loads(response.text)

        # here is publish_time defined but only if status_code == 200
        publish_time = datetime.strptime(device_data["commit"]["commit"]["author"]["date"], "%Y-%m-%dT%H:%M:%SZ").strftime("%Y-%m-%d %H")
        # end of skipped code when status code != 200

    # this line is always processed
    logging.info("creation_time diyHue : " + str(creation_time))

   # status code != 200 and publish_time is not defined. This line raise Exception
    logging.info("publish_time  diyHue : " + str(publish_time))

**Comment by mariusmotea** [comment]
I think it is now fixed

**Comment by hendriksen-mark** [comment]
"1970-01-01 00:00:00.000000000 +0100\n"
Is not the wright notation.

"1970-01-01 0"
Is the wright notation.

"creation_time diyHue : 2024-05-28 19"

**Comment by hendriksen-mark** [comment]
Or use datetime to convert it

**Comment by Justdigit** [comment]
Looks like this is happening again.

Or something like this

`2024-07-09 21:04:24,884 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2024-07-09 21:04:24,894 - configManager.argumentHandler - INFO - Debug logging disabled!
2024-07-09 21:04:25,050 - configManager.configHandler - INFO - Config loaded
2024-07-09 21:04:25,445 - services.updateManager - INFO - no swversion number update from Philips
2024-07-09 21:04:25,577 - services.updateManager - INFO - creation_time diyHue : 2024-07-08 21
2024-07-09 21:04:25,578 - services.updateManager - INFO - publish_time  diyHue : 1970-01-01 00:00:00.000000000 +0100

2024-07-09 21:04:25,693 - services.updateManager - INFO - creation_time UI : 2024-07-08 21
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 115, in <module>
    updateManager.startupCheck()
  File "/opt/hue-emulator/services/updateManager.py", line 104, in startupCheck
    githubCheck()
  File "/opt/hue-emulator/services/updateManager.py", line 56, in githubCheck
    elif githubUICheck() == True:
  File "/opt/hue-emulator/services/updateManager.py", line 85, in githubUICheck
    logging.info("publish_time  UI : " + str(publish_time))
UnboundLocalError: local variable 'publish_time' referenced before assignment
Exception ignored in: <function Light.__del__ at 0x7f8dab2a60>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 308, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Light.__del__ at 0x7f8dab2a60>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 308, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Light.__del__ at 0x7f8dab2a60>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 308, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Light.__del__ at 0x7f8dab2a60>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 308, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Light.__del__ at 0x7f8dab2a60>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 308, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Light.__del__ at 0x7f8dab2a60>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 308, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Light.__del__ at 0x7f8dab2a60>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 308, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Group.__del__ at 0x7f8dab6dc0>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 1051, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
2024-07-09 21:04:25,810 - HueObjects - INFO - Daylight sensor was destroyed.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "/usr/local/lib/python3.8/logging/handlers.py", line 183, in shouldRollover
    self.stream = self._open()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Call stack:
  File "/opt/hue-emulator/HueObjects/__init__.py", line 1755, in __del__
    logging.info(self.name + " sensor was destroyed.")
Message: 'Daylight sensor was destroyed.'
Arguments: ()
[cmd] ./run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... `

**Comment by hendriksen-mark** [comment]
yes i wil fix it now.

**Comment by hendriksen-mark** [comment]
i pushed the change, this error is not a directly a diyhue issue, per IP address you can only do 60 request per hour to github.
This can be fixed with setting a fake date to publish_time.

**Comment by Justdigit** [comment]
> i pushed the change, this error is not a directly a diyhue issue, per IP address you can only do 60 request per hour to github. This can be fixed with setting a fake date to publish_time.

OK??? Does that mean i am spamming Github?? Or is it meant to check that much for updates??

**Comment by hendriksen-mark** [comment]
in normal conditions diyhue checks only 1 time per day(at update time you setup in the hue app), if you restart diyhue it also checks. so if you restart diyhue or check for update it will make 2 request to github(diyhue and ui) so you can only do this 30 times in 1 hour.

**Comment by Justdigit** [comment]
> in normal conditions diyhue checks only 1 time per day(at update time you setup in the hue app), if you restart diyhue it also checks. so if you restart diyhue or check for update it will make 2 request to github(diyhue and ui) so you can only do this 30 times in 1 hour.

WOW I am definitely not restarting that much manually. I have it now running on my Home Assistant machine.
I had the same issue on my VM before i moved to HA

**Comment by hendriksen-mark** [comment]
what is also possible is that diyhue can not acces github, so it can not connect to the outside world.

**Comment by hendriksen-mark** [comment]
Added `publish_time` to diyhue and webui, also if no connection to internet it skips these checks.
