### ISSUE TITLE
Hue app does not work when gradient lightstrip added

### ISSUE THREAD

**Issue by ummetcivi** [diyhue/diyHue#1035]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

No

### Description

Hey,

I have Hue Play gradient lightstrip 65 connected to Zigbee2Mqtt. It's recognized as LCX002

![image](https://github.com/user-attachments/assets/315d9411-87fa-4982-9278-10eaef063cd8)

I added this light to Diyhue as LCX002.

![image](https://github.com/user-attachments/assets/57bf8714-5e55-4f70-9ff9-797ce6287d6c)

But whenever I add this light to Diyhue, Hue App does not work. If I remove it, everything backs to normal. 

I attached the logs of Diyhue when Hue app tries to connect.

### Errorlog:

2024-08-04 19:19:25,558 - werkzeug - 225 - INFO - 192.168.1.123 - - [04/Aug/2024 19:19:25] "GET /clip/v2/resource HTTP/1.1" 500 -
2024-08-04 19:19:25,964 - werkzeug - 225 - INFO - 192.168.1.67 - - [04/Aug/2024 19:19:25] "GET /lights HTTP/1.1" 200 -
2024-08-04 19:19:26,525 - werkzeug - 225 - INFO - 192.168.1.123 - - [04/Aug/2024 19:19:26] "GET /clip/v2/resource/bridge HTTP/1.1" 200 -
2024-08-04 19:19:26,538 - werkzeug - 225 - INFO - 192.168.1.123 - - [04/Aug/2024 19:19:26] "GET /eventstream/clip/v2 HTTP/1.1" 200 -
[2024-08-04 19:19:26,558] ERROR in app: Exception on /clip/v2/resource [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hue-emulator/flaskUI/v2restapi.py", line 244, in get
    data.append(light.getV2Api())
                ^^^^^^^^^^^^^^^^
  File "/opt/hue-emulator/HueObjects/Light.py", line 281, in getV2Api
    "points_capable": self.protocol_cfg["points_capable"]}
                      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'points_capable'
2024-08-04 19:19:26,560 - werkzeug - 225 - INFO - 192.168.1.123 - - [04/Aug/2024 19:19:26] "GET /clip/v2/resource HTTP/1.1" 500 -
2024-08-04 19:19:26,662 - werkzeug - 225 - INFO - 172.18.0.12 - - [04/Aug/2024 19:19:26] "GET /api/config HTTP/1.0" 200 -

### Steps to reproduce

 - Add LCX002 to Zigbee2Mqtt
 - Add LCX002 to Diyhue
 - Open Hue App

### Please enter your operating system details here

Hue-Emulator Version: 2024-08-02 20:11:46.000000000 +0300
WebUI Version: 2024-08-02 20:10:26.000000000 +0300
Architecture: x86_64
OS: Linux
Linux version: #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15)
Linux release: 6.1.0-23-amd64
Hardware: %Hardware%

### Upload debug tar

```
This can be downloaded from the webUI.
DiyHue > Bridge > Brdige Control > Download debug > Full debug
Do not upload from Force config dump, Force config dump contains sensitive information
``
[config_debug_2.zip](https://github.com/user-attachments/files/16488242/config_debug_2.zip)


### What DiyHue version(branch) are you using?

master (latest)

**Comment by AJ-Reckless** [comment]
This same behavior also happens with LCX006 (Hue Play Gradient Lightstrip).

**Comment by hendriksen-mark** [comment]
Hi, please look at the diyhue docs at https://diyhue.readthedocs.io/en/latest/lights/lightTypes.html

The lcx types in diyhue only work with diyhue lights and not with other lights.

**Comment by AJ-Reckless** [comment]
I landed there before, but as someone who doesn't build their own lights I did not understand what "only use with native gradient sketch" meant.  I do now, and thank you for the clarification.  Just to  confirm before I pull out my old bridge, this also means that as of now there is no way to use an actual Philips Hue Play gradient light strip with duyHue as intended (behind a TV, syncing with the colors around the border via the Hue Sync app), correct?

**Comment by hendriksen-mark** [comment]
You can use the other light types, I suggest you use LST002. The important part is what features the light have, bri, ct, xy, hue, sat

**Comment by hendriksen-mark** [comment]
Hi, i did some more research and this function is not yet in HA, it is in Z2M.
I can change diyhue to make the edit to LCX work for non native lights but i have no lights to test with.
If you can and are willing to test this i will do the update.

**Comment by AJ-Reckless** [comment]
I can absolutely test.  All of my other Philips lights are Z2m, but I still use a Philips bridge for all of my for my gradient lightstrips and hue smart play lights so that they can sync to my displays with Hue Sync.  If this allows me to properly use Hue Sync with diyHue I can finally ditch my bridge.

**Comment by hendriksen-mark** [comment]
the new version with the changes are online, now if you change the light type on the webui it should work.

**Comment by AJ-Reckless** [comment]
Just finished testing.  The good news is that you can select the LCX002 profile on genuine Philips Hue lightstrips now and the system remains functional. I am also able to control and adjust the lights appropriately.  The only problem is that the Hue Sync app still does not work properly.  When I selected my lightstrip and started to sync the lights to my display it caused the lightstrip to continuously flash random colors and it became unresponsive.  I had to manually pull the plug and start it back up.

**Comment by hendriksen-mark** [comment]
Thanks for the feedback, if i understand correctly you can set the gradient via the hue app and the light displays the correct colors?
when using entertainment mode(hue sync) the light randomly flashes and does not exit this state and then you pull the plug?
from what do you pull the plug?
