### ISSUE TITLE
Custom WLED strip gets "light was destroyed" when changing model ID to LCX002,4,6

### ISSUE THREAD

**Issue by DiegoJp** [diyhue/diyHue#1037]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

No

### Description

Hello, I'm having issues with my custom WLED powered ws2813 strip.
Apparrently config files get corrupted after selecting LCX006, LCX004 or LCX002 in the WebUI. Check attached log.
It get "destroyed" and then diyhue can't start ever again having to wipe the lights.yaml.

When set as LST002 no issues happen but having set as this limits the functionality.
It is worth mentioning that in some versions before my strip was recognized as LCX006 and was functioning ok.

### Errorlog:

-----------------------------------------------------------
 Add-on: diyHue
 Emulate a Hue Bridge, add lights, sensors etc. from different vendors into one Ecosystem
-----------------------------------------------------------
 Add-on version: 2.0.15
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.0  (amd64 / qemux86-64)
 Home Assistant Core: 2024.8.1
 Home Assistant Supervisor: 2024.08.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/config/diyhue exists.
Your Architecture is = amd64
Serve HTTPS
2024-08-15 11:53:59,804 - configManager.argumentHandler - INFO - Using Host 192.168.1.190:80
2024-08-15 11:53:59,805 - configManager.argumentHandler - INFO - Host MAC given as 02186852322F
2024-08-15 11:53:59,805 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2024-08-15 11:53:59,805 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2024-08-15 11:53:59,805 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2024-08-15 11:53:59,807 - configManager.argumentHandler - INFO - Using Host 192.168.1.190:80
2024-08-15 11:53:59,808 - configManager.argumentHandler - INFO - Host MAC given as 02186852322F
2024-08-15 11:53:59,808 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2024-08-15 11:53:59,808 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2024-08-15 11:53:59,808 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2024-08-15 11:53:59,808 - configManager.argumentHandler - INFO - Debug logging enabled!
2024-08-15 16:53:59,827 - configManager.configHandler - ERROR - CRITICAL! Config file was not loaded
Traceback (most recent call last):
  File "/opt/hue-emulator/configManager/configHandler.py", line 149, in load_config
    self.yaml_config["lights"][light] = Light(data)
  File "/opt/hue-emulator/HueObjects/__init__.py", line 291, in __init__
    "data": [self.getV2Api()],
  File "/opt/hue-emulator/HueObjects/__init__.py", line 508, in getV2Api
    "points_capable": self.protocol_cfg["points_capable"]}
KeyError: 'points_capable'
2024-08-15 16:53:59,829 - HueObjects - INFO - wled-ambilightpc_seg0 light was destroyed.
CRITICAL! Config file was not loaded
Exception ignored in: <function Light.__del__ at 0x7fb0b0d9b9d0>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 308, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
[cmd] ./run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

### Steps to reproduce

1. Start a fresh install of DiyHue HA addon. (empty /config)
2. Open the WebUI
3. Add lights with Scan for lights button
4. WLED strip gets added as LST002
5. Change the model from LST002 to LCX006 (or LCX002 or LCX004)
6. Go to an app that could control DiyHue, in this case Hue Essentials (Windows Store version 2.4.4.0)
7. Try to turn on the strip.
8. Strip won't turn on or off
9. Check the WebUI, realise the webui was stopped
10. Check the logs, realise the addon was stopped
11. Hello

### Please enter your operating system details here

If diyHue does not star use "uname -mrs"
Hue-Emulator Version:2.0.15
Architecture: Home Assistant x86_64 on a proxmox container.
Hardware: Proxmox virtual container

### Upload debug tar

```
This can be downloaded from the webUI.
DiyHue > Bridge > Brdige Control > Download debug > Full debug
Do not upload from Force config dump, Force config dump contains sensitive information
``


### What DiyHue version(branch) are you using?

master (latest)

**Comment by hendriksen-mark** [comment]
please take a look at this issue https://github.com/diyhue/diyHue/issues/1014.

**Comment by DiegoJp** [comment]
> please take a look at this issue #1014.

Hello, excuse me but is that issue relevant to the case stated in my submitted issue?
I barely see the connection.

Thanks for the answer

**Comment by hendriksen-mark** [comment]
Hi, the lights with lcx and 915005987201 only work with diyhue lights firmware.
https://github.com/hendriksen-mark/ReadTheDocs/blob/master/source/lights/lightTypes.rst

**Comment by DiegoJp** [comment]
yikes

**Comment by hendriksen-mark** [comment]
Hi, the lights with lcx and 915005987201 only work with diyhue lights firmware.
https://diyhue.readthedocs.io/en/latest/lights/lightTypes.html
What else do you expect?
