### ISSUE TITLE
Pairing problem between DiyHue and Hue app

### ISSUE THREAD

**Issue by ZephyrOff** [diyhue/diyHue#1041]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Install Script

### Home Assistant related?

Yes

### Description

Hi,
I can no longer pair the Hue app with my DiyHue bridge which is in Home Assistant. The application detects the bridge but when I click on the Link button, nothing happens. I also tried with Hue Essentials and I have the same behavior.
I tried to completely delete the configuration and the application to start from scratch on HA but the problem persists.

### Errorlog:

2024-09-04 07:34:19,608 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:19,610 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:19] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:23,138 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:23] "GET /api/config HTTP/1.1" 200 -
2024-09-04 07:34:23,210 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:23,211 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:23] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:24,278 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:24,280 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:24] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:25,314 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:25,315 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:25] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:26,359 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:26,360 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:26] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:27,072 - werkzeug - 225 - INFO - 192.168.1.18 - - [04/Sep/2024 07:34:27] "GET /api/e2f56616653b11ef82ae48210b5e7f29/groups/0 HTTP/1.1" 200 -
2024-09-04 07:34:27,073 - werkzeug - 225 - INFO - 192.168.1.18 - - [04/Sep/2024 07:34:27] "GET /api/e2f56616653b11ef82ae48210b5e7f29/config/swupdate2 HTTP/1.1" 200 -
2024-09-04 07:34:27,397 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:27,399 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:27] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:28,156 - werkzeug - 225 - INFO - 192.168.1.18 - - [04/Sep/2024 07:34:28] "GET /api/e2f56616653b11ef82ae48210b5e7f29/config HTTP/1.1" 200 -
2024-09-04 07:34:28,225 - flaskUI.restful - 291 - DEBUG - [{'success': {'/config/linkbutton': {'lastlinkbuttonpushed': 1725428068}}}]
2024-09-04 07:34:28,232 - configManager.configHandler - 262 - DEBUG - Dump config file /config/diyhue/config.yaml
2024-09-04 07:34:28,233 - werkzeug - 225 - INFO - 192.168.1.18 - - [04/Sep/2024 07:34:28] "PUT /api/e2f56616653b11ef82ae48210b5e7f29/config HTTP/1.1" 200 -
2024-09-04 07:34:28,426 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:28,428 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:28] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:29,447 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:29,449 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:29] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:30,476 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:30,476 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:30] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:30,499 - services.stateFetch - 12 - INFO - start lights sync
2024-09-04 07:34:31,025 - services.ssdp - 33 - DEBUG - Sending M-Search response to 192.168.1.18
2024-09-04 07:34:31,501 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:31,503 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:31] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:31,929 - services.ssdp - 33 - DEBUG - Sending M-Search response to 192.168.1.18
2024-09-04 07:34:32,063 - werkzeug - 225 - INFO - 192.168.1.18 - - [04/Sep/2024 07:34:32] "GET /api/e2f56616653b11ef82ae48210b5e7f29/config/swupdate2 HTTP/1.1" 200 -
2024-09-04 07:34:32,064 - werkzeug - 225 - INFO - 192.168.1.18 - - [04/Sep/2024 07:34:32] "GET /api/e2f56616653b11ef82ae48210b5e7f29/groups/0 HTTP/1.1" 200 -
2024-09-04 07:34:32,560 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:32,562 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:32] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:32,831 - services.ssdp - 33 - DEBUG - Sending M-Search response to 192.168.1.18
2024-09-04 07:34:33,589 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:33,591 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:33] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:34,036 - services.ssdp - 33 - DEBUG - Sending M-Search response to 192.168.1.18
2024-09-04 07:34:34,620 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:34,621 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:34] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:35,677 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:35,678 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:35] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:36,694 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:36,696 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:36] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:37,070 - werkzeug - 225 - INFO - 192.168.1.18 - - [04/Sep/2024 07:34:37] "GET /api/e2f56616653b11ef82ae48210b5e7f29/config/swupdate2 HTTP/1.1" 200 -
2024-09-04 07:34:37,071 - werkzeug - 225 - INFO - 192.168.1.18 - - [04/Sep/2024 07:34:37] "GET /api/e2f56616653b11ef82ae48210b5e7f29/groups/0 HTTP/1.1" 200 -
2024-09-04 07:34:37,732 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:37,734 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:37] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:38,754 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:38,757 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:38] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:39,792 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:39,793 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:39] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:40,853 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:40,855 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:40] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:41,868 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:41,869 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:41] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:42,052 - werkzeug - 225 - INFO - 192.168.1.18 - - [04/Sep/2024 07:34:42] "GET /api/e2f56616653b11ef82ae48210b5e7f29/config/swupdate2 HTTP/1.1" 200 -
2024-09-04 07:34:42,054 - werkzeug - 225 - INFO - 192.168.1.18 - - [04/Sep/2024 07:34:42] "GET /api/e2f56616653b11ef82ae48210b5e7f29/groups/0 HTTP/1.1" 200 -
2024-09-04 07:34:42,885 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:42,887 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:42] "POST /api HTTP/1.1" 200 -
2024-09-04 07:34:43,514 - services.stateFetch - 12 - INFO - start lights sync
2024-09-04 07:34:43,914 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 07:34:43,915 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 07:34:43] "POST /api HTTP/1.1" 200 -

### Steps to reproduce

Complicated to reproduce without my hardware but I have the DiyHue plugin on HA, connected by wire to my box. And an Android phone in wifi on the same box with the Hue application and Hue Essentials

### Please enter your operating system details here

Hue-Emulator Version: 2024-09-03 11:34:18.000000000
WebUI Version: 2024-09-03 11:34:22.000000000
Architecture: x86_64
OS: Linux
Linux version: #1 SMP PREEMPT_DYNAMIC Wed Aug 21 16:24:58 UTC 2024
Linux release: 6.6.46-haos
Hardware: %Hardware%

### Upload debug tar

[config_debug.tar.zip](https://github.com/user-attachments/files/16861889/config_debug.tar.zip)

Rename the file without .zip, Github doesn't accept .tar

### What DiyHue version(branch) are you using?

master (latest)

**Comment by hendriksen-mark** [comment]
Hi, did you pit i the wright mac addres in the plugin settings?
The config_debug.tar is not good, i can not download it.

**Comment by hendriksen-mark** [comment]
Did you setup the time zone? It is now on London. If the python time and the device time is off more then 2 hours it will not pair.

**Comment by ZephyrOff** [comment]
How can I check this? My installation is in Paris.

**Comment by hendriksen-mark** [comment]
In the webui>diyhue>bridge>bridge config>timezone.
Ow nice I'm in Paris tomorrow.

**Comment by hendriksen-mark** [comment]
You can not use philips cloud.

**Comment by ZephyrOff** [comment]
Yes I know, I ignored it when I logged in

**Comment by hendriksen-mark** [comment]
Can you restart diyhue and check again?

**Comment by ZephyrOff** [comment]
I restarted my entire server to be sure but I still have the problem

**Comment by hendriksen-mark** [comment]
can you resend the logfile, i dont need the config_dubug anymore.

**Comment by ZephyrOff** [comment]
Here is the logfile.
Thanks for the help :)
[diyhue_log.tar.zip](https://github.com/user-attachments/files/16874897/diyhue_log.tar.zip)

**Comment by hendriksen-mark** [comment]
```
2024-09-04 12:22:40,561 - flaskUI.restful - 291 - DEBUG - [{'success': {'/config/linkbutton': {'lastlinkbuttonpushed': 1725445360}}}]
2024-09-04 12:22:40,571 - configManager.configHandler - 262 - DEBUG - Dump config file /config/diyhue/config.yaml
2024-09-04 12:22:40,572 - werkzeug - 225 - INFO - 192.168.1.18 - - [04/Sep/2024 12:22:40] "PUT /api/e2f56616653b11ef82ae48210b5e7f29/config HTTP/1.1" 200 -
2024-09-04 12:22:40,692 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 12:22:40] "GET /api/config HTTP/1.1" 200 -
2024-09-04 12:22:40,768 - flaskUI.restful - 75 - INFO - {'devicetype': 'Hue#HD1913', 'generateclientkey': True}
2024-09-04 12:22:40,771 - flaskUI.restful - 90 - DEBUG - [{'success': {'username': '9d9614966aa711efbdc648210b5e7f29', 'clientkey': '4CFD9885128744129AA0537937ADF5E4'}}]
2024-09-04 12:22:40,780 - configManager.configHandler - 262 - DEBUG - Dump config file /config/diyhue/config.yaml
2024-09-04 12:22:40,830 - configManager.configHandler - 279 - DEBUG - Dump config file /config/diyhue/lights.yaml
2024-09-04 12:22:40,831 - configManager.configHandler - 279 - DEBUG - Dump config file /config/diyhue/groups.yaml
2024-09-04 12:22:40,831 - configManager.configHandler - 279 - DEBUG - Dump config file /config/diyhue/scenes.yaml
2024-09-04 12:22:40,831 - configManager.configHandler - 279 - DEBUG - Dump config file /config/diyhue/rules.yaml
2024-09-04 12:22:40,831 - configManager.configHandler - 279 - DEBUG - Dump config file /config/diyhue/resourcelinks.yaml
2024-09-04 12:22:40,831 - configManager.configHandler - 279 - DEBUG - Dump config file /config/diyhue/schedules.yaml
2024-09-04 12:22:40,839 - configManager.configHandler - 279 - DEBUG - Dump config file /config/diyhue/sensors.yaml
2024-09-04 12:22:40,839 - configManager.configHandler - 279 - DEBUG - Dump config file /config/diyhue/behavior_instance.yaml
2024-09-04 12:22:40,839 - configManager.configHandler - 279 - DEBUG - Dump config file /config/diyhue/smart_scene.yaml
2024-09-04 12:22:40,840 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 12:22:40] "POST /api HTTP/1.1" 200 -
2024-09-04 12:22:40,872 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 12:22:40] "GET /clip/v2/resource/bridge HTTP/1.1" 200 -
2024-09-04 12:22:40,909 - flaskUI.restful - 291 - DEBUG - [{'success': {'/config/swupdate2': {'install': False, 'autoinstall': {'on': True}}}}]
2024-09-04 12:22:40,918 - configManager.configHandler - 262 - DEBUG - Dump config file /config/diyhue/config.yaml
2024-09-04 12:22:40,919 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 12:22:40] "PUT /api/9d9614966aa711efbdc648210b5e7f29/config HTTP/1.1" 200 -
2024-09-04 12:22:40,955 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 12:22:40] "GET /eventstream/clip/v2 HTTP/1.1" 200 -
2024-09-04 12:22:41,077 - werkzeug - 225 - INFO - 192.168.1.105 - - [04/Sep/2024 12:22:41] "[35m[1mGET /clip/v2/resource HTTP/1.1[0m" 500 -
```

this is the interesting part.
fist the link button is pressed.
then device `Hue#HD1913` with ip `192.168.1.105` want a key.
the key is generated.
the key is saved in diyhue.
ip `192.168.1.105` makes a successful change to swupdate2 http code 200.
ip `192.168.1.105` successfully gets eventstream http code 200.
ip `192.168.1.105` want `/clip/v2/resource` but get a http code 500.

can you try to remove the app data from your phone or if iphone reinstall the app.

Unfortunately due to my trip to paris im not able to respond for 2 days.
after that i will investigate more if it still not working.

**Comment by ZephyrOff** [comment]
I just tested with another phone and I have the same behavior.
However, I just saw in the plugin log that there is a Python error, this can affect the 500 error.

Have a good trip, we'll see about that when you get back

```
2024-09-04 21:00:49,132 - configManager.configHandler - 262 - DEBUG - Dump config file /config/diyhue/config.yaml
2024-09-04 21:00:49,132 - werkzeug - 225 - INFO - 192.168.1.71 - - [04/Sep/2024 21:00:49] "PUT /api/ff78daca6aef11efbf4248210b5e7f29/config HTTP/1.1" 200 -
[2024-09-04 21:00:49,325] ERROR in app: Exception on /clip/v2/resource [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/hue-emulator/flaskUI/v2restapi.py", line 307, in get
    temperature = sensor.getTemperature()
  File "/opt/hue-emulator/HueObjects/Sensor.py", line 292, in getTemperature
    "temperature": self.state["temperature"]/100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2024-09-04 21:00:49,326 - werkzeug - 225 - INFO - 192.168.1.71 - - [04/Sep/2024 21:00:49] "GET /clip/v2/resource HTTP/1.1" 500 -
2024-09-04 21:00:49,414 - werkzeug - 225 - INFO - 192.168.1.71 - - [04/Sep/2024 21:00:49] "GET /clip/v2/resource/bridge HTTP/1.1" 200 -
2024-09-04 21:00:49,478 - werkzeug - 225 - INFO - 192.168.1.71 - - [04/Sep/2024 21:00:49] "GET /eventstream/clip/v2 HTTP/1.1" 200 -
[2024-09-04 21:00:49,512] ERROR in app: Exception on /clip/v2/resource [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/hue-emulator/flaskUI/v2restapi.py", line 307, in get
    temperature = sensor.getTemperature()
  File "/opt/hue-emulator/HueObjects/Sensor.py", line 292, in getTemperature
    "temperature": self.state["temperature"]/100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2024-09-04 21:00:49,513 - werkzeug - 225 - INFO - 192.168.1.71 - - [04/Sep/2024 21:00:49] "GET /clip/v2/resource HTTP/1.1" 500 -
```

**Comment by ZephyrOff** [comment]
Hi hendriksen-mark,
I just saw that you pushed a commit for my issue.
How can I push it to the Home Assistant plugin. Do I have to wait for the next version on HACS or is there another method?

**Comment by hendriksen-mark** [comment]
hi, i made changes to fix this. please try and give feedback.

**Comment by ZephyrOff** [comment]
Hi,
I just tested with the latest version and I came back on a bug with the link button. The hub is detected in the application but the link button does not work, and I do not see anything in the logs.
I tried to restart the service and the complete system.
I send you back the debug files

[config_debug.tar.zip](https://github.com/user-attachments/files/17228758/config_debug.tar.zip)
[diyhue_log.tar.zip](https://github.com/user-attachments/files/17228760/diyhue_log.tar.zip)

**Comment by hendriksen-mark** [comment]
In the log i only see 1 request from Hue Essentials with no error.
In what app do you get the problem?
Also debug is off can you enable this and try again?

**Comment by ZephyrOff** [comment]
I tested with the Hue Essentials app and mainly with the official Hue app
And I checked, the time zone is set correctly

[config_debug.tar.zip](https://github.com/user-attachments/files/17232429/config_debug.tar.zip)
[diyhue_log.tar.zip](https://github.com/user-attachments/files/17232430/diyhue_log.tar.zip)

**Comment by hendriksen-mark** [comment]
i dont see any requests to pair?
the link button works.
and you do not have the latest version of diyhue

**Comment by ZephyrOff** [comment]
I just got the latest version released 11 hours ago.
I tested the pairing with another device and I have the same problem. On the Hue app it discovers the bridge and asks to press the link button, but on the logs I don't see the connection request.
Any other ideas?

**Comment by hendriksen-mark** [comment]
Do you have a original bridge or another instance of diyhue running? If so remove the original bridge from power or shutdown the other diyhue and try again.

**Comment by ZephyrOff** [comment]
No I only have the diyhue on my Home Assistant, that's what's weird. I don't see where the problem could come from

**Comment by ZephyrOff** [comment]
I just tested changing the bridge name to check if Hue Essential gives me the right bridge and it is the right one, so there is no duplicate on my network

**Comment by hendriksen-mark** [comment]
can you share the output of [192.168.1.86/api/config](url)?

**Comment by hendriksen-mark** [comment]
also you have `https` desabled, `2024-10-02 17:46:56,165 - configManager.argumentHandler - 187 - INFO - HTTPS Port Disabled`
the hue app need port 443.

**Comment by ZephyrOff** [comment]
I tested with and without https but the result is the same. Here is the /api/config

{"apiversion": "1.66.0", "bridgeid": "48210BFFFE5E7F29", "datastoreversion": "126", "factorynew": false, "mac": "48:21:0b:5e:7f:29", "modelid": "BSB002", "name": "HA Bridge", "replacesbridgeid": null, "starterkitid": "", "swversion": "1966117030"}

**Comment by hendriksen-mark** [comment]
can you check the certificate using this instructions and share the output?
https://diyhue.readthedocs.io/en/latest/AddFuncts/debug.html#https-certificate-check

**Comment by ZephyrOff** [comment]
The bridge is not listening on 443 even though the no_serve_https option is disabled and I rebuilt the plugin for security.

curl https://192.168.1.86/api/nouser/config -v -k
*   Trying 192.168.1.86:443...
* connect to 192.168.1.86 port 443 from 0.0.0.0 port 53517 failed: Connection refused
* Failed to connect to 192.168.1.86 port 443 after 2048 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to 192.168.1.86 port 443 after 2048 ms: Couldn't connect to server

[diyhue_log.tar.zip](https://github.com/user-attachments/files/17241615/diyhue_log.tar.zip)
[config_debug.tar.zip](https://github.com/user-attachments/files/17241616/config_debug.tar.zip)

**Comment by ZephyrOff** [comment]
He doesn't even listen

![image](https://github.com/user-attachments/assets/bb1081f4-bc7c-420b-84fa-732304848d79)

**Comment by ZephyrOff** [comment]
I found this error when I restart the add-on

![image](https://github.com/user-attachments/assets/4f48fe92-a61d-410a-a861-15c7b6d9de6a)
