### ISSUE TITLE
DiyHue Connection Failure with Zigbee2MQTT + Home Assistant 

### ISSUE THREAD

**Issue by crow1093** [diyhue/diyHue#1046]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

Yes

### Description

Since mid-August, my DiyHue setup with Zigbee2MQTT and Home Assistant has been experiencing connection failures. Pairing with Home Assistant alone still works, but as soon as MQTT comes into play, the connection breaks.

### Errorlog:

2024-09-21 10:27:06,973 - flaskUI.restful - 75 - INFO - {'devicetype': 'home-assistant#home'}
2024-09-21 10:27:07,296 - werkzeug - 225 - INFO - 192.168.178.83 - - [21/Sep/2024 10:27:07] "POST /api HTTP/1.1" 200 -
[2024-09-21 10:27:07,307] ERROR in app: Exception on /clip/v2/resource [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.11/dist-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/hue-emulator/flaskUI/v2restapi.py", line   
 307, in get
    temperature = sensor.getTemperature()
  File "/opt/hue-emulator/HueObjects/Sensor.py", line 292, in getTemperature
    "temperature": self.state["temperature"]/100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

### Steps to reproduce

Setup new diyhue container > Pair with Home Assistant > Setup mqtt in HueBridge > Reload Home Assistant Integration

### Please enter your operating system details here

If diyHue does not star use "uname -mrs"
Hue-Emulator Version: 2024-09-02 21:04:00.000000000 +0200
Architecture: x86_64
OS: Linux
Os version:  '#1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z)'
Os release: 6.5.11-7-pve
Hardware: Intel Nuc with Proxmox > Debian Docker LXC

### Upload debug tar

[config_debug.zip](https://github.com/user-attachments/files/17083457/config_debug.zip)

### What DiyHue version(branch) are you using?

master (latest)

**Comment by hendriksen-mark** [comment]
hi, i made changes to fix this. please try and give feedback.

**Comment by crow1093** [comment]
The recent image changes seem to have resolved the issues completely. Pairing with Home Assistant is working flawlessly, even with motion sensors included. Additionally, the problem with scenes not being controllable or triggered from Home Assistant has also been fixed. Everything is working as expected now!

When I'm back home, I'll also test the connection with the Hue apps. Thank you for the quick response!

**Comment by hendriksen-mark** [comment]
good to hear.
you ware not the first with this problem.
https://github.com/diyhue/diyHue/issues/1041
and also on slack.
