### ISSUE TITLE
No color change on RGBW Milight bulb

### ISSUE THREAD

**Issue by kapellmeister84** [diyhue/diyHue#108]
Hey, I just installed diyHue and the Diy Milight hub. Everything working fine, except the color doesn't change, when I try to, using the Hue App. If I change the color in the milightHub web interface, it works fine. But not with the diyHue interface, or the app. Any ideas? Thank you!

**Comment by kapellmeister84** [comment]
It only works with the app Hue Essentials but not with the official Hue app, nor Hue Hello app.

**Comment by mariusmotea** [comment]
Can you start the Hue Emultor in debug mode and show me the error here during light change from Hue App?

**Comment by kapellmeister84** [comment]
Thanks for your reply! I'll google how to do that and get back to you.

**Comment by Mevel** [comment]
change dir to Hue-Emulator and execute  hue Emulator with `--debug true` appeded

**Comment by jorisvanr** [comment]
Hi! I am also having this issue with Milight RGB CCT lights. I started the emulator in debug mode and this is the output: 

`2019-03-16 20:34:18,342 - root - ERROR - light 3 is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0x6ef96110>, 'Connection to 192.168.2.148 timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.2.148', port=80): Max retries exceeded with url: /state?light=2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x6ef96110>, 'Connection to 192.168.2.148 timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 194, in syncWithLights
    light_state = protocol.get_light_state(addresses[light], lights[light])
  File "/opt/hue-emulator/protocols/native_multi.py", line 11, in get_light_state
    state = requests.get("http://"+address["ip"]+"/state?light=" + str(address["light_nr"]), timeout=3)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.2.148', port=80): Max retries exceeded with url: /state?light=2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x6ef96110>, 'Connection to 192.168.2.148 timed out. (connect timeout=3)'))
`

**Comment by mariusmotea** [comment]
Tottaly different issue, here in logs we can see the milight hub is not responding to http calls. Probably the device was overloaded or is a bad ESP board.

**Comment by jorisvanr** [comment]
Thats weird. It does response when I go to the ESP IP address and change colors here. The IP address in the error is not an IP I use for the pi or ESP so no idea where it comes from.
