### ISSUE TITLE
Service failed to start

### ISSUE THREAD

**Issue by m50008** [diyhue/diyHue#130]
Everything worked fine but after rebooting the raspberry pi (which runs the original raspbian and is up to date) the diy-hue bridge was not reachable through the app. Even through the Browser the ip was not reachable. Then i connected via ssh and tried to start the service manualy.  This brought only an error so i stoped the service with `sudo systemctl stop hue-emulator.service ` 
and tried to start hue-emulator with `sudo ./HueEmulator3.py --debug=true`.
This is what i got. Any ideas what is going on?
As i read in some other issues, the bridge was configured with the original hue app.
Also there is nothing else running on the pi that could block a port binding or something else. 
```
sudo ./HueEmulator3.py --debug=true
Debug Enabled
Using Host IP of 192.168.178.99
2019-06-04 12:53:37,066 - root - INFO - b827ebc42831
2019-06-04 12:53:37,067 - root - INFO - IP range for light discovery: 0-255
2019-06-04 12:53:37,072 - root - INFO - Config loaded
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x759188f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/283145a4e198cc6535/config (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x759188f0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./HueEmulator3.py", line 1543, in <module>
    scanDeconz()
  File "./HueEmulator3.py", line 776, in scanDeconz
    deconz_config = json.loads(sendRequest("http://127.0.0.1:" + str(bridge_config["deconz"]["port"]) + "/api/" + bridge_config["deconz"]["username"] + "/config", "GET", "{}"))
  File "/opt/hue-emulator/functions/request.py", line 19, in sendRequest
    response = requests.get(url, timeout=timeout, headers=head)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/283145a4e198cc6535/config (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x759188f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-06-04 12:53:42,080 - root - INFO - delete scenes / 16
2019-06-04 12:53:42,081 - root - INFO - delete scenes / 19
2019-06-04 12:53:42,082 - root - INFO - delete scenes / 18
2019-06-04 12:53:42,082 - root - INFO - delete scenes / 17
```

**Comment by mariusmotea** [comment]
Hi,

I believe you enabled Deconz and now the hue emulator is unable to connect to Deconz because is not listening anymore on port 8080 (Deconz update?)

You can manually disable deconz in config.json file, just look for the key `deconz` => `enabled` => `true`. Change `true` to `false` and start the hue emulator back.
```
(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/283145a4e198cc6535/config (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x759188f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by m50008** [comment]
Yes, i enabled Deconz for the Hue Tap switch, but i didnt change anything there?
How can i change the Deconz port back to 8080?
Thanks, i will later test if this works.

**Comment by mariusmotea** [comment]
From Wiki:

> Edit Deconz systemd script to bind on port 8080: sudo vim /lib/systemd/system/deconz.service replace --http-port=80 with
> --http-port=8080 --upnp=0 --ws-port=8081

After this reload systemd service and restart deconz service.

**Comment by m50008** [comment]
I didn't had to change anything there, this was already in the config file. I did a `sudo service deconz-wifi restart` and `sudo service deconz-update restart` but the error stays the same.
