### ISSUE TITLE
MILIGHT - ERROR:root:light 1 is unreachable

### ISSUE THREAD

**Issue by Macopnet** [diyhue/diyHue#134]
Hello

I have a Fut066 working great with MilightHub 1.9.0 (nodemcuv2)
Install today DiyHue on raspberry 2+ and disable Domoticz
Pair MilightHub with DiyHue (device 0x1234 - groupe 1) to test
Install Hue Essentials app and pairing DiyHue

I can see my light but cannot on/off with Hue Essentials app
If i switch "on" the light with MilightHub, I can modify color, brigness etc with Hue Essentials app until Hue essential put in off the light

DEBUG:

 Installation completed. Open Hue app and search for bridges.
pi@raspberrypi:~ $ sudo systemctl stop hue-emulator
pi@raspberrypi:~ $ cd /opt/hue-emulator
pi@raspberrypi:/opt/hue-emulator $ sudo ./HueEmulator3.py
Using Host IP of 192.168.0.25
ERROR:root:light 1 is unreachable
Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 215, in syncWithLight                                                     s
    if light_data["state"] == "ON":
KeyError: 'state'
192.168.0.13 - - [10/Jun/2019 10:43:43] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.0.13 - - [10/Jun/2019 10:43:53] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.0.13 - - [10/Jun/2019 10:44:04] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
ERROR:root:light 1 is unreachable

**Comment by mariusmotea** [comment]
Please do the same but start the emulator in debug.

 `sudo ./HueEmulator3.py --debug=true`

 i need to see also the request.

**Comment by Macopnet** [comment]
i upgraded MilightHub 1.9.2 (nodemcuv2) fixing ( #476 ) Boolean values for state/status field are now properly respected, and On/Off work now, with Hue Essentials app

But:
I turn on the light with Hue Essentials app
The light comes on
After a few seconds, Hue Essentials app turns the Lightswitch off
the light stays on

DEBUG:

Last login: Sun Jun 16 06:01:40 2019 from 192.168.0.24
pi@raspberrypi:~ $ sudo systemctl stop hue-emulator
pi@raspberrypi:~ $ cd /opt/hue-emulator
pi@raspberrypi:/opt/hue-emulator $ sudo ./HueEmulator3.py --debug=true
Debug Enabled
Using Host IP of 192.168.0.25
2019-06-16 06:09:44,341 - root - INFO - b827eb3ffca6
2019-06-16 06:09:44,349 - root - INFO - IP range for light discovery: 0-255
2019-06-16 06:09:44,355 - root - INFO - 127.0.0.1
2019-06-16 06:09:44,375 - root - INFO - Config loaded
2019-06-16 06:09:44,413 - root - INFO - sync with lights
2019-06-16 06:09:44,475 - root - INFO - Starting httpd...
2019-06-16 06:09:44,518 - root - INFO - Starting ssl httpd...
2019-06-16 06:09:45,355 - root - ERROR - light 1 is unreachable
Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 226, in syncWithLights
    lights[light]["state"]["hue"] = light_data["hue"] * 180
KeyError: 'hue'
2019-06-16 06:09:45,587 - root - ERROR - light 3 is unreachable
Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 226, in syncWithLights
    lights[light]["state"]["hue"] = light_data["hue"] * 180
KeyError: 'hue'
2019-06-16 06:09:48,680 - root - ERROR - light 2 is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0xb10c3fd0>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='198.168.0.15', port=80): Max retries exceeded with url: /gateways/0x1235/rgbw/1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb10c3fd0>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 214, in syncWithLights
    light_data = json.loads(sendRequest("http://" + addresses[light]["ip"] + "/gateways/" + addresses[light]["device_id"] + "/" + addresses[light]["mode"] + "/" + str(addresses[light]["group"]), "GET", "{}"))
  File "/opt/hue-emulator/functions/request.py", line 19, in sendRequest
    response = requests.get(url, timeout=timeout, headers=head)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='198.168.0.15', port=80): Max retries exceeded with url: /gateways/0x1235/rgbw/1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb10c3fd0>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)'))
192.168.0.25 - - [16/Jun/2019 06:09:48] "GET /api/84312883a7fcbf9d9e6d180df58ba912 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:09:48] "GET /api/84312883a7fcbf9d9e6d180df58ba912/groups/0 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:09:58] "GET /api/84312883a7fcbf9d9e6d180df58ba912 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:09:58] "GET /api/84312883a7fcbf9d9e6d180df58ba912/groups/0 HTTP/1.1" 200 -
192.168.0.13 - - [16/Jun/2019 06:10:06] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
2019-06-16 06:10:07,834 - root - INFO - sync with lights
2019-06-16 06:10:07,962 - root - ERROR - light 1 is unreachable
Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 226, in syncWithLights
    lights[light]["state"]["hue"] = light_data["hue"] * 180
KeyError: 'hue'
2019-06-16 06:10:08,093 - root - ERROR - light 3 is unreachable
Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 226, in syncWithLights
    lights[light]["state"]["hue"] = light_data["hue"] * 180
KeyError: 'hue'
192.168.0.13 - - [16/Jun/2019 06:10:08] "PUT /api/a7161538be80d40b3de98dece6e91f90/lights/1/state HTTP/1.1" 200 -
2019-06-16 06:10:08,189 - root - INFO - in PUT method
2019-06-16 06:10:08,196 - root - INFO - /api/a7161538be80d40b3de98dece6e91f90/lights/1/state
2019-06-16 06:10:08,201 - root - INFO - b'{"on":true}'
2019-06-16 06:10:08,209 - root - INFO - {"status": true}
2019-06-16 06:10:08,578 - root - INFO - LightRequest: http://192.168.0.18/gateways/0x1234/rgb_cct/1
2019-06-16 06:10:08,588 - root - INFO - [
    {
        "success": {
            "/lights/1/state/on": true
        }
    }
]
192.168.0.25 - - [16/Jun/2019 06:10:09] "GET /api/84312883a7fcbf9d9e6d180df58ba912 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:10:09] "GET /api/84312883a7fcbf9d9e6d180df58ba912/groups/0 HTTP/1.1" 200 -
2019-06-16 06:10:11,197 - root - ERROR - light 2 is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0xb10ac9d0>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='198.168.0.15', port=80): Max retries exceeded with url: /gateways/0x1235/rgbw/1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb10ac9d0>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 214, in syncWithLights
    light_data = json.loads(sendRequest("http://" + addresses[light]["ip"] + "/gateways/" + addresses[light]["device_id"] + "/" + addresses[light]["mode"] + "/" + str(addresses[light]["group"]), "GET", "{}"))
  File "/opt/hue-emulator/functions/request.py", line 19, in sendRequest
    response = requests.get(url, timeout=timeout, headers=head)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='198.168.0.15', port=80): Max retries exceeded with url: /gateways/0x1235/rgbw/1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb10ac9d0>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)'))
192.168.0.13 - - [16/Jun/2019 06:10:16] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:10:19] "GET /api/84312883a7fcbf9d9e6d180df58ba912 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:10:19] "GET /api/84312883a7fcbf9d9e6d180df58ba912/groups/0 HTTP/1.1" 200 -
192.168.0.13 - - [16/Jun/2019 06:10:26] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:10:29] "GET /api/84312883a7fcbf9d9e6d180df58ba912 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:10:29] "GET /api/84312883a7fcbf9d9e6d180df58ba912/groups/0 HTTP/1.1" 200 -
2019-06-16 06:10:30,277 - root - INFO - sync with lights
2019-06-16 06:10:30,400 - root - ERROR - light 1 is unreachable
Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 226, in syncWithLights
    lights[light]["state"]["hue"] = light_data["hue"] * 180
KeyError: 'hue'
2019-06-16 06:10:30,533 - root - ERROR - light 3 is unreachable
Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 226, in syncWithLights
    lights[light]["state"]["hue"] = light_data["hue"] * 180
KeyError: 'hue'
2019-06-16 06:10:33,627 - root - ERROR - light 2 is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0xb10ac8b0>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='198.168.0.15', port=80): Max retries exceeded with url: /gateways/0x1235/rgbw/1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb10ac8b0>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 214, in syncWithLights
    light_data = json.loads(sendRequest("http://" + addresses[light]["ip"] + "/gateways/" + addresses[light]["device_id"] + "/" + addresses[light]["mode"] + "/" + str(addresses[light]["group"]), "GET", "{}"))
  File "/opt/hue-emulator/functions/request.py", line 19, in sendRequest
    response = requests.get(url, timeout=timeout, headers=head)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='198.168.0.15', port=80): Max retries exceeded with url: /gateways/0x1235/rgbw/1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb10ac8b0>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)'))
192.168.0.13 - - [16/Jun/2019 06:10:36] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:10:39] "GET /api/84312883a7fcbf9d9e6d180df58ba912 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:10:39] "GET /api/84312883a7fcbf9d9e6d180df58ba912/groups/0 HTTP/1.1" 200 -
^C2019-06-16 06:10:45,853 - root - INFO - config saved
Traceback (most recent call last):
  File "./HueEmulator3.py", line 1574, in <module>
    sleep(10)
KeyboardInterrupt
192.168.0.13 - - [16/Jun/2019 06:10:46] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:10:49] "GET /api/84312883a7fcbf9d9e6d180df58ba912 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:10:49] "GET /api/84312883a7fcbf9d9e6d180df58ba912/groups/0 HTTP/1.1" 200 -
2019-06-16 06:10:50,692 - root - INFO - sync with lights
2019-06-16 06:10:50,816 - root - ERROR - light 1 is unreachable
Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 226, in syncWithLights
    lights[light]["state"]["hue"] = light_data["hue"] * 180
KeyError: 'hue'
2019-06-16 06:10:50,945 - root - ERROR - light 3 is unreachable
Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 226, in syncWithLights
    lights[light]["state"]["hue"] = light_data["hue"] * 180
KeyError: 'hue'
2019-06-16 06:10:54,040 - root - ERROR - light 2 is unreachable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0xb65ed230>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='198.168.0.15', port=80): Max retries exceeded with url: /gateways/0x1235/rgbw/1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb65ed230>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 214, in syncWithLights
    light_data = json.loads(sendRequest("http://" + addresses[light]["ip"] + "/gateways/" + addresses[light]["device_id"] + "/" + addresses[light]["mode"] + "/" + str(addresses[light]["group"]), "GET", "{}"))
  File "/opt/hue-emulator/functions/request.py", line 19, in sendRequest
    response = requests.get(url, timeout=timeout, headers=head)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='198.168.0.15', port=80): Max retries exceeded with url: /gateways/0x1235/rgbw/1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb65ed230>, 'Connection to 198.168.0.15 timed out. (connect timeout=3)'))
192.168.0.13 - - [16/Jun/2019 06:10:56] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:10:59] "GET /api/84312883a7fcbf9d9e6d180df58ba912 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:10:59] "GET /api/84312883a7fcbf9d9e6d180df58ba912/groups/0 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:11:09] "GET /api/84312883a7fcbf9d9e6d180df58ba912 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:11:09] "GET /api/84312883a7fcbf9d9e6d180df58ba912/groups/0 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:11:19] "GET /api/84312883a7fcbf9d9e6d180df58ba912 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:11:19] "GET /api/84312883a7fcbf9d9e6d180df58ba912/groups/0 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:11:29] "GET /api/84312883a7fcbf9d9e6d180df58ba912 HTTP/1.1" 200 -
192.168.0.25 - - [16/Jun/2019 06:11:29] "GET /api/84312883a7fcbf9d9e6d180df58ba912/groups/0 HTTP/1.1" 200 -
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
pi@raspberrypi:/opt/hue-emulator $

**Comment by Macopnet** [comment]
Well, i unpaired my lights from the bridge, paired again et seem working good now

**Comment by Macopnet** [comment]
Unpair my lights from the bridge, paired again

i tested with the official Hue app instead Hue essential, and seem working good (no more ERROR - light 1 is unreachable)

If i use Hue essential i have the error again.

**Comment by mariusmotea** [comment]
I was expecting something more interesting in logs, but is just connection timeout. Check your wifi connectivity and set the milight hub cpu clock to 160Mhz.
