### ISSUE TITLE
Unable to Add New Lights

### ISSUE THREAD

**Issue by ryancasler** [diyhue/diyHue#135]
I am unable to add new lights.

**To Reproduce**
Attempt to add lights.

**Expected behavior**
Lights added.

**Logs**
```
2019-06-14 20:24:44,512 - root - INFO - sync with lights
2019-06-14 20:24:44,518 - root - ERROR - light 5 is unreachable
Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 247, in syncWithLights
    updateGroupStats(light, lights, groups)
  File "/opt/hue-emulator/functions/updateGroup.py", line 10, in updateGroupStats
    if lights[group_light]["state"]["on"]:
KeyError: '1'
192.168.1.5 - - [14/Jun/2019 20:24:44] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:44] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:45] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.2 - - [14/Jun/2019 20:24:45] "GET /description.xml HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:45] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:45] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:45] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:45] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:46] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:46] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors/new HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:47] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:47] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors/new HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:47] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:47] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:48] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:48] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors/new HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:49] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:49] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:50] "POST /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
2019-06-14 20:24:50,300 - root - INFO - in post method
2019-06-14 20:24:50,306 - root - INFO - /api/a7161538be80d40b3de98dece6e91f90/lights
2019-06-14 20:24:50,312 - root - INFO - b'{}'
192.168.1.5 - - [14/Jun/2019 20:24:50] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:50] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:51] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:51] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors/new HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:24:52] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
2019-06-14 20:24:55,736 - root - INFO - [
    "192.168.1.4",
    "192.168.1.12",
    "192.168.1.44"
]
2019-06-14 20:24:58,833 - root - INFO - ip 192.168.1.12 is unknow device, HTTPConnectionPool(host='192.168.1.12', port=80): Max retries exceeded with url: /detect (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb51fbff0>, 'Connection to 192.168.1.12 timed out. (connect timeout=3)'))
----------------------------------------
Exception happened during processing of request from ('192.168.1.5', 54000)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 424, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 390, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
2019-06-14 20:25:01,967 - root - INFO - ip 192.168.1.44 is unknow device, HTTPConnectionPool(host='192.168.1.44', port=80): Max retries exceeded with url: /detect (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0xb497a2b0>, 'Connection to 192.168.1.44 timed out. (connect timeout=3)'))
2019-06-14 20:25:02,282 - root - INFO - Starting deconz websocket
192.168.1.2 - - [14/Jun/2019 20:25:17] "GET /description.xml HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:25:17] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:25:17] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.5 - - [14/Jun/2019 20:25:18] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
2019-06-14 20:25:18,927 - root - INFO - sync with lights
2019-06-14 20:25:18,931 - root - ERROR - light 5 is unreachable
Traceback (most recent call last):
  File "/opt/hue-emulator/functions/lightRequest.py", line 247, in syncWithLights
    updateGroupStats(light, lights, groups)
  File "/opt/hue-emulator/functions/updateGroup.py", line 10, in updateGroupStats

```

**Comment by ryancasler** [comment]
I ended up having to rebuild my whole hub since no one got back to me with any ideas.
