### ISSUE TITLE
Can´t connect deconz to hue-emulator

### ISSUE THREAD

**Issue by mduerager** [diyhue/diyHue#144]
Whatever i try, i cant get my Hue Dimmer Switch working with the hue-emulator. I did everything step by step as the documenation states. Unfortunately, the wiki is a little bit outdated because the phoscon webinterface did change a lot. 

What I did so far: 
-Installed deconz and logged into phoscon web app
-connected my dimmer switch to the gateway
-removed to dimmer switch
-went to 'settings' -> 'gateway' -> App Sync (letting 3rd party apps connect to deconz)
- after that whenever i go to the webinterface of the emulator -> 'deconz', i get back an empty website, sayin 'error_empty_page'
-at this stage, the emulator is working normally, just the deconz button does nothing but returning  an empty response.
- when i then login into raspian via ssh, and restart the server (sudo reboot), i then can´t reach it anymore via the webinterface (error_connection_refused). Login via ssh works as before.

I really don´t know what i do miss here... Tried it 3x now, following it step by step, still... not what i expected. Anyone here who can give me a working tutorial on it?

**Comment by mariusmotea** [comment]
You need to run HueEmulator3.py in debug mode to see the output. This is described in Wiki.

**Comment by mduerager** [comment]
Will do that tomorrow and repost then, thx for now!

**Comment by mduerager** [comment]
`2019-07-16 22:40:54,799 - root - INFO - Config loaded
2019-07-16 22:40:54,833 - root - INFO - Starting deconz websocket
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 657, in websocketClient
    from ws4py.client.threadedclient import WebSocketClient
ModuleNotFoundError: No module named 'ws4py'

2019-07-16 22:40:54,844 - root - INFO - sync with lights
2019-07-16 22:40:54,853 - root - INFO - Starting httpd...
2019-07-16 22:40:54,859 - root - INFO - Starting ssl httpd...
10.0.0.6 - - [16/Jul/2019 22:40:55] "GET /description.xml HTTP/1.1" 200 -
10.0.0.32 - - [16/Jul/2019 22:40:56] "GET /description.xml HTTP/1.1" 200 -
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/functions/ssdp.py", line 28, in ssdpSearch
    data = data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdb in position 377: invalid continuation byte
`

This is the output whenever i click on the 'authenticate' button and reload hue-emulator deconz webpage.

**Comment by mduerager** [comment]
I just installed ws4py again (pip3 install ws4py). Same error.

**Comment by mduerager** [comment]
I could make out the ws4py error, had to install it again, using sudo pip3 install ws4py... 🤒 
But then, i tried to bind the deconz gateway, now it says: 

`Using Host IP of 10.0.0.XXX
2019-07-17 13:45:58,599 - root - INFO - b827eb858820
2019-07-17 13:45:58,600 - root - INFO - IP range for light discovery: 0-255
2019-07-17 13:45:58,600 - root - INFO - 127.0.0.1
2019-07-17 13:45:58,603 - root - INFO - Config loaded
Traceback (most recent call last):
  File "./HueEmulator3.py", line 1564, in <module>
    scanDeconz()
  File "./HueEmulator3.py", line 796, in scanDeconz
    bridge_config["deconz"]["websocketport"] = deconz_config["websocketport"]
KeyError: 'websocketport'
`

Webpage not reachable anymore, wether i restart the emulator or reboot the rasp, it still refuses connection, debug output as above...

**Comment by mariusmotea** [comment]
I don't believe there is an issue with the module because you will receive module import error. The issue is between deconz and hue-emulator. The output from deconz don't contain the key "websocketport" and this is mandatory. Probably Deconz don't provide it because there was a problem with previews pair. Please check if systemd file was edited for Deconz in order to run deconz by default on port 8080 with websocket on 8081 (is described in wiki). execute `sudo netstat -lntp` to show used ports on system. Also stop hue-emulator service temporary and change in config.json folowing key: "deconz" => "enabled" must be true, set it to false. Initiate a new pair process.

**Comment by mduerager** [comment]
How to modify config.json?

**Comment by mariusmotea** [comment]
sudo nano /opt/hue-emulator/config.json

**Comment by mduerager** [comment]
Thx, but first i need to reinstall the whole system, cause without any webinterface... its hard... ^^

**Comment by mduerager** [comment]
Also, can you again shortly explain how to pair? Because what is written in the wiki is a little complicated if it was never done correctly before... 
Thx in advance for your support :)

**Comment by mduerager** [comment]
So, i just reinstalled everything, seems deconz websocket is running correctly... But, as soon as i press 'authenticate app' in phoscon webapp, it outputs an error:


2019-07-17 19:54:57,337 - root - INFO - Using Host 10.0.0.14:80
2019-07-17 19:54:57,366 - root - INFO - b827eb858820
2019-07-17 19:54:57,367 - root - INFO - IP range for light discovery: 0-255
2019-07-17 19:54:57,367 - root - INFO - 127.0.0.1
2019-07-17 19:54:57,369 - root - INFO - Config loaded
2019-07-17 19:54:57,403 - root - INFO - Starting deconz websocket
2019-07-17 19:54:57,408 - root - INFO - sync with lights
2019-07-17 19:54:57,416 - root - INFO - Starting httpd...
2019-07-17 19:54:57,428 - root - INFO - Starting ssl httpd...
10.0.0.32 - - [17/Jul/2019 19:55:15] "GET /deconz HTTP/1.1" 200 -
2019-07-17 19:55:15,953 - root - INFO - Starting deconz websocket
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/functions/ssdp.py", line 28, in ssdpSearch
    data = data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdb in position 377: invalid continuation byte

**Comment by mduerager** [comment]
Oh man ohhh man! I just changed time-zone in phoscon to my time-zone i am in. And guess what? Hue-emulator detects my dimmer switch! Just one more problem, shouldnt the switch show up in 'http://my_diyhue_ip/deconz'? Because there is nothing in there. Log shows that button presses are recognized.

**Comment by mariusmotea** [comment]
No, in http://my_diyhue_ip/deconz you see just devices not supported by Hue app and need rules configuration from hue-emulator (xiaomi/tradfri remotes/motion sensors). As the Hue Dimmer Switch is official device and Hue app can configure the rules for it was not necessary to add it to that page.

**Comment by mduerager** [comment]
Ok, great. Still, it shouldn't happen you need to set the correct timezone in order to get it working...
Also, you could add to wiki that you need to install ws4py, cause i didnt see any information about this. 
If you want I can help writing and updating wiki?

**Comment by mduerager** [comment]
Next problem... It´s getting frustrating any time soon. As soon as i click 'add switches and sensors' the hue app crashes to homescreen. Debug outputs following when i press:

Exception happened during processing of request from ('10.0.0.11', 41266)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------

**Comment by mduerager** [comment]
Solved... Deleted switch and re-paired in phoscon, then opened gateway again. Now it works... 
So many hiccups...
If you don´t mind, would really help to get the wiki more up to date and maybe filled with more information, just let me know :)
