### ISSUE TITLE
Another Crash After Updating

### ISSUE THREAD

**Issue by ryancasler** [diyhue/diyHue#159]
So, after updating, I am unable to start the server side....again.  This is the error I get:

```
2019-08-15 01:26:44,021 - root - INFO - Using Host 192.168.1.24:80
2019-08-15 01:26:44,232 - root - INFO - b827eb59c220
2019-08-15 01:26:44,238 - root - INFO - IP range for light discovery: 0-255
2019-08-15 01:26:44,245 - root - INFO - 127.0.0.1
2019-08-15 01:26:44,285 - root - ERROR - CRITICAL! Config file was not loaded
Traceback (most recent call last):
  File "./HueEmulator3.py", line 160, in initialize
    bridge_config = load_config(path)
  File "./HueEmulator3.py", line 331, in load_config
    return json.load(fp)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1757 column 10 (char 52551)

```

For some reason the last two close brace at the end of the config file were just left off after updating.  I don't know why but it prevented the config from loading.  I added the two back in manually, and now I get this error.

```
2019-08-15 01:36:45,637 - root - INFO - Using Host 192.168.1.24:80
2019-08-15 01:36:45,872 - root - INFO - b827eb59c220
2019-08-15 01:36:45,886 - root - INFO - IP range for light discovery: 0-255
2019-08-15 01:36:45,893 - root - INFO - 127.0.0.1
2019-08-15 01:36:45,936 - root - INFO - Config loaded
Traceback (most recent call last):
  File "./HueEmulator3.py", line 1699, in <module>
    initialize()
  File "./HueEmulator3.py", line 177, in initialize
    generateSensorsState()
  File "./HueEmulator3.py", line 368, in generateSensorsState
    for sensor in bridge_config["sensors"]:
KeyError: 'sensors'
```

Also, the documentation is out of date.  You no longer have to enter "True" after "--debug" when running in debug mode.   It would be very helpful if that was updated.  I've put my config file up in pastebin.  If that's the problem, please let me know what I need to edit to fix it.  
https://pastebin.com/S8UvhSTY

Thanks,

**Comment by ryancasler** [comment]
So, it appears that the sensors at the end of the config were not added during the upgrade process, causing the crash at boot.  Here's a pastebin of my fixed config.

https://pastebin.com/p5z9fwhH
