### ISSUE TITLE
Startup failes with MiLight configuration

### ISSUE THREAD

**Issue by maberle** [diyhue/diyHue#16]
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 1752, in <module>
    updateConfig()
  File "/opt/hue-emulator/HueEmulator3.py", line 116, in updateConfig
    if bridge_config["lights"][light]["manufacturername"] == "Philips": #update config lights firmware version

Reason: The MiLight configuration does not contain a field "manufacturername". 

Workaround: Adding the field manually to the config.json file in the lights section

Solution: Check the existence of the key before accessing

**Comment by mariusmotea** [comment]
Thanks, i will fix this issue.
