### ISSUE TITLE
Discovering new lights not possible

### ISSUE THREAD

**Issue by Zappelphilipp** [diyhue/diyHue#166]
in short: everything is working except adding lights. docker container spits out:
```
192.168.0.85 - - [21/Aug/2019 14:54:30] "GET /api/a7161538be80d40b3de98dece6e91f90/lights/new HTTP/1.1" 200 -
192.168.0.85 - - [21/Aug/2019 14:54:30] "GET /api/a7161538be80d40b3de98dece6e91f90/sensors/new HTTP/1.1" 200 -
Exception in thread Thread-41:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/HueEmulator3.py", line 636, in scan_for_lights
    device_data = json.loads(response.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

192.168.0.85 - - [21/Aug/2019 14:54:30] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.0.85 - - [21/Aug/2019 14:54:30] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
```
- ES1812b strip on a wemos d1 mini connected to the wifi and accessible via http.
- docker container with the emulator bridge. 
- essentials and official hue app, both can add the emulator but cannot find the light.

**Comment by Zappelphilipp** [comment]
update: tried to workaroung with the --ip-range switch which does sometimes lead to not crash the script, but even then i dont get my lights to get find.

**Comment by mariusmotea** [comment]
What lights you have connected to the network? Can you ping the lights from docker container?

**Comment by Zappelphilipp** [comment]
its an ESP8266 Controller with an WS2812b lightstrip. yes, it is pingable and i fiddled around with the --ip-range parameter until it didnt crash anymore and then i got it working somehow. 

i already read into the code where it faceplants and try to fix it.

**Comment by Zappelphilipp** [comment]
it suddenly worked (at least once) and i changed nothing. 
```
{
"name": "WS2812 Strip",
"lights": 3,
"protocol": "native_multi",
"modelid": "LST002",
"type": "ws2812_strip",
"mac": "5C:CF:7F:AC:7D:18",
"version": 3.1
}
```
