### ISSUE TITLE
Hue Essentials Effects Crashes Diyhue

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#171]
**Describe the bug**
Running hue essentials effects stored on the bridge causes diyhue freeze and output massive amounts of failures in the logs.
**To Reproduce**
Open Hue Essentials. Open a room and choose effects. Select an effect and choose storage location bridge.
**Expected behavior**
It to not crash diyhue.
**Logs**
If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with `python3 HueEmulator3.py`.
```
127.0.0.1 - - [27/Aug/2019 00:19:33] "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/1/action HTTP/1.1" 200 -
127.0.0.1 - - [27/Aug/2019 00:19:33] "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/1/action HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51306)127.0.0.1 - - [27/Aug/2019 00:19:33] "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/1/action HTTP/1.1" 200 -

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=80): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/opt/hue-emulator/HueEmulator3.py", line 1624, in do_PUT
    rulesProcessor(url_pices[4], current_time)
  File "/opt/hue-emulator/HueEmulator3.py", line 570, in rulesProcessor
    sendRequest("/api/" +    list(bridge_config["config"]["whitelist"])[0] + action["address"], action["method"], json.dumps(action["body"]))
  File "/opt/hue-emulator/functions/request.py", line 16, in sendRequest
    response = requests.put(url, data=bytes(data, "utf8"), timeout=timeout, headers=head)
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=80): Read timed out. (read timeout=3)
----------------------------------------
127.0.0.1 - - [27/Aug/2019 00:19:33] "PUT /api/a7161538be80d40b3de98dece6e91f90/sensors/3/state HTTP/1.1" 200 -
127.0.0.1 - - [27/Aug/2019 00:19:33] "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/1/action HTTP/1.1" 200 -
127.0.0.1 - - [27/Aug/2019 00:19:33] "PUT /api/a7161538be80d40b3de98dece6e91f90/groups/1/action HTTP/1.1" 200 -
ERROR:root:Unexpected error
Traceback (most recent call last):
  File "/opt/hue-emulator/protocols/yeelight.py", line 73, in command
    tcp_socket.connect((ip, int(55443)))
socket.timeout: timed out
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51340)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=80): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/opt/hue-emulator/HueEmulator3.py", line 1624, in do_PUT
    rulesProcessor(url_pices[4], current_time)
  File "/opt/hue-emulator/HueEmulator3.py", line 570, in rulesProcessor
    sendRequest("/api/" +    list(bridge_config["config"]["whitelist"])[0] + action["address"], action["method"], json.dumps(action["body"]))
  File "/opt/hue-emulator/functions/request.py", line 16, in sendRequest
    response = requests.put(url, data=bytes(data, "utf8"), timeout=timeout, headers=head)
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=80): Read timed out. (read timeout=3)

```
**Additional context**

**Comment by mariusmotea** [comment]
This is still in investigation.

**Comment by alexyao2015** [comment]
This still needs to be investigated. Would like to keep this open as a reminder to look into it.
