### ISSUE TITLE
Hue Sync Connection Error

### ISSUE THREAD

**Issue by Zappelphilipp** [diyhue/diyHue#183]
**Describe the bug**
Opening Philips Hue Sync on Win10, finding bridge and getting the information to push connection-button. pushing the "button" on the bridge, nothing happens, getting the following excpetion: 
```
192.168.0.71 - - [06/Sep/2019 23:47:06] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
192.168.0.161 - - [06/Sep/2019 23:47:07] "POST /api/ HTTP/1.1" 200 -
192.168.0.161 - - [06/Sep/2019 23:47:08] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.71', 46218)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------

```

**Comment by mariusmotea** [comment]
This happens every time? Are the devices wired connected to avoid any network connection problem?

> "Connection reset by peer" is the TCP/IP equivalent of slamming the phone back on the hook. It's more polite than merely not replying, leaving one hanging. But it's not the FIN-ACK expected of the truly polite TCP/IP converseur."

**Comment by Zappelphilipp** [comment]
Next day it just worked on the first try. I am not even sure anymore if this error is related or not. I think this issue can be closed until i found more evidence and correlation.
