### ISSUE TITLE
Regression: Cannot create default scenes when a room is created

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#224]
**Describe the bug**
Scenes cannot be created.
**To Reproduce**

Delete config. Start diyhue and config lights. Get error

**Expected behavior**

**Logs**
If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with `python3 HueEmulator3.py`.
```
2019-10-15 00:50:58,359 - root - INFO - b'{"type":"GroupScene","group":"1","name":"Savanna sunset","recycle":false,"appdata":{"version":1,"data":"bM7pc_r01_d15"}}'
----------------------------------------
Exception happened during processing of request from ('192.168.1.134', 41472)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/opt/hue-emulator/HueEmulator3.py", line 1482, in do_POST
    for light in post_dictionary["lights"]:
KeyError: 'lights'
----------------------------------------

```
**Additional context**

**Comment by alexyao2015** [comment]
Related to this commit
https://github.com/diyhue/diyHue/commit/f6417828653acf81b5d716657bd8aa0843f47b66

**Comment by mariusmotea** [comment]
I made a commit now. Hope this is fixed for good.

**Comment by alexyao2015** [comment]
Awesome. Its fixed.
