### ISSUE TITLE
F.Lux will not pair

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#238]
**Describe the bug**
F.lux, a yellow light blocker application on windows, will not pair.
**To Reproduce**

**Expected behavior**

**Logs**
If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with `python3 HueEmulator3.py`.
192.168.1.132 - - [20/Oct/2019 03:48:59] "GET /description.xml HTTP/1.1" 200 -
192.168.1.132 - - [20/Oct/2019 03:48:59] "GET /description.xml HTTP/1.1" 200 -
192.168.1.132 - - [20/Oct/2019 03:48:59] code 404, message not found
192.168.1.132 - - [20/Oct/2019 03:48:59] "GET /api/ HTTP/1.1" 404 -

**Additional context**
I don't have a bridge so I don't know what it should be getting if it visits /api or /description.xml

**Comment by mariusmotea** [comment]
somehow i miss this issue. I think it can be fixed quickly by allowing `/api/ HTTP/` like ` /api/ nouser/`

**Comment by mariusmotea** [comment]
I made a commit to fix at last the first issue of the pair process. Can you test now to see if is working properly?

**Comment by alexyao2015** [comment]
Alright so I've discovered that this commit was the reason why sleep and huematic stopped working entirely....

**Comment by alexyao2015** [comment]
Progress... It seems that it sends something to /api through a POST

```
192.168.1.132 - - [18/Nov/2019 06:43:41] "POST /api HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.132', 59893)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/opt/hue-emulator/HueEmulator3.py", line 1565, in do_POST
    post_dictionary = json.loads(raw_json)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 23 (char 22)
----------------------------------------
```

**Comment by mariusmotea** [comment]
Json library is unable to decode the post content.

**Comment by alexyao2015** [comment]
Hmm this is the output from raw_json

`{"devicetype":"f.lux"}`

**Comment by mariusmotea** [comment]
Must be some special characters  somewhere.

**Comment by mariusmotea** [comment]
`print(repr(raw_json))` will display also the special characters, i expect some \r\n or other windows characteristic characters

**Comment by alexyao2015** [comment]
Problem 1 fixed, now problem 2. Doesn't like something because it keeps spamming after link button is pressed.

192.168.1.132 - - [18/Nov/2019 17:13:26] "POST /api HTTP/1.1" 200 -
2019-11-18 17:13:26,328 - root - INFO - in post method
2019-11-18 17:13:26,329 - root - INFO - /api
2019-11-18 17:13:26,329 - root - DEBUG - '{"devicetype":"f.lux"}\x00'
2019-11-18 17:13:26,330 - root - INFO - b'{"devicetype":"f.lux"}\x00'
2019-11-18 17:13:26,332 - root - INFO - [
    {
        "success": {
            "username": "bbc204fc0a2611ea8004000c295d1e1c"
        }
    }
]
192.168.1.132 - - [18/Nov/2019 17:13:26] "POST /api HTTP/1.1" 200 -
2019-11-18 17:13:26,351 - root - INFO - in post method
2019-11-18 17:13:26,351 - root - INFO - /api
2019-11-18 17:13:26,351 - root - DEBUG - '{"devicetype":"f.lux"}\x00'
2019-11-18 17:13:26,352 - root - INFO - b'{"devicetype":"f.lux"}\x00'
2019-11-18 17:13:26,353 - root - INFO - [
    {
        "success": {
            "username": "bbc5469e0a2611ea8004000c295d1e1c"
        }
    }
]
