### ISSUE TITLE
DIYHue with Raspbee on Raspberry

### ISSUE THREAD

**Issue by AxelF1977** [diyhue/diyHue#266]
Hello,

I´m sorry for my next question, but I don´t get it.

First I tried to use DIYHue with an import of my HUE Ligfhts from my bridge. It workes. I have seen then, that it is using the HUE Bridge to controll the light, but it worked.

I have a rasbee module as well and prefer to use this.

I tried to install all with this instruction https://diyhue.readthedocs.io/en/latest/lights/raspbee.html#deconz-installation

But I don´t get it. Installed DIYHue first, stoped it, installed deCONz, and did anything like in the instrction, but it don´t work, DIYHue is not working with DeConz, I do not get the lights into DIYHUE.

Whats´the right way to combine my Rasberry with Raspbee and DIYHue. 

I had a problem with the standart scenes when I used DIYHue with the HUE briges. After I tried to use a standard scene in a romm, the lamps switched off. Do you want me to open a sepperate issue?

**Comment by mariusmotea** [comment]
Ensure you changed the deconz service file and it use the new ports. You can check with command `sudo netstat -lntp`. Deconz must use the ports 8080 and 8081.

**Comment by AxelF1977** [comment]
Hi,

yes, I changed the ports in the file. I can use deconz with <ip>:8080 But to go to <ipdiyhue>/deconz has no effect. 

There is just a save button, if I klick it ot not, ne effect. I can add new lights to deconz, but they don´t pop up in diyhue. 

BUT, the is a smal problem i see now, port 8081 is already in use with ioBroker on the Raspy

**Comment by mariusmotea** [comment]
you will need to start the bridge emulator in debug to see what is happening. Please check the wiki to see how to do that.

**Comment by AxelF1977** [comment]
What I get is this

`:/opt/hue-emulator $ sudo ./HueEmulator3.py
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/functions/entertainment.py", line 9, in entertainmentService
    serverSocket.bind(('127.0.0.1', 2101))
OSError: [Errno 98] Address already in use

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1840, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1827, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use`

**Comment by alexyao2015** [comment]
Lets move this to Slack as well
