### ISSUE TITLE
list index out of range when  scanForLights

### ISSUE THREAD

**Issue by daniel-a-h** [diyhue/diyHue#289]
Below is the debug output I get when scanning for a light.
I have a brand new docker image for diyHue and a single ESP8622 that I want to discover. Scans stop with the exception below:
```
2019-11-17 05:21:16,778 - root - INFO - in post method
2019-11-17 05:21:16,782 - root - INFO - /api/hueess2c08fa11ea832900a0983e9dfc/lights
2019-11-17 05:21:16,784 - root - INFO - b'{}'
2019-11-17 05:21:16,797 - root - DEBUG - tasmota: <discover> invoked!
2019-11-17 05:21:16,806 - root - DEBUG - ESPHome: <discover> invoked!
2019-11-17 05:21:19,799 - root - DEBUG - Yeelight search end
2019-11-17 05:21:21,891 - root - INFO - [
    "192.168.1.1:80",
    "192.168.1.4:80",
    "192.168.1.25:80",
    "192.168.1.96:80"
]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/HueEmulator3.py", line 716, in scan_for_lights
    logging.debug('devs', device_ips)
Message: 'devs'
Arguments: (['192.168.1.1:80', '192.168.1.4:80', '192.168.1.25:80', '192.168.1.96:80'],)
2019-11-17 05:21:21,935 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.1:80
2019-11-17 05:21:21,953 - urllib3.connectionpool - DEBUG - http://192.168.1.1:80 "GET /detect HTTP/1.1" 404 1703
2019-11-17 05:21:21,974 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.4:80
2019-11-17 05:21:22,070 - urllib3.connectionpool - DEBUG - http://192.168.1.4:80 "GET /detect HTTP/1.1" 404 None
2019-11-17 05:21:22,097 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.25:80
2019-11-17 05:21:22,111 - urllib3.connectionpool - DEBUG - http://192.168.1.25:80 "GET /detect HTTP/1.1" 307 180
2019-11-17 05:21:22,121 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): 192.168.1.25:443
2019-11-17 05:21:22,209 - root - INFO - ip 192.168.1.25:80 is unknown device: HTTPSConnectionPool(host='192.168.1.25', port=443): Max retries exceeded with url: /detect (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))
2019-11-17 05:21:22,225 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.96:80
2019-11-17 05:21:22,240 - urllib3.connectionpool - DEBUG - http://192.168.1.96:80 "GET /detect HTTP/1.1" 200 102
2019-11-17 05:21:22,248 - root - INFO - {
    "hue": "strip",
    "lights": 1,
    "mac": "8f:c7:b3:c2:dd:bc",
    "modelid": "LST002",
    "name": "WS2812 Hue Strip"
}
2019-11-17 05:21:22,249 - root - INFO - 192.168.1.96:80 is WS2812 Hue Strip
2019-11-17 05:21:22,250 - root - INFO - Add new light: WS2812 Hue Strip
2019-11-17 05:21:22,251 - root - INFO - ip 192.168.1.96:80 is unknown device: list index out of range
```

I believe the Problem is in the last line of the log output

**Comment by alexyao2015** [comment]
Does the light get added to the config? It seems that the error is only cosmetic?

**Comment by roshan2908** [comment]
cant add light from yesterday

**Comment by alexyao2015** [comment]
Run this build and post debug logs when adding the light
https://github.com/diyhue/diyHue/tree/debuglightscan

**Comment by roshan2908** [comment]
2019-11-17 07:00:27,914 - root - INFO - [
    "192.168.31.1:80",
    "192.168.31.191:80"
]
2019-11-17 07:00:27,955 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.31.1:80
2019-11-17 07:00:28,168 - urllib3.connectionpool - DEBUG - http://192.168.31.1:80 "GET /detect HTTP/1.1" 404 162
2019-11-17 07:00:28,224 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.31.191:80
2019-11-17 07:00:28,410 - urllib3.connectionpool - DEBUG - http://192.168.31.191:80 "GET /detect HTTP/1.1" 200 145
2019-11-17 07:00:28,440 - root - INFO - {
    "lights": 4,
    "mac": "__________",
    "modelid": "LST002",
    "name": "Hue WS2812 strip",
    "protocol": "native_multi",
    "type": "ws2812_strip",
    "version": 3.1
}
2019-11-17 07:00:28,453 - root - INFO - 192.168.31.191:80 is Hue WS2812 strip
2019-11-17 07:00:28,461 - root - INFO - Add new light: Hue WS2812 strip
2019-11-17 07:00:28,465 - root - DEBUG - Debug String 1
2019-11-17 07:00:28,470 - root - DEBUG - Debug String 2:None
2019-11-17 07:00:28,474 - root - DEBUG - Debug String 3
2019-11-17 07:00:28,479 - root - DEBUG - Debug String 4
2019-11-17 07:00:28,483 - root - DEBUG - Debug String 5
2019-11-17 07:00:28,489 - root - INFO - ip 192.168.31.191:80 is unknown device: list index out of range
2019-11-17 07:00:28,522 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:8080
