### ISSUE TITLE
diyHue issue with Ambilight TV

### ISSUE THREAD

**Issue by luk001** [diyhue/diyHue#313]
Hi, I have connected my Philips TV to diyHue, diyhue is detected as Bridge, I can configure the lamp but the lamp does not seem to sync.

The following error appears in the debug:

```
192.168.178.39 - - [24/Dec/2019 09:49:53] "GET /api/72d5fa3c263211ea9345b827ebc75792/groups/null HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.178.39', 41953)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1562, in do_GET
    self._set_end_headers(bytes(json.dumps(bridge_config[url_pices[3]][url_pices[4]],separators=(',', ':'),ensure_ascii=False), "utf8"))
KeyError: 'null'
```

**Comment by mariusmotea** [comment]
the request looks to be invalid as it contain `null` instead of a group id

**Comment by ihearcolors** [comment]
The way i do it is to add the lights to the bridge in the hue app first then config the tv with the bridge. Ps if you use a pc, ScreenBloom will sync way better than ambilight tv's....well cheap ones anyway.
