### ISSUE TITLE
conenction to deconz failed add switch and lights

### ISSUE THREAD

**Issue by zbizel** [diyhue/diyHue#321]
**Describe the bug**
platform: raspberry -  Raspbian GNU/Linux 10 (buster)
deconz installed automatically
Python 3.7.3

/lib/systemd/system/deconz.service
[Unit]
Description=deCONZ: ZigBee gateway -- REST API
Wants=deconz-init.service deconz-update.service

[Service]
User=1000
ExecStart=/usr/bin/deCONZ -platform minimal --http-port=8080 --upnp=0 --ws-port=8081
Restart=on-failure
StartLimitIntervalSec=0
RestartSec=30
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_KILL CAP_SYS_BOOT CAP_SYS_TIME

[Install]
WantedBy=multi-user.target

**To Reproduce**
1. Go to deconz software gateway and enable athenticate app 
2. Go to diyhue and click deconz
3. add dimmer, after that see error - page not found

**Logs**

192.168.0.105 - - [04/Jan/2020 15:04:40] "GET /api/FC2135F90D/groups?_=1578145605735 HTTP/1.1" 200 -
2020-01-04 15:04:44,459 - root - DEBUG - Sending M-Search response to 192.168.0.105
192.168.0.105 - - [04/Jan/2020 15:04:44] "GET /deconz?4=ZGPSwitch&mode_4=CT HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.105', 36143)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1436, in do_GET
    self._set_end_headers(bytes(webformDeconz({"deconz": bridge_config["deconz"], "sensors": bridge_config["sensors"], "groups": bridge_config["groups"]}), "utf8"))
  File "/opt/hue-emulator/functions/html.py", line 187, in webformDeconz
    if bridge_config["deconz"]["sensors"][deconzSensor]["modelid"] == "TRADFRI motion sensor":
KeyError: 'modelid'
----------------------------------------
192.168.0.105 - - [04/Jan/2020 15:04:44] "GET /deconz?4=ZGPSwitch&mode_4=CT HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.105', 36124)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1436, in do_GET
    self._set_end_headers(bytes(webformDeconz({"deconz": bridge_config["deconz"], "sensors": bridge_config["sensors"], "groups": bridge_config["groups"]}), "utf8"))
  File "/opt/hue-emulator/functions/html.py", line 187, in webformDeconz
    if bridge_config["deconz"]["sensors"][deconzSensor]["modelid"] == "TRADFRI motion sensor":
KeyError: 'modelid'
----------------------------------------
192.168.0.105 - - [04/Jan/2020 15:04:44] "GET /deconz?4=ZGPSwitch&mode_4=CT HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.105', 36144)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1436, in do_GET
    self._set_end_headers(bytes(webformDeconz({"deconz": bridge_config["deconz"], "sensors": bridge_config["sensors"], "groups": bridge_config["groups"]}), "utf8"))
  File "/opt/hue-emulator/functions/html.py", line 187, in webformDeconz
    if bridge_config["deconz"]["sensors"][deconzSensor]["modelid"] == "TRADFRI motion sensor":
KeyError: 'modelid'
----------------------------------------
192.168.0.105 - - [04/Jan/2020 15:04:44] "GET /deconz?4=ZGPSwitch&mode_4=CT HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.105', 36060)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1436, in do_GET
    self._set_end_headers(bytes(webformDeconz({"deconz": bridge_config["deconz"], "sensors": bridge_config["sensors"], "groups": bridge_config["groups"]}), "utf8"))
  File "/opt/hue-emulator/functions/html.py", line 187, in webformDeconz
    if bridge_config["deconz"]["sensors"][deconzSensor]["modelid"] == "TRADFRI motion sensor":
KeyError: 'modelid'
----------------------------------------
192.168.0.105 - - [04/Jan/2020 15:04:44] "GET /deconz?4=ZGPSwitch&mode_4=CT HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.105', 36206)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1436, in do_GET
    self._set_end_headers(bytes(webformDeconz({"deconz": bridge_config["deconz"], "sensors": bridge_config["sensors"], "groups": bridge_config["groups"]}), "utf8"))
  File "/opt/hue-emulator/functions/html.py", line 187, in webformDeconz
    if bridge_config["deconz"]["sensors"][deconzSensor]["modelid"] == "TRADFRI motion sensor":
KeyError: 'modelid'_

**Comment by mariusmotea** [comment]
I had same issue in the past. The root cause is in Deconz as new sensors are exposed without "modelid" value. I think you need a fresh install of diyhue.

**Comment by zbizel** [comment]
Hi  Marius
This installation is fresh in a fresh updated raspbian
I downloaded now sources from git and run. I have the same issue.

**Comment by alexyao2015** [comment]
Try using the beta branch.

**Comment by tchabaud** [comment]
Hello,
Can you reopen this issue please ? I have exactly the same problem, with the docker image tagged stable-latest.
I get the following error when I browse to /deconz and try to add devices :

```Exception happened during processing of request from ('192.168.48.6', 36492)                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                                                   
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread                                                                                                                                     
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/opt/hue-emulator/HueEmulator3.py", line 1417, in do_GET
    self._set_end_headers(bytes(webformDeconz({"deconz": bridge_config["deconz"], "sensors": bridge_config["sensors"], "groups": bridge_config["groups"]}), "utf8"))
  File "/opt/hue-emulator/functions/html.py", line 187, in webformDeconz
    if bridge_config["deconz"]["sensors"][deconzSensor]["modelid"] == "TRADFRI motion sensor":
KeyError: 'modelid'
```
