### ISSUE TITLE
Motionsensor doesn't work 

### ISSUE THREAD

**Issue by Xorfee** [diyhue/diyHue#323]
**Describe the bug**
I have diyhue emulator and deconz installed on my raspberry. 
Emulator is listening port 80 while deconz works at 8080. 

I started to pair my hue motion sensor with raspbee and deconz and imported my motion sensor to diyhue.. With the nativ hue app I am not able to set anything with my motion sensor, with hue essentials I am able to, but it doesn't react or even works. The only methode to trigger my lamps is, setting some behaviour on the deconz page, while this works only with my zigsbee devices I am not able to control my esp8266 lamps. 

So what I did next was, buying some HC S501 Pir sensors and pair that with my wemos d1 mini. I connected ground with ground 5v to 5v and d1 to the middle connector of my pir sensor. I just put that get request on the api, and this recognized my hue emulator as a motion sensor. But it still does not work my hue sensor isn't decting any movements..

**Comment by mariusmotea** [comment]
Is know currently is not able to set the motion sensor in Hue app, but it must work if you set it in Hue Essentials. Please show some debug output during sensor trigger. Also ensure the light sensor send "dark=true" because the light will be turned on only if outside is dark.

**Comment by Xorfee** [comment]
It still does not work..

Motion Sensor detects when i am using a simple sketch like this 
#define PIR_PIN D3

void setup(void) {
   pinMode(PIR_PIN, INPUT);
   Serial.begin(9600);
}
void loop() {
  if (digitalRead(PIR_PIN) == HIGH) {
    Serial.println("Motion detected!");
  } else {
    Serial.println("No motion detected");
  }
  delay(1000);
}

But when i am using Hue Essentials with Dark=True or even false it does not detect anything..

**Comment by mariusmotea** [comment]
Start the emulator in debug mode please and show output during motion sensor triggering.

**Comment by Xorfee** [comment]
Even Hue Motion Sensor isnt working at all.. when i am using it on essentials. its i can click on it but it will kick me back.. 

cant find the command to enable debug..
nano HueEmulator3.py when i type this it shows me this: 
if args.debug or (os.getenv('DEBUG') and (os.getenv('DEBUG') == "true" or os.ge$
    root = logging.getLogger()
    root.setLevel(logging.DEBUG)
    ch = logging.StreamHandler(sys.stdout)
    ch.setLevel(logging.DEBUG)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(m$
    ch.setFormatter(formatter)
    root.addHandler(ch)

**Comment by mariusmotea** [comment]
```
cd /opt/hue-emulator
sudo ./HueEmulator3.py --debug
```
Trigger the sensor and show the output.

**Comment by Xorfee** [comment]
Will test it out on weekend. Thx will post then the results. When I type this on my headless raspberry do i get the results on ssh Afterwards?

**Comment by Xorfee** [comment]
pi@raspberrypi:~ $ cd /opt/hue-emulator
pi@raspberrypi:/opt/hue-emulator $ sudo ./HueEmulator3.py --debug
2020-01-12 10:26:08,114 - root - INFO - Using Host 192.168.178.71:80
2020-01-12 10:26:08,144 - root - INFO - dca63252893e
2020-01-12 10:26:08,145 - root - INFO - IP range for light discovery: 0-255
2020-01-12 10:26:08,145 - root - INFO - 127.0.0.1
2020-01-12 10:26:08,145 - root - INFO - Online Discovery/Remote API Enabled!
2020-01-12 10:26:08,152 - root - INFO - Config loaded
2020-01-12 10:26:08,160 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 127.0.0.1:8080
2020-01-12 10:26:08,166 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8080                                                                                                                                                              "GET /api/283145a4e198cc6535/config HTTP/1.1" 200 6147
2020-01-12 10:26:08,169 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 127.0.0.1:8080
2020-01-12 10:26:08,174 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8080                                                                                                                                                              "GET /api/283145a4e198cc6535/lights HTTP/1.1" 200 6838
2020-01-12 10:26:08,178 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 127.0.0.1:8080
2020-01-12 10:26:08,181 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8080                                                                                                                                                              "GET /api/283145a4e198cc6535/sensors HTTP/1.1" 200 2686
2020-01-12 10:26:08,183 - root - INFO - Starting deconz websocket
2020-01-12 10:26:08,185 - root - DEBUG - starting ssdp...
2020-01-12 10:26:08,185 - root - DEBUG - start ssdp broadcast
2020-01-12 10:26:08,197 - root - INFO - sync with lights
2020-01-12 10:26:08,200 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,213 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/1 HTTP/1.1" 200 402
2020-01-12 10:26:08,218 - urllib3.connectionpool - DEBUG - Starting new HTTPS co                                                                                                                                                             nnection (1): discovery.diyhue.org:443
2020-01-12 10:26:08,221 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,231 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/2 HTTP/1.1" 200 395
2020-01-12 10:26:08,235 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/functions/entertainment.py", line 9, in entertainmentS                                                                                                                                                             ervice
    serverSocket.bind(('127.0.0.1', 2101))
OSError: [Errno 98] Address already in use

2020-01-12 10:26:08,245 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/3 HTTP/1.1" 200 268
2020-01-12 10:26:08,252 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,256 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/4 HTTP/1.1" 200 282
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1933, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

2020-01-12 10:26:08,264 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,268 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/5 HTTP/1.1" 200 399
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1920, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

2020-01-12 10:26:08,277 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,291 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/6 HTTP/1.1" 200 401
2020-01-12 10:26:08,297 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,302 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/7 HTTP/1.1" 200 400
2020-01-12 10:26:08,307 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,310 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/8 HTTP/1.1" 200 396
2020-01-12 10:26:08,314 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,317 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/9 HTTP/1.1" 200 402
2020-01-12 10:26:08,320 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,323 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/10 HTTP/1.1" 200 404
2020-01-12 10:26:08,327 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,329 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/11 HTTP/1.1" 200 353
2020-01-12 10:26:08,333 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.58:80
2020-01-12 10:26:08,343 - urllib3.connectionpool - DEBUG - http://192.168.178.58                                                                                                                                                             :80 "GET /get?light=1 HTTP/1.1" 200 99
2020-01-12 10:26:08,347 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.67:80
2020-01-12 10:26:08,481 - urllib3.connectionpool - DEBUG - http://192.168.178.67                                                                                                                                                             :80 "GET /get?light=1 HTTP/1.1" 200 100
2020-01-12 10:26:08,500 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.72:80
2020-01-12 10:26:08,507 - root - INFO - deltaSunsetOffset: 24384.492901
2020-01-12 10:26:08,507 - root - INFO - deltaSunriseOffset: -1955.5071160000002
2020-01-12 10:26:08,507 - root - INFO - set daylight sensor to true
2020-01-12 10:26:08,532 - urllib3.connectionpool - DEBUG - http://192.168.178.72                                                                                                                                                             :80 "GET /state HTTP/1.1" 200 94
2020-01-12 10:26:08,535 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,537 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/08830F1FE9/lights/21 HTTP/1.1" 200 343
2020-01-12 10:26:08,541 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,543 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/08830F1FE9/lights/22 HTTP/1.1" 200 344
2020-01-12 10:26:08,548 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,550 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/12 HTTP/1.1" 200 268
2020-01-12 10:26:08,555 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,557 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/F243567EBD/lights/24 HTTP/1.1" 200 266
2020-01-12 10:26:08,561 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,563 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/13 HTTP/1.1" 200 268
2020-01-12 10:26:08,567 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,570 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/14 HTTP/1.1" 200 268
2020-01-12 10:26:08,574 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,577 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/15 HTTP/1.1" 200 286
2020-01-12 10:26:08,582 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,585 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/16 HTTP/1.1" 200 290
2020-01-12 10:26:08,589 - urllib3.connectionpool - DEBUG - Starting new HTTP con                                                                                                                                                             nection (1): 192.168.178.71:8080
2020-01-12 10:26:08,592 - urllib3.connectionpool - DEBUG - http://192.168.178.71                                                                                                                                                             :8080 "GET /api/2135F90D23/lights/17 HTTP/1.1" 200 291
2020-01-12 10:26:08,603 - urllib3.connectionpool - DEBUG - https://discovery.diy                                                                                                                                                             hue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2020-01-12 10:26:21,336 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 10:26:26,036 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 10:26:34,524 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 10:26:35,937 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 10:26:38,634 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-01-12 10:26:38,793 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2020-01-12 10:26:41,743 - root - DEBUG - Sending M-Search response to 192.168.178.1



nothing special at all

**Comment by Xorfee** [comment]
Also added the Hue Motion Sensor afterwards.. 

2020-01-12 10:36:43,238 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-01-12 10:36:43,449 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2020-01-12 10:36:44,920 - root - INFO - {"config":{"alert":"none","delay":0,"ledindication":false,"on":true,"reachable":true,"sensitivity":0,"sensitivitymax":2,"usertest":false},"e":"changed","id":"9","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 10:36:44,920 - root - INFO - unable to process the request'9'
2020-01-12 10:36:44,923 - root - INFO - {"config":{"alert":"none","ledindication":false,"offset":0,"on":true,"reachable":true,"usertest":false},"e":"changed","id":"10","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0402"}
2020-01-12 10:36:44,923 - root - INFO - unable to process the request'10'
2020-01-12 10:36:44,925 - root - INFO - {"config":{"alert":"none","ledindication":false,"on":true,"reachable":true,"tholddark":12000,"tholdoffset":7000,"usertest":false},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0400"}
2020-01-12 10:36:44,925 - root - INFO - unable to process the request'11'
2020-01-12 10:36:45,757 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 10:36:55,566 - root - INFO - {"config":{"alert":"none","delay":0,"ledindication":false,"on":true,"reachable":true,"sensitivity":0,"sensitivitymax":2,"usertest":false},"e":"changed","id":"9","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 10:36:55,566 - root - INFO - unable to process the request'9'
2020-01-12 10:36:55,568 - root - INFO - {"config":{"alert":"none","ledindication":false,"offset":0,"on":true,"reachable":true,"usertest":false},"e":"changed","id":"10","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0402"}
2020-01-12 10:36:55,568 - root - INFO - unable to process the request'10'
2020-01-12 10:36:55,570 - root - INFO - {"config":{"alert":"none","ledindication":false,"on":true,"reachable":true,"tholddark":12000,"tholdoffset":7000,"usertest":false},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0400"}
2020-01-12 10:36:55,570 - root - INFO - unable to process the request'11'
2020-01-12 10:37:05,533 - root - INFO - {"config":{"alert":"none","delay":0,"ledindication":false,"on":true,"reachable":true,"sensitivity":0,"sensitivitymax":2,"usertest":false},"e":"changed","id":"9","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 10:37:05,533 - root - INFO - unable to process the request'9'
2020-01-12 10:37:05,535 - root - INFO - {"config":{"alert":"none","ledindication":false,"offset":0,"on":true,"reachable":true,"usertest":false},"e":"changed","id":"10","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0402"}
2020-01-12 10:37:05,535 - root - INFO - unable to process the request'10'
2020-01-12 10:37:05,537 - root - INFO - {"config":{"alert":"none","ledindication":false,"on":true,"reachable":true,"tholddark":12000,"tholdoffset":7000,"usertest":false},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0400"}
2020-01-12 10:37:05,537 - root - INFO - unable to process the request'11'
2020-01-12 10:37:13,482 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-01-12 10:37:13,697 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2020-01-12 10:37:15,558 - root - INFO - {"config":{"alert":"none","delay":0,"ledindication":false,"on":true,"reachable":true,"sensitivity":2,"sensitivitymax":2,"usertest":false},"e":"changed","id":"9","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 10:37:15,559 - root - INFO - unable to process the request'9'
2020-01-12 10:37:17,561 - root - INFO - {"e":"changed","id":"9","r":"sensors","state":{"lastupdated":"2020-01-12T10:37:17","presence":true},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 10:37:17,562 - root - INFO - unable to process the request'9'
2020-01-12 10:37:18,528 - root - INFO - {"config":{"alert":"none","battery":56,"delay":0,"ledindication":false,"on":true,"reachable":true,"sensitivity":2,"sensitivitymax":2,"usertest":false},"e":"changed","id":"9","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 10:37:18,529 - root - INFO - unable to process the request'9'
2020-01-12 10:37:18,532 - root - INFO - {"config":{"alert":"none","battery":56,"ledindication":false,"offset":0,"on":true,"reachable":true,"usertest":false},"e":"changed","id":"10","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0402"}
2020-01-12 10:37:18,532 - root - INFO - unable to process the request'10'
2020-01-12 10:37:18,536 - root - INFO - {"config":{"alert":"none","battery":56,"ledindication":false,"on":true,"reachable":true,"tholddark":12000,"tholdoffset":7000,"usertest":false},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0400"}
2020-01-12 10:37:18,536 - root - INFO - unable to process the request'11'
2020-01-12 10:37:19,474 - root - INFO - {"e":"changed","id":"10","r":"sensors","state":{"lastupdated":"2020-01-12T10:37:19","temperature":1277},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0402"}
2020-01-12 10:37:19,475 - root - INFO - unable to process the request'10'
2020-01-12 10:37:22,422 - root - DEBUG - Sending M-Search response to 192.168.178.51
2020-01-12 10:37:40,088 - root - INFO - {"config":{"battery":4,"group":"8252","on":true,"reachable":true},"e":"changed","id":"7","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:c8:9b:9e-02-fc00"}
2020-01-12 10:37:43,736 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-01-12 10:37:43,909 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2020-01-12 10:37:54,201 - root - DEBUG - Sending M-Search response to 192.168.178.51
2020-01-12 10:37:55,312 - root - INFO - {"config":{"alert":"none","battery":87,"on":true,"reachable":true},"e":"changed","id":"4","r":"sensors","t":"event","uniqueid":"cc:cc:cc:ff:fe:d4:61:57-01-1000"}
2020-01-12 10:38:02,769 - root - INFO - {"config":{"battery":90,"group":"26366","on":true,"reachable":true},"e":"changed","id":"8","r":"sensors","t":"event","uniqueid":"00:17:88:01:04:f6:d5:0d-02-fc00"}
2020-01-12 10:38:08,115 - root - DEBUG - Sending M-Search response to 192.168.178.51
2020-01-12 10:38:09,418 - root - DEBUG - Sending M-Search response to 192.168.178.51
2020-01-12 10:38:11,220 - root - DEBUG - Sending M-Search response to 192.168.178.51
2020-01-12 10:38:13,949 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-01-12 10:38:14,138 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}


Hue Essentials gets everytime a motion trigger if i test the motion sensor although i am not triggering the sensor

**Comment by Xorfee** [comment]
2020-01-12 11:19:52,973 - root - INFO - deltaSunsetOffset: 21163.026212
2020-01-12 11:19:52,974 - root - INFO - deltaSunriseOffset: -5180.973808
2020-01-12 11:19:52,974 - root - INFO - set daylight sensor to true
2020-01-12 11:20:01,274 - root - INFO - {"e":"changed","id":"9","r":"sensors","state":{"lastupdated":"2020-01-12T11:20:01","presence":false},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 11:20:21,601 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 11:20:22,949 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-01-12 11:20:23,152 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2020-01-12 11:20:26,200 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 11:20:36,298 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 11:20:37,910 - root - INFO - {"e":"changed","id":"9","r":"sensors","state":{"lastupdated":"2020-01-12T11:20:37","presence":true},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 11:20:38,001 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 11:20:38,015 - root - INFO - {"e":"changed","id":"11","r":"sensors","state":{"dark":true,"daylight":false,"lastupdated":"2020-01-12T11:20:38","lightlevel":8485,"lux":7},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0400"}
2020-01-12 11:20:41,502 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 11:20:42,940 - root - INFO - {"e":"changed","id":"11","r":"sensors","state":{"dark":true,"daylight":false,"lastupdated":"2020-01-12T11:20:42","lightlevel":10635,"lux":12},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0400"}
2020-01-12 11:20:53,180 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-01-12 11:20:53,449 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2020-01-12 11:21:18,512 - root - DEBUG - Sending M-Search response to 192.168.178.51
2020-01-12 11:21:23,491 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-01-12 11:21:23,664 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2020-01-12 11:21:33,096 - root - DEBUG - Sending M-Search response to 192.168.178.51
2020-01-12 11:21:34,597 - root - DEBUG - Sending M-Search response to 192.168.178.51
2020-01-12 11:21:41,906 - root - DEBUG - Sending M-Search response to 192.168.178.51
2020-01-12 11:21:43,708 - root - DEBUG - Sending M-Search response to 192.168.178.51
2020-01-12 11:21:53,700 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-01-12 11:21:53,902 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2020-01-12 11:21:55,140 - root - INFO - {"e":"changed","id":"9","r":"sensors","state":{"lastupdated":"2020-01-12T11:21:55","presence":false},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 11:21:55,901 - root - INFO - {"e":"changed","id":"10","r":"sensors","state":{"lastupdated":"2020-01-12T11:21:55","temperature":1361},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0402"}
2020-01-12 11:22:04,211 - root - INFO - {"e":"changed","id":"9","r":"sensors","state":{"lastupdated":"2020-01-12T11:22:04","presence":true},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 11:22:19,272 - root - INFO - {"e":"changed","id":"11","r":"sensors","state":{"dark":false,"daylight":false,"lastupdated":"2020-01-12T11:22:19","lightlevel":14769,"lux":30},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0400"}
2020-01-12 11:22:22,016 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 11:22:23,912 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-01-12 11:22:24,108 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2020-01-12 11:22:26,616 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 11:22:29,591 - root - INFO - {"e":"changed","id":"9","r":"sensors","state":{"lastupdated":"2020-01-12T11:22:29","presence":false},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 11:22:36,419 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 11:22:38,021 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 11:22:41,218 - root - DEBUG - Sending M-Search response to 192.168.178.1
2020-01-12 11:22:47,493 - root - INFO - {"config":{"battery":3,"group":"8252","on":true,"reachable":true},"e":"changed","id":"7","r":"sensors","t":"event","uniqueid":"00:17:88:01:03:c8:9b:9e-02-fc00"}
2020-01-12 11:22:47,994 - root - INFO - {"e":"changed","id":"9","r":"sensors","state":{"lastupdated":"2020-01-12T11:22:47","presence":true},"t":"event","uniqueid":"00:17:88:01:03:28:99:bb-02-0406"}
2020-01-12 11:22:54,148 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-01-12 11:22:54,356 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}


here is the latest event of my diy hue Motion sensor... data pin connected to D1 on wemos doesnt change anything

**Comment by mariusmotea** [comment]
I see requests just from an original motion sensor paired to deconz. No http requests from any wemos sensor. Can you show a photo with your sensor? did you specify the correct ip address of the emulator in the sketch?

**Comment by Xorfee** [comment]
![2020-01-14 09 48 47](https://user-images.githubusercontent.com/58124296/72328368-148c3400-36b3-11ea-9596-f605b14036c6.jpg)
![2020-01-14 09 49 00](https://user-images.githubusercontent.com/58124296/72328386-1c4bd880-36b3-11ea-83f3-d5779200b7b1.jpg)

Yeah I did use the correct ip adress..
Which pin are u using in ur sketch to detect motion? 

I have 5v connected to the 5v port of wemos ground to ground and the middle connector connected to d1

**Comment by mariusmotea** [comment]
Please note that your circuit is not energy efficient and may empty the batteries soner than expected. To test the sketch please disconnect the pir and usin a wire touch shortly the GND to RST pin of the Wemod board. If you see requests in debug output then is the wemos work as expected. Next you need to simulate this action from the PIR, but as the pir output 3.3V during detection while you need GND pulse, the signal inversion is required. For this you can use any NPN transistor.

Example: https://i.stack.imgur.com/KntFP.jpg

**Comment by alexyao2015** [comment]
Since there has been no reply, I will be closing this issue.
