### ISSUE TITLE
Schedules with 'transitiontime' don't survive service restart

### ISSUE THREAD

**Issue by PiMaker** [diyhue/diyHue#346]
**Describe the bug**
Using latest diyhue and "Hue Essentials" Android App, schedules with "transitiontime" do not survive a restart of diyHue. After restarting the service they show up as "Unknown" in Hue Essentials, with their "full name" showing (e.g. SOn_2_rulename_OfCMh, etc...). They also don't work anymore.

To fix, either delete the rule and create it new, or just create a new one and magically have the old one appear correctly again as well - though now you have it twice, of course, so you have to delete one anyway.

**To Reproduce**
1. Create a schedule with transitiontime, i.e. in Hue Essentials, create a schedule for a room, set "repeat" to at least one day of the week, enter a time and select "Fade time" to be non-zero
2. Restart diyhue
3. Error appears. If you have multiple such schedules, all of them will be broken. Schedules without transition times work just fine.

**Expected behavior**
Not this :) Schedules should survive service restarts without changing behaviour/breaking.

**Logs**
Here are logs from startup in debug mode, nothing out of the ordinary AFAICT:
```
2020-02-26 21:24:17,526 - root - INFO - Using Host 10.0.5.2:80
2020-02-26 21:24:17,774 - root - INFO - b827eb30f4c3
2020-02-26 21:24:17,782 - root - INFO - IP range for light discovery: 0-255
2020-02-26 21:24:17,791 - root - INFO - 127.0.0.1
2020-02-26 21:24:17,796 - root - INFO - Online Discovery/Remote API Enabled!
2020-02-26 21:24:17,852 - root - INFO - Config loaded
2020-02-26 21:24:17,989 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:8080
2020-02-26 21:24:18,034 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "GET /api/283145a4e198cc6535/config HTTP/1.1" 200 1906
2020-02-26 21:24:18,134 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:8080
2020-02-26 21:24:18,182 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "GET /api/283145a4e198cc6535/lights HTTP/1.1" 200 2022
2020-02-26 21:24:18,258 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:8080
2020-02-26 21:24:18,288 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "GET /api/283145a4e198cc6535/sensors HTTP/1.1" 200 2200
2020-02-26 21:24:18,307 - root - INFO - Starting deconz websocket
2020-02-26 21:24:18,338 - root - DEBUG - starting ssdp...
2020-02-26 21:24:18,354 - root - DEBUG - start ssdp broadcast
2020-02-26 21:24:18,433 - root - INFO - sync with lights
2020-02-26 21:24:18,503 - root - INFO - Starting httpd...
2020-02-26 21:24:18,634 - root - INFO - Starting ssl httpd...
2020-02-26 21:24:18,785 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1177, in daylightSensor
    from astral import Astral, Location
ImportError: cannot import name 'Astral' from 'astral' (/usr/local/lib/python3.7/dist-packages/astral-2.1-py3.7.egg/astral/__init__.py)
```

The Astral error always happens, but I think since I'm not using the Daylight Sensor this is fine? No idea why though, used the install script directly.

**Additional context**
Latest diyhue (just upgraded with `check_updates.sh`) running on a Pi Zero.

config.json contains the following for one of my "broken" schedules:
```
    "schedules": {
        "3": {
            "command": {
                "address": "/api/hueess92203d11ea938cb827eb30f4c3/groups/2/action",
                "body": {
                    "scene": "12",
                    "transitiontime": 9000
                },              
                "method": "PUT"
            },
            "created": "2020-02-26T20:22:25",
            "description": "2",
            "localtime": "W120/T07:25:00",
            "name": "SOn_2_morning_OfCMh",
            "recycle": false,      
            "status": "enabled",    
            "time": "W120/T07:25:00"
        }
    },

```
Keep in mind that this does not change during restart, it's created, works, and after a reboot it doesn't anymore, but the config stays the same throughout.

**Comment by mariusmotea** [comment]
Hi,

What OS/board you are using?

**Comment by PiMaker** [comment]
Raspberry Pi Zero with latest Raspbian (upgraded with 'apt dist-upgrade' before testing)

**Comment by mariusmotea** [comment]
I will start to work on astral bug. It seams Astral library was refactored and version 2 changelog have following statement:

> This is a code refactor as well as an update so it is highly likely that you will need to adapt your code to suit.

I will work on this problem because it affect all the users then i will look for scene issue. I can tell you that i have not implemented scene with transitiontime specified in same  http PUT request.
