### ISSUE TITLE
Can not start Entertainment area sync.

### ISSUE THREAD

**Issue by jaagupku** [diyhue/diyHue#457]
**Describe the bug:**
Can not start entertainment sync from any app after I updated 6 week old docker image to latest.

I am running diyHue on Docker in Raspberry Pi 4.

I guess logs explain the best:
```
----------------------------------------
192.168.1.136 - - [10/Sep/2020 22:32:52] "PUT /api/d01fd788caa311ea8f63dca632408ee6/groups/2 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.136', 63770)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/opt/hue-emulator/HueEmulator3.py", line 1751, in do_PUT
    Popen(["/opt/hue-emulator/entertain-srv", "server_port=2100", "dtls=1", "psk_list=" + url_pices[2] + ",321c0c2ebfa7361e55491095b2f5f9db"])
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/hue-emulator/entertain-srv': '/opt/hue-emulator/entertain-srv'
----------------------------------------
192.168.1.140 - - [10/Sep/2020 22:32:53] "GET /api/cc74ee543af011ea9de9dca632408ee6/groups HTTP/1.1" 200 -
```

When i `docker exec -it diyHue bash`, then I can't even run entertain-srv from bash.

```
pi@raspberrypi:~ $ docker exec -it diyHue bash
root@raspberrypi:/opt/hue-emulator# /opt/hue-emulator/entertain-srv
bash: /opt/hue-emulator/entertain-srv: No such file or directory
```

The binary is there.

```
root@raspberrypi:/opt/hue-emulator# ls -l | grep entertain-srv
-rwxr-xr-x 1 root root 500384 Aug 24 01:15 entertain-srv
```

**Comment by alexyao2015** [comment]
Perhaps this is an issue with docker pulling the wrong architecture
Try running `diyhue/core:latest@sha256:119d587e0f1003bff4d75742a1b29ce3f4deb5f31f8d7a3ddc3c0c36b268901c`

**Comment by jaagupku** [comment]
Ok that was the case. Problem solved.
