### ISSUE TITLE
Routines not working correctly

### ISSUE THREAD

**Issue by WanderingStark** [diyhue/diyHue#465]
**Describe the bug**
Routines do not run at time they are set to run at. This is using the official Hue app and third party apps. 

**To Reproduce**
1. Go to routines
2. Set a routine
3. Wait for time routine is set for

**Expected behavior**
Routine runs at correct time

**Logs**

```
2020-09-24` 15:48:50,161 - __main__ - INFO - execute schedule: 2 withe delay 0
2020-09-24 15:48:50,173 - WebServer - DEBUG - 127.0.0.1 - "PUT /api/hueessb4fdc411eaa945b827ebe04bd2/groups/1/action HTTP/1.1" 200 -
2020-09-24 15:48:50,174 - webServer.server - INFO - in PUT method
2020-09-24 15:48:50,174 - webServer.server - INFO - /api/hueessb4fdc411eaa945b827ebe04bd2/groups/1/action
2020-09-24 15:48:50,175 - webServer.server - INFO - b'{"scene": "15"}'
2020-09-24 15:48:50,177 - protocols.esphome - DEBUG - ESPHome: <set_light> invoked! IP=192.168.0.102
2020-09-24 15:48:50,179 - protocols.esphome - DEBUG - LCT015
2020-09-24 15:48:50,180 - protocols.esphome - DEBUG - {'on': True}
2020-09-24 15:48:50,494 - webServer.server - INFO - [
    {
        "success": {
            "/groups/1/action/scene": "15"
        }
    }
]
2020-09-24 15:48:51,268 - WebServer - DEBUG - 192.168.0.13 - "DELETE /api/hueessb4fdc411eaa945b827ebe04bd2/schedules/2 HTTP/1.1" 200 -
2020-09-24 15:48:51,269 - webServer.server - INFO - [{"success":"/schedules/2 deleted."}]
2020-09-24 15:48:51,299 - WebServer - DEBUG - 192.168.0.13 - "GET /api/hueessb4fdc411eaa945b827ebe04bd2/scenes/3 HTTP/1.1" 200 -
2020-09-24 15:48:51,381 - WebServer - DEBUG - 192.168.0.13 - "POST /api/hueessb4fdc411eaa945b827ebe04bd2/schedules HTTP/1.1" 200 -
2020-09-24 15:48:51,382 - webServer.server - INFO - in post method
2020-09-24 15:48:51,382 - webServer.server - INFO - /api/hueessb4fdc411eaa945b827ebe04bd2/schedules
2020-09-24 15:48:51,383 - webServer.server - INFO - b'{"name":"SOn_1_Schedule 1_CKSmD","description":"1","localtime":"2020-09-24T16:50:00","command":{"address":"/api/hueessb4fdc411eaa945b827ebe04bd2/groups/1/action","method":"PUT","body":{"scene":"3"}},"status":"enabled","autodelete":false,"recycle":false}'
2020-09-24 15:48:51,384 - webServer.server - INFO - [
    {
        "success": {
            "id": "2"
        }
    }
]
2020-09-24 15:48:52,310 - functions.lightRequest - INFO - sync with lights
2020-09-24 15:48:52,713 - WebServer - DEBUG - 192.168.0.13 - "GET /api/hueessb4fdc411eaa945b827ebe04bd2 HTTP/1.1" 200 -
2020-09-24 15:48:53,403 - protocols.esphome - DEBUG - ESPHome: <get_light_state> invoked!
{"ok"}
{"ok"}
{"ok"}
{"ok"}
----------------------------------------
Exception happened during processing of request from ('192.168.0.13', 37890)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
2020-09-24 15:54:04,593 - functions.lightRequest - INFO - sync with lights
2020-09-24 15:54:05,820 - protocols.esphome - DEBUG - ESPHome: <get_light_state> invoked!
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
2020-09-24 15:59:17,031 - functions.lightRequest - INFO - sync with lights
2020-09-24 15:59:18,147 - protocols.esphome - DEBUG - ESPHome: <get_light_state> invoked!
2020-09-24 15:59:40,434 - WebServer - DEBUG - 192.168.0.13 - "GET /api/hueessb4fdc411eaa945b827ebe04bd2 HTTP/1.1" 200 -
2020-09-24 15:59:41,745 - functions.lightRequest - INFO - sync with lights
2020-09-24 15:59:43,007 - protocols.esphome - DEBUG - ESPHome: <get_light_state> invoked!
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
```

**Docker Info (please complete the following information):**
 - Architecture: ARM
 - Docker image version: master-refactor
 - Hardware: RP3

**Additional context**
2 Yeelight 1s bulbs and one bulb flashed with ESPHome

**Comment by alexyao2015** [comment]
Dupe #216
