### ISSUE TITLE
Adding DIY WS2812 fails

### ISSUE THREAD

**Issue by BPHvZ** [diyhue/diyHue#519]
**Describe the bug**

Adding a DIY WS2812b led strip light using the provided sketch from diyhue/lights repo, fails.
The lights can be found and are added to the Hue app. However, they are not controllable separately, only as a group/zone.
The docker image shows some errors after finding and adding the lights.

**Steps to Reproduce**

1. Search for lights in the Hue app.
2. The lights are found, but can not be controlled individually. They also report "unavailable" in the app.

**Expected behavior**

Each light should be controllable separately.

**Logs**

```
2020-12-07 21:36:06,524 - protocols.native.discover - INFO - {,
    "lights": 4,,
    "mac": "2C:F4:32:4A:08:29",,
    "modelid": "LST002",,
    "name": "Hue WS2812 strip",,
    "protocol": "native_multi",,
    "type": "ws2812_strip",,
    "version": 3.1,
},
2020-12-07 21:36:06,525 - protocols.native.discover - INFO - 192.168.178.231:80 is Hue WS2812 strip,
2020-12-07 21:36:06,525 - protocols.native.discover - INFO - Add new light: Hue WS2812 strip,
2020-12-07 21:36:08,848 - webServer.server - INFO - in PUT method,
2020-12-07 21:36:08,849 - webServer.server - INFO - /api/6b74f3ec38d311eb8b2cb827ebaeb239/groups/0,
2020-12-07 21:36:08,849 - webServer.server - INFO - b'{"name":"","lights":["7","3","8","4","5","1","6","2"],"class":"none"}',
----------------------------------------,
Exception occurred during processing of request from ('192.168.178.249', 55419),
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/socketserver.py", line 650, in process_request_thread,
    self.finish_request(request, client_address),
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request,
    self.RequestHandlerClass(request, client_address, self),
  File "/usr/local/lib/python3.9/socketserver.py", line 720, in __init__,
    self.handle(),
  File "/usr/local/lib/python3.9/http/server.py", line 429, in handle,
    self.handle_one_request(),
  File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request,
    method(),
  File "/diyhue/webServer/server.py", line 778, in do_PUT,
    bridge_config[url_pieces[3]][url_pieces[4]].update(put_dictionary),
KeyError: '0',
----------------------------------------,
2020-12-07 21:36:08,879 - webServer.server - INFO - in PUT method,
2020-12-07 21:36:08,879 - webServer.server - INFO - /api/6b74f3ec38d311eb8b2cb827ebaeb239/groups/0,
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): armv7l
 - Docker image version (Ex: latest, arm-05f043b, 128): armv7-experimental, digest: c185d099d861
 - OS (Ex: Windows 10, Ubuntu Buster): Raspbian GNU/Linux 10 (buster)
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry Pi 3 Model B Plus Rev 1.3

**Checklist**
- [X] I confirm that this is a bug report
- [X] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
@alexyao2015 Please check the code, it is webServer related

**Comment by BPHvZ** [comment]
The above log might be irrelevant because the error comes from a different IP
`request from ('192.168.178.249', 55419)`. The led strip uses 192.168.178.231.
The main problem is that the lights (I use light count 4) of the led strip are not available individually, but grouped together the light of the whole strip can be controlled. It is also not possible to create an entertainment room because the lights can not be controlled separately.

**Comment by mariusmotea** [comment]
The log is very useful. It show the code expect group 0 to be a key present in the config, but this is a virtual group that apply the actions to all groups.

**Comment by Tam-Koowan** [comment]
Bonjour, j'ai également le même problème avec mes bandes de LED WS2812B, l'application Hue Essential m'ajoute mes LED mais je ne peux pas les contrôler ni dans l'application Hue Essential ou du le pont Raspberry DiyHue.
Par contre mes Hue officiel fonctionne parfaitement. 
Je ne sais pas quoi faire, j'ai ce problème suite à la réinstallation du pont DiyHue qui qui ne fonctionnait plus.
merci à vous de votre aide

**Comment by mariusmotea** [comment]
les journaux de l'émulateur sont requis pendant le contrôle des bandes LED

**Comment by Tam-Koowan** [comment]
Je n'ai jamais eu a faire ça avant. Comment on fait ?
