### ISSUE TITLE
Home Assistant - Lights detected, but not visible in Hue Essentials

### ISSUE THREAD

**Issue by larsf96** [diyhue/diyHue#562]
**Describe the bug**

I've configured the home assistant integration within diyHue. The connection gets established and the lights are also being detected as far as I can see in the logs. But when I now connect the Hue Essentials App, there are no lights visible there.
I've used the API debugger to check the "/lights" endpoint, it's also returning an empty array

**Steps to Reproduce**

1. Fresh installation of diyHue
2. Configure home assistant integration
3. Connect Hue Essentials

**Expected behavior**

As far as I have understood, the lights should be visible at least in the Hue Essentials App

**Logs**

```
2021-01-02 11:01:47,331 - root - INFO - IP range for light discovery: 0-255
2021-01-02 11:01:47,331 - root - INFO - 127.0.0.1
2021-01-02 11:01:47,331 - root - INFO - Online Discovery/Remote API Enabled!
2021-01-02 11:01:47,334 - root - INFO - Config loaded
cp: can't create '/config/diyhue/export/': Is a directory
2021-01-02 11:01:47,344 - root - WARNING - Home Assistant Web Socket Client disconnected trying to (re)connect
2021-01-02 11:01:47,351 - root - INFO - Home Assistant WebSocket Connection Opened
2021-01-02 11:01:47,352 - root - INFO - Home Assistant Web Socket Client connected
2021-01-02 11:01:47,353 - root - INFO - Home Assistant Web Socket Authorisation required
2021-01-02 11:01:47,354 - root - DEBUG - start ssdp broadcast
2021-01-02 11:01:47,355 - root - DEBUG - starting ssdp...
2021-01-02 11:01:47,356 - root - INFO - Home Assistant Web Socket Authorisation complete
2021-01-02 11:01:47,357 - root - INFO - sync with lights
2021-01-02 11:01:47,374 - root - INFO - Starting httpd...
2021-01-02 11:01:47,413 - root - INFO - Starting ssl httpd...
2021-01-02 11:01:47,449 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2021-01-02 11:01:47,514 - root - INFO - Found light.flur_lights
2021-01-02 11:01:47,515 - root - INFO - Found light.kuche_light
2021-01-02 11:01:47,515 - root - INFO - Found light.decke_buro_light
2021-01-02 11:01:47,515 - root - INFO - Found light.schreibtisch_light
2021-01-02 11:01:47,516 - root - INFO - Found light.wohnzimmer_light
2021-01-02 11:01:47,516 - root - INFO - Found light.flur_light
2021-01-02 11:01:47,516 - root - INFO - Found light.flur2_light
2021-01-02 11:01:47,516 - root - INFO - Found light.arbeitsplatte_light
2021-01-02 11:01:47,516 - root - INFO - Found light.baum_buro_light
2021-01-02 11:01:47,517 - root - INFO - Found light.lampe_schreibtisch_light
2021-01-02 11:01:47,517 - root - INFO - Found light.ledstrip
2021-01-02 11:01:47,517 - root - INFO - Found light.first_led_hardware_instance
2021-01-02 11:01:47,621 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
192.168.0.61 - - [02/Jan/2021 11:01:47] "GET /description.xml HTTP/1.1" 200 -
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): ARM
 - Docker image version (Ex: latest, arm-05f043b, 128): latest dev
 - OS (Ex: Windows 10, Ubuntu Buster): Raspbian
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry Pi 3

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

FYI: I'm using the home assistant addon, which starts diyHue as a docker container. But as everything else is working, I guess that the problem is not located within the addon rather than in diyHue itself.

**Comment by mariusmotea** [comment]
Hi,

In your logs there is no request from Hue Essentials. Are you sure your phone was WiFi connected? Seams more a network related issue. Was diyhue ports 80 and 443 exposed?

**Comment by larsf96** [comment]
Hi,

I've catched the logs after a restart to get the output for the lights.
Here is a more recent log snippet:

```
2021-01-02 11:47:06,952 - root - INFO - sync with lights
2021-01-02 11:47:08,148 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2021-01-02 11:47:08,318 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2021-01-02 11:47:30,748 - root - DEBUG - Sending M-Search response to 192.168.0.28
2021-01-02 11:47:31,650 - root - DEBUG - Sending M-Search response to 192.168.0.28
2021-01-02 11:47:32,440 - root - DEBUG - Sending M-Search response to 192.168.0.28
2021-01-02 11:47:33,342 - root - DEBUG - Sending M-Search response to 192.168.0.28
2021-01-02 11:47:34,647 - root - DEBUG - Sending M-Search response to 192.168.0.28
2021-01-02 11:47:35,650 - root - DEBUG - Sending M-Search response to 192.168.0.28
2021-01-02 11:47:38,369 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2021-01-02 11:47:38,547 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
192.168.0.23 - - [02/Jan/2021 11:47:39] "GET /api/hueessb44c3911eba692dca63261de47 HTTP/1.1" 200 -
2021-01-02 11:47:40,997 - root - INFO - sync with lights
2021-01-02 11:47:44,758 - root - DEBUG - Sending M-Search response to 192.168.0.61
192.168.0.61 - - [02/Jan/2021 11:47:45] "GET /description.xml HTTP/1.1" 200 -
192.168.0.61 - - [02/Jan/2021 11:47:45] "GET /description.xml HTTP/1.1" 200 -
2021-01-02 11:47:45,460 - root - DEBUG - Sending M-Search response to 192.168.0.61
2021-01-02 11:47:46,459 - root - DEBUG - Sending M-Search response to 192.168.0.61
2021-01-02 11:47:47,560 - root - DEBUG - Sending M-Search response to 192.168.0.61
192.168.0.23 - - [02/Jan/2021 11:47:49] "GET /api/hueessb44c3911eba692dca63261de47 HTTP/1.1" 200 -
2021-01-02 11:47:52,581 - root - DEBUG - Sending M-Search response to 192.168.0.61
```

Port 80 & 443 are both exposed and accessible via browser

**Comment by mariusmotea** [comment]
What  Hue Essentials display, because it seams the pair process was successful. The user hash hueessb44c3911eba692dca63261de47 is related to Hue Essentials app.

**Comment by larsf96** [comment]
I can't provide a screenshot at the moment, but the app says that it's connected to the bridge an there is a room named "Philips hue" visible with no lights and nothing else is visible.
The resources tab of the bridge says "0 lights, 1 sensor" and everything else also 0

**Comment by mariusmotea** [comment]
I ask @foxy82, the plugin developer, maybe he can help.

**Comment by foxy82** [comment]
Hi @larsf96 can you go into the Bridges in Hue Essential go to Devices -> Hit "+" -> Select "Lights" -> Select the diyhue bridge and then select "search for lights". It will complete and say nothing has been found but you should then see the lights in Hue Essentials.

**Comment by larsf96** [comment]
hi @foxy82,

thanks for the hint, this worked for me! First I was getting some error messages from Hue essentials and also some errors from the diyHue logs below, but after a few moments the lights appeared. Thank you!

```
192.168.0.23 - - [02/Jan/2021 15:49:36] "POST /api/hueessb44c3911eba692dca63261de47/lights HTTP/1.1" 200 -
2021-01-02 15:49:36,077 - root - INFO - in post method
2021-01-02 15:49:36,077 - root - INFO - /api/hueessb44c3911eba692dca63261de47/lights
2021-01-02 15:49:36,078 - root - INFO - b'{}'
2021-01-02 15:49:36,080 - root - DEBUG - tasmota: <discover> invoked!
2021-01-02 15:49:36,082 - root - DEBUG - shelly: <discover> invoked!
2021-01-02 15:49:36,083 - root - INFO - HomeAssistant WebSocket discovery called
2021-01-02 15:49:36,092 - root - WARNING - Home Assistant Web Socket Client disconnected trying to (re)connect
2021-01-02 15:49:36,094 - root - DEBUG - ESPHome: <discover> invoked!
2021-01-02 15:49:36,106 - root - DEBUG - Hyperion: <discover> invoked!
2021-01-02 15:49:36,109 - root - DEBUG - wled discovery started
2021-01-02 15:49:36,116 - root - INFO - Home Assistant WebSocket Connection Opened
2021-01-02 15:49:36,119 - root - INFO - Home Assistant Web Socket Client connected
----------------------------------------
2021-01-02 15:49:36,120 - root - DEBUG - light id f785e9b0-193c-5cb9-ac2b-34ee6e456fec already exist, updating ip...
Exception happened during processing of request from ('192.168.0.23', 48100)
2021-01-02 15:49:36,135 - root - INFO - Home Assistant Web Socket Authorisation required
2021-01-02 15:49:36,136 - root - INFO - HomeAssistant WebSocket discovery waiting for devices
2021-01-02 15:49:36,141 - root - ERROR - Home Assistant Web Socket Authorisation invalid: {'type': 'auth_invalid', 'message': "Auth message incorrectly formatted: extra keys not allowed @ data['id']. Got 1\nnot a valid value for dictionary value @ data['type']. Got 'get_states'"}
2021-01-02 15:49:36,142 - ws4py - DEBUG - Closing message received (1000) 'b'''
2021-01-02 15:49:36,144 - root - INFO - Home Assistant WebSocket Connection Closed. Code: 1000 Reason b''
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 429, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/opt/hue-emulator/HueEmulator3.py", line 1654, in do_POST
    self._set_end_headers(bytes(json.dumps([{"success": {"/" + url_pices[3]: "Searching for new devices"}}],separators=(',', ':'),ensure_ascii=False), "utf8"))
  File "/opt/hue-emulator/HueEmulator3.py", line 1299, in _set_end_headers
    self.wfile.write(data)
  File "/usr/local/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
2021-01-02 15:49:36,180 - root - DEBUG - Sending M-Search response to 192.168.0.28
Assertion failed: htn.toclock_running == true (Target.cc: stopTimeOutClock: 503)
Assertion failed: htn.toclock_running == true (Target.cc: stopTimeOutClock: 503)
Aborted (core dumped)
Aborted (core dumped)
2021-01-02 15:49:37,582 - root - DEBUG - Sending M-Search response to 192.168.0.28
2021-01-02 15:49:39,085 - root - DEBUG - Yeelight search end
2021-01-02 15:49:39,956 - root - DEBUG - Hyperion search end
2021-01-02 15:49:40,588 - root - DEBUG - tasmota: probing ip 192.168.0.1
2021-01-02 15:49:40,593 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.0.1:80
2021-01-02 15:49:40,603 - urllib3.connectionpool - DEBUG - http://192.168.0.1:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 1705
2021-01-02 15:49:40,604 - root - DEBUG - tasmota: probing ip 192.168.0.39
2021-01-02 15:49:40,608 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.0.39:80
2021-01-02 15:49:40,615 - urllib3.connectionpool - DEBUG - http://192.168.0.39:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 447
2021-01-02 15:49:40,617 - root - DEBUG - tasmota: probing ip 192.168.0.28
2021-01-02 15:49:40,621 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.0.28:80
192.168.0.28 - - [02/Jan/2021 15:49:40] code 404, message not found
192.168.0.28 - - [02/Jan/2021 15:49:40] "GET /cm?cmnd=Status%200 HTTP/1.1" 404 -
2021-01-02 15:49:40,627 - urllib3.connectionpool - DEBUG - http://192.168.0.28:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 447
2021-01-02 15:49:41,167 - root - INFO - [
    "192.168.0.1:80",
    "192.168.0.38:80",
    "192.168.0.39:80"
]
2021-01-02 15:49:41,174 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.0.1:80
2021-01-02 15:49:41,186 - urllib3.connectionpool - DEBUG - http://192.168.0.1:80 "GET /detect HTTP/1.1" 404 1705
2021-01-02 15:49:41,192 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.0.38:80
192.168.0.38 - - [02/Jan/2021 15:49:41] code 404, message not found
192.168.0.38 - - [02/Jan/2021 15:49:41] "GET /detect HTTP/1.1" 404 -
2021-01-02 15:49:41,197 - urllib3.connectionpool - DEBUG - http://192.168.0.38:80 "GET /detect HTTP/1.1" 404 447
2021-01-02 15:49:41,203 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.0.39:80
2021-01-02 15:49:41,211 - urllib3.connectionpool - DEBUG - http://192.168.0.39:80 "GET /detect HTTP/1.1" 404 447
2021-01-02 15:49:41,216 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:8080
2021-01-02 15:49:41,218 - root - INFO - registration fail, is the link button pressed?
cp: can't create '/config/diyhue/export/': Is a directory
cp: can't create '/config/diyhue/export/': Is a directory
2021-01-02 15:49:45,653 - root - DEBUG - Sending M-Search response to 192.168.0.61
2021-01-02 15:49:46,657 - root - DEBUG - Sending M-Search response to 192.168.0.61
2021-01-02 15:49:47,460 - root - DEBUG - Sending M-Search response to 192.168.0.61
2021-01-02 15:49:48,866 - root - DEBUG - Sending M-Search response to 192.168.0.61
2021-01-02 15:49:51,863 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2021-01-02 15:49:51,896 - root - DEBUG - Hyperion search end
2021-01-02 15:49:52,024 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2021-01-02 15:49:53,050 - root - DEBUG - Sending M-Search response to 192.168.0.61
```

**Comment by foxy82** [comment]
Looks like your home assistant long lived access token is invalid.

**Comment by juanesf** [comment]
@larsf96 What kind of lights are you using?

**Comment by larsf96** [comment]
@juanesf I use some different lights, some are Hue and others are IKEA Tradfri, I use zigbee2mqtt to connect them to homeassistant
