### ISSUE TITLE
TV Ambilight : Only one Yeelight bulb works on all 4.

### ISSUE THREAD

**Issue by BenGost** [diyhue/diyHue#597]
**Describe the bug**

Bonjour,

J'ai configuré ma tv Phillips avec diyHue. 
Toutes les ampoules sont reconnues (4) (yeelight).
Mais uniquement une seule est synchronisée avec la TV.

Pouvez-vous m'aider ?

---------------------

Hello,
I configured my Philips TV with diyHue.
All bulbs are recognized (4) (yeelight).
But only one is synchronized with the TV.
Can you help me ?

Merci

**Steps to Reproduce**

Sur Phillips TV, activé Ambilight externe.
Ajouter la passerelle DiyHue,
Chaque ampoule se configure correctement.
Dès qu’on active l'ambilight, une seule lampe est synchronisée, les autres ne changent pas de couleur.
Sur l'application smartphonne, on voit bien les ampoules avec des couleurs.
Mais la seule ampoule qui se synchronise remonte en erreur.

------------------

On Phillips TV, activated External Ambilight.
Add the DiyHue gateway,
Each bulb is configured correctly.
As soon as you activate the ambilight, only one lamp is synchronized, the others do not change color.
On the smartphone application, we can clearly see the bulbs with colors.
But the only bulb that synchronizes goes wrong.

**Expected behavior**

**Logs**

```
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: ----------------------------------------
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: 192.168.1.166 - - [15/Mar/2021 17:58:25] "GET /api/e39d964085b711ebad6e000c29a11e17/groups/1 HTTP/1.1" 200 -
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: ----------------------------------------
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: Exception happened during processing of request from ('192.168.1.166', 41462)
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: Traceback (most recent call last):
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:   File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:     self.finish_request(request, client_address)
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:   File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:     self.RequestHandlerClass(request, client_address, self)
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:   File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:     self.handle()
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:   File "/usr/lib/python3.6/http/server.py", line 418, in handle
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:     self.handle_one_request()
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:   File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:     method()
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:   File "/opt/hue-emulator/HueEmulator3.py", line 1613, in do_GET
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]:     self._set_end_headers(bytes(json.dumps(bridge_config[url_pieces[3]][url_pieces[4]],separators=(',', ':'),ensure_ascii=False), "utf8
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: KeyError: '1'
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: ----------------------------------------
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: 192.168.1.166 - - [15/Mar/2021 17:58:25] "GET /api/e39d964085b711ebad6e000c29a11e17/groups/2 HTTP/1.1" 200 -
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: 192.168.1.166 - - [15/Mar/2021 17:58:25] "GET /api/e39d964085b711ebad6e000c29a11e17/groups/3 HTTP/1.1" 200 -
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: 192.168.1.166 - - [15/Mar/2021 17:58:25] "PUT /api/e39d964085b711ebad6e000c29a11e17/groups/3 HTTP/1.1" 200 -
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: 192.168.1.166 - - [15/Mar/2021 17:58:25] "PUT /api/e39d964085b711ebad6e000c29a11e17/lights/3/state HTTP/1.1" 200 -
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: 192.168.1.166 - - [15/Mar/2021 17:58:25] "GET /api/e39d964085b711ebad6e000c29a11e17/capabilities HTTP/1.1" 200 -
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: 192.168.1.166 - - [15/Mar/2021 17:58:25] "PUT /api/e39d964085b711ebad6e000c29a11e17/groups/3 HTTP/1.1" 200 -
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: 192.168.1.166 - - [15/Mar/2021 17:58:29] "GET /api/e39d964085b711ebad6e000c29a11e17/lights/1 HTTP/1.1" 200 -
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: 192.168.1.162 - - [15/Mar/2021 17:58:29] "GET /api/16c3209285b511ebad6e000c29a11e17/ HTTP/1.1" 200 -
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: 192.168.1.162 - - [15/Mar/2021 17:58:29] "PUT /api/16c3209285b511ebad6e000c29a11e17/groups/3/action HTTP/1.1" 200 -
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: 192.168.1.166 - - [15/Mar/2021 17:58:32] "GET /api/e39d964085b711ebad6e000c29a11e17/lights/1 HTTP/1.1" 200 -
Mar 15 17:58:32 vmlinux HueEmulator3.py[1379]: WARNING:root:lampadaire is unreachable: invalid literal for int() with base 16: '  '
```

**Docker Info (please complete the following information):**
 - Architecture AMD64 & ARM 
 - Docker image version latest: 
 - OS Ubuntu and raspbian raspberry 1: 
 - Hardware (PC and Raspberry Pi 1): 

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

Toutes mes ampoules sont des yeelight.

Lampadaire c'est le nom de mon ampoule. C'est la seule qui suit l'ambilight tv.
Comme si cette erreur arrêter le script pour les autres ampoules.
Elles sont toutes détectables, j'arrive a les faires clignotés à partir de la tv.

Mais elles ne suivent pas les scènes?

--------------

All of my bulbs are yeelight.

"Lampadaire" is the name of my bulb. She's the only one that follows ambilight tv.
As if this error will stop the script for the other bulbs.
They are all detectable, I can have them flashed from the tv.

But they don't follow the scenes?

**Comment by BenGost** [comment]
J'ai refait un test, en ajoutant les ampoules manuellement
J'ai commencé avec l'id N3 au lieu de 1

Et ça fonctionne sans erreur. Je ne comprends pas ?

Voici mon nouveau fichier de configuration :

-------------------

I did a test again, adding the bulbs manually
I started with the id N3 instead of 1

And it works without error. I do not understand ?

Here is my new config file:

```
"lights": {
        "3": {
            "capabilities": {
                "certified": true,
                "control": {
                    "colorgamut": [
                        [
                            0.6915,
                            0.3083
                        ],
                        [
                            0.17,
                            0.7
                        ],
                        [
                            0.1532,
                            0.0475
                        ]
                    ],
                    "colorgamuttype": "C",
                    "ct": {
                        "max": 500,
                        "min": 153
                    },
                    "maxlumen": 800,
                    "mindimlevel": 1000
                },
                "streaming": {
                    "proxy": true,
                    "renderer": true
                }
            },
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": false,
                    "mode": "safety"
                }
            },
            "manufacturername": "Philips",
            "modelid": "LCT015",
            "name": "Bureau",
            "productname": "Hue color lamp",
            "state": {
                "alert": "select",
                "bri": 63,
                "colormode": "ct",
                "ct": 355,
                "effect": "none",
                "hue": 0,
                "mode": "homeautomation",
                "on": false,
                "reachable": true,
                "sat": 0,
                "transitiontime": 5,
                "xy": [
                    0.6844586861982147,
                    0.30472266727702757
                ]
            },
            "swversion": "1.46.13_r26312",
            "type": "Extended color light",
            "uniqueid": "4a:e0:ad:7f:cf:49-1"
        },
        "4": {
            "capabilities": {
                "certified": true,
                "control": {
                    "colorgamut": [
                        [
                            0.6915,
                            0.3083
                        ],
                        [
                            0.17,
                            0.7
                        ],
                        [
                            0.1532,
                            0.0475
                        ]
                    ],
                    "colorgamuttype": "C",
                    "ct": {
                        "max": 500,
                        "min": 153
                    },
                    "maxlumen": 800,
                    "mindimlevel": 1000
                },
                "streaming": {
                    "proxy": true,
                    "renderer": true
                }
            },
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": false,
                    "mode": "safety"
                }
            },
            "manufacturername": "Philips",
            "modelid": "LCT015",
            "name": "Cuisine",
            "productname": "Hue color lamp",
            "state": {
                "alert": "select",
                "bri": 152,
                "colormode": "ct",
                "ct": 399,
                "effect": "none",
                "hue": 0,
                "mode": "homeautomation",
                "on": false,
                "reachable": true,
                "sat": 0,
                "transitiontime": 5,
                "xy": [
                    0.2657511253528649,
                    0.27176317998016325
                ]
            },
            "swversion": "1.46.13_r26312",
            "type": "Extended color light",
            "uniqueid": "4a:e0:ad:7f:cf:71-1"
        },
        "5": {
            "capabilities": {
                "certified": true,
                "control": {
                    "colorgamut": [
                        [
                            0.6915,
                            0.3083
                        ],
                        [
                            0.17,
                            0.7
                        ],
                        [
                            0.1532,
                            0.0475
                        ]
                    ],
                    "colorgamuttype": "C",
                    "ct": {
                        "max": 500,
                        "min": 153
                    },
                    "maxlumen": 800,
                    "mindimlevel": 1000
                },
                "streaming": {
                    "proxy": true,
                    "renderer": true
                }
            },
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": false,
                    "mode": "safety"
                }
            },
            "manufacturername": "Philips",
            "modelid": "LCT015",
            "name": "lampadaire",
            "productname": "Hue color lamp",
            "state": {
                "alert": "select",
                "bri": 63,
                "colormode": "ct",
                "ct": 412,
                "effect": "none",
                "hue": 0,
                "mode": "homeautomation",
                "on": false,
                "reachable": true,
                "sat": 0,
                "transitiontime": 5,
                "xy": [
                    0.14162846892435976,
                    0.04269068722009299
                ]
            },
            "swversion": "1.46.13_r26312",
            "type": "Extended color light",
            "uniqueid": "4a:e0:ad:7f:cf:49-1"
        },
        "6": {
            "capabilities": {
                "certified": true,
                "control": {
                    "colorgamut": [
                        [
                            0.6915,
                            0.3083
                        ],
                        [
                            0.17,
                            0.7
                        ],
                        [
                            0.1532,
                            0.0475
                        ]
                    ],
                    "colorgamuttype": "C",
                    "ct": {
                        "max": 500,
                        "min": 153
                    },
                    "maxlumen": 800,
                    "mindimlevel": 1000
                },
                "streaming": {
                    "proxy": true,
                    "renderer": true
                }
            },
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": false,
                    "mode": "safety"
                }
            },
            "manufacturername": "Philips",
            "modelid": "LCT015",
            "name": "plafond",
            "productname": "Hue color lamp",
            "state": {
                "alert": "select",
                "bri": 205,
                "colormode": "ct",
                "ct": 421,
                "effect": "none",
                "hue": 0,
                "mode": "homeautomation",
                "on": false,
                "reachable": true,
                "sat": 0,
                "transitiontime": 5,
                "xy": [
                    0.2657511253528649,
                    0.27176317998016325
                ]
            },
            "swversion": "1.46.13_r26312",
            "type": "Extended color light",
            "uniqueid": "4a:e0:ad:7f:cf:96-1"
        }
    },
    "lights_address": {
        "3": {
            "backlight": false,
            "id": "0x0000000010f639c7",
            "ip": "192.168.1.185",
            "model": "color",
            "protocol": "yeelight"
        },
        "4": {
            "backlight": false,
            "id": "0x0000000007fd8e07",
            "ip": "192.168.1.157",
            "model": "color",
            "protocol": "yeelight"
        },
        "5": {
            "backlight": false,
            "id": "0x0000000010f64917",
            "ip": "192.168.1.163",
            "model": "color",
            "protocol": "yeelight"
        },
        "6": {
            "backlight": false,
            "id": "0x0000000007c2dfed",
            "ip": "192.168.1.199",
            "model": "color",
            "protocol": "yeelight"
        }
    },
```

**Comment by Mevel** [comment]
You manage to resolve the issue?

**Comment by vKnmnn** [comment]
I just wanna chime in and say, that i see the same error message on my bridge, and i have a few yeelights too.
I might investigate later.

**Comment by vKnmnn** [comment]
Today the bridge became unresponsive after setting up ambilight+Hue with said error in the logs.
Restarting the app resulted in a corrupted config. This is really bad.

**Comment by BenGost** [comment]
Je voulais juste dire que le problème est revenu sans raison.
Je laisse tomber. Je pense que le problème se situe au niveau des ampoules.

-----

I just wanted to say that the problem returned for no reason.
I give up. I think the problem is with the bulbs.

**Comment by zewelor** [comment]
Just tried and also only single yeelight bulb works out of 3.

**Comment by mariusmotea** [comment]
@zewelor there will be a fix soon for this. Join Slack for discussions regarding this issue.
