### ISSUE TITLE
Hue App routines not firing

### ISSUE THREAD

**Issue by hackbaellchen** [diyhue/diyHue#613]
**Describe the issue**

Lately my routines are not executed anymore. All routines added in the official Philips Hue App (Android, 3.48.2 (7637)) are created properly, but aren't firing. This behaviour happens since 4-5 weeks ago, I don't recall exactly. I used the wakeup routine all the time since I had my diyHue instance. Suddenly (I think after an update of the docker image) they stopped working.

The other GitHub issues didn't apply to my problem, so I created this one. As no one else seems to have this problem, I think of this as a help request rather than a bug report.

**Steps you tried**

First I took a look to the commits made, but couldn't find anything that could have broken the routines. I tried to change all parameters of the wakeup routine and tried the Hue Essentials App (Android, 1.21.1), which also shows the routine correctly. I also tried to setup other routines in the official app - all with the same outcome. Then I added the DEBUG=true flag, to hopefully see some weird messages, but got just the standard messages that appear on changes in the app - no errors what whatsoever.
Everything else, like synchronization with the Windows Hue Sync, and other normal usage work flawlessly.
Finally I saved my config file externally and tried the same with a fresh installation, just to see still no change there.

**How we can help**

Please provide any new idea to make the routines working (again).

**Logs**

Here is the output when I add a routine with my smartphone:

```
diyhue  - - [05/May/2021 11:31:22] "GET /api/c831f8664ac911eb8d90dca6326c6e3f/ HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:22] "GET /api/45614a0aad8311ebb062dca6326c6e3f/capabilities HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:22] "POST /api/45614a0aad8311ebb062dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:22] "POST /api/45614a0aad8311ebb062dca6326c6e3f/scenes HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:22] "PUT /api/45614a0aad8311ebb062dca6326c6e3f/scenes/24/lightstates/4 HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:22] "POST /api/45614a0aad8311ebb062dca6326c6e3f/scenes HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:22] "GET /api/45614a0aad8311ebb062dca6326c6e3f/scenes/24 HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:22] "PUT /api/45614a0aad8311ebb062dca6326c6e3f/scenes/36/lightstates/4 HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:23] "POST /api/45614a0aad8311ebb062dca6326c6e3f/sensors HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:23] "POST /api/45614a0aad8311ebb062dca6326c6e3f/schedules HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:23] "POST /api/45614a0aad8311ebb062dca6326c6e3f/schedules HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:23] "POST /api/45614a0aad8311ebb062dca6326c6e3f/rules HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:23] "POST /api/45614a0aad8311ebb062dca6326c6e3f/rules HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:23] "POST /api/45614a0aad8311ebb062dca6326c6e3f/resourcelinks HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:23] "GET /api/45614a0aad8311ebb062dca6326c6e3f/scenes/36 HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:23] "GET /api/45614a0aad8311ebb062dca6326c6e3f HTTP/1.1" 200 -
hue app - - [05/May/2021 11:31:24] "GET /api/45614a0aad8311ebb062dca6326c6e3f/config HTTP/1.1" 200 -
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): aarch64
 - Docker image version (Ex: latest, arm-05f043b, 128): diyhue/core:latest
 - OS (Ex: Windows 10, Ubuntu Buster): Ubuntu 20.04.2
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry Pi 4

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

Here's how I start the docker container:
```
docker run -e "TZ=Europe/Berlin" -e "DEGUB=true" -d --name diyHue --restart=always --network=host -e MAC=mymac -v /mnt/hue-emulator/export:/opt/hue-emulator/export diyhue/core:latest
(using diyhue/core:latest with sha256:e6b2b9961558fd88ff7952b34bdcb86b53f2de23f22de9c84c2b7df22b54d54f)
```
I hope you have another idea how I can resolve this problem.
Thanks!

**Comment by mariusmotea** [comment]
The posted logs are not debug logs, i see only the http request with no body data. I think more important is to provide the `schedules` part from your config.json file.

**Comment by hackbaellchen** [comment]
I recreated a "clean" config.json and added a simple room with a wakeup routine. I think the sensors and rules could be helpful too, so I added them below.

<details>
<summary>schedules.json</summary>

```
"schedules": {
  "1": {
    "command": {
      "address": "/api/e01776eaae4711eb8fd8dca6326c6e3f/sensors/2/state",
      "body": {
        "flag": true
      },
      "method": "PUT"
    },
    "created": "2021-05-06T08:50:05",
    "description": "L_04_LEu6b_start wake up",
    "localtime": "W127/T08:30:00",
    "name": "Morgen",
    "recycle": true,
    "status": "enabled",
    "time": "W127/T08:30:00"
  },
  "2": {
    "autodelete": false,
    "command": {
      "address": "/api/e01776eaae4711eb8fd8dca6326c6e3f/groups/0/action",
      "body": {
        "scene": "13"
      },
      "method": "PUT"
    },
    "created": "2021-05-06T08:50:05",
    "description": "L_04_LEu6b_trigger end scene",
    "localtime": "PT00:01:00",
    "name": "L_04_LEu6b",
    "recycle": true,
    "starttime": "2021-05-06T08:50:05",
    "status": "disabled",
    "time": "PT00:01:00"
  }
},
```

</details>

<details>
<summary>sensors.json</summary>

```
"sensors": {
  "1": {
    "config": {
      "configured": false,
      "on": true,
      "sunriseoffset": 30,
      "sunsetoffset": -30
    },
    "manufacturername": "Philips",
    "modelid": "PHDL00",
    "name": "Daylight",
    "state": {
      "daylight": null,
      "lastupdated": "none"
    },
    "swversion": "1.0",
    "type": "Daylight"
  },
  "2": {
    "config": {
      "on": true
    },
    "manufacturername": "Philips",
    "modelid": "WAKEUP",
    "name": "Sensor for wakeup",
    "recycle": true,
    "state": {
      "flag": false,
      "lastupdated": "none"
    },
    "swversion": "A_1943185030",
    "type": "CLIPGenericFlag",
    "uniqueid": "L_04_LEu6b"
  }
}
```

</details>

<details>
<summary>rules.json</summary>

```
"rules": {
  "1": {
    "actions": [
      {
        "address": "/groups/1/action",
        "body": {
          "scene": "12"
        },
        "method": "PUT"
      },
      {
        "address": "/schedules/2",
        "body": {
          "status": "enabled"
        },
        "method": "PUT"
      }
    ],
    "conditions": [
      {
        "address": "/sensors/2/state/flag",
        "operator": "eq",
        "value": "true"
      }
    ],
    "created": "2021-05-06T08:50:05",
    "lasttriggered": "none",
    "name": "L_04_LEu6b_Start",
    "owner": "e01776eaae4711eb8fd8dca6326c6e3f",
    "recycle": true,
    "status": "enabled",
    "timestriggered": 0
  },
  "2": {
    "actions": [
      {
        "address": "/groups/2/action",
        "body": {
          "on": false
        },
        "method": "PUT"
      },
      {
        "address": "/sensors/2/state",
        "body": {
          "flag": false
        },
        "method": "PUT"
      }
    ],
    "conditions": [
      {
        "address": "/sensors/2/state/flag",
        "operator": "eq",
        "value": "true"
      },
      {
        "address": "/sensors/2/state/flag",
        "operator": "ddx",
        "value": "PT02:30:00"
      }
    ],
    "created": "2021-05-06T08:50:05",
    "lasttriggered": "none",
    "name": "Wake up 1.end",
    "owner": "e01776eaae4711eb8fd8dca6326c6e3f",
    "recycle": true,
    "status": "enabled",
    "timestriggered": 0
  }
},
```

</details>

**Comment by mariusmotea** [comment]
At first look it is correct. The schedule is at 08:30:00, but this only if the timezone is correlty set in the container. Can you set new routine in next 5 minutes and monitor the logs to paste them here?

**Comment by hackbaellchen** [comment]
I once again removed the "productive" config and copied my "clean" config.
After restarting (and pulling the new docker image), I deleted the Hue App cache and paired the app with the bridge via the webinterface (see the first few log entries). Then I deleted the previous not working routine and added one for 12:10 with 10 minutes wakeup time - i.e. the routine should start at 12:00. Additionally I added a turnoff at 14:10. I'm using the current time of Berlin, so subtract two hours to get the config time.
There are no logs after that except `{"ok"}`. Am I missing some log entries? The [documentation](https://diyhue.readthedocs.io/en/latest/AddFuncts/debug.html#docker-install) doesn't really say something about different outputs. The logs (`docker attach diyHue`) I get are from the beginning at until 12:03.
There's a `BrokenPipeError` at the beginning when I tried to pair my app. I don't think, that this caused any trouble, as the pairing and everything else worked flawlessly.

<details>
<summary>Logs</summary>

I replaced the ip adresses with the devices.

```
diyhue  - - [06/May/2021 11:53:12] "GET / HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:12] "GET /config.js HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:12] "GET /static/js/2.8a2060e0.chunk.js HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:12] "GET /static/js/main.f9be324d.chunk.js HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:12] "GET /static/css/2.675adcc2.chunk.css HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:12] "GET /favicon-16x16.png HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:12] "GET /apple-touch-icon.png HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('diyhue ', 52793)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/opt/hue-emulator/HueEmulator3.py", line 1326, in do_GET
    self._set_end_headers(f.read())
  File "/opt/hue-emulator/HueEmulator3.py", line 1295, in _set_end_headers
    self.wfile.write(data)
  File "/usr/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
{"ok"}
diyhue  - - [06/May/2021 11:53:13] "GET /api/e01776eaae4711eb8fd8dca6326c6e3f/groups HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:13] "GET /api/e01776eaae4711eb8fd8dca6326c6e3f/lights HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:14] "GET /api/e01776eaae4711eb8fd8dca6326c6e3f/groups HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:14] "GET /api/e01776eaae4711eb8fd8dca6326c6e3f/lights HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:15] "GET /api/e01776eaae4711eb8fd8dca6326c6e3f/groups HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:15] "GET /api/e01776eaae4711eb8fd8dca6326c6e3f/lights HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:16] "GET /api/e01776eaae4711eb8fd8dca6326c6e3f/groups HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:16] "GET /api/e01776eaae4711eb8fd8dca6326c6e3f/lights HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:16] "GET /hue/linkbutton HTTP/1.1" 401 -
hue app - - [06/May/2021 11:53:17] "GET /api/nouser/config HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:17] "GET /hue/linkbutton HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:17] "GET /api/e01776eaae4711eb8fd8dca6326c6e3f/lights HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:17] "GET /api/e01776eaae4711eb8fd8dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:17] "GET /api/nouser/config HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:17] "POST /api/ HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:18] code 404, message not found
diyhue  - - [06/May/2021 11:53:18] "GET /favicon.ico HTTP/1.1" 404 -
hue app - - [06/May/2021 11:53:18] "POST /api/ HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:19] "POST /api/ HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:20] "POST /api/ HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:21] "POST /api/ HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:22] "POST /api/ HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:23] "POST /api/ HTTP/1.1" 200 -
diyhue  - - [06/May/2021 11:53:24] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:24] "POST /api/ HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:24] "GET /api/e64ff970ae5011eb8687dca6326c6e3f HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/lights HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/11 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/12 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/13 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/1 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/2 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/3 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/4 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/5 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/6 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:25] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/7 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:26] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/8 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:26] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/9 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:26] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/10 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:26] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/sensors HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:26] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/config HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:27] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/lights HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:27] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:29] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/lights HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:29] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:31] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/lights HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:31] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:33] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/lights HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:33] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:34] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/lights HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:34] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:34] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/sensors HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:34] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/config HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:34] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/lights HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:34] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:35] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/lights HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:35] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:35] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:37] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/lights HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:37] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:37] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:37] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/sensors HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:38] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/config HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:38] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/config HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:40] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/config HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:41] "GET /api/e64ff970ae5011eb8687dca6326c6e3f HTTP/1.1" 200 -
{"ok"}
hue app - - [06/May/2021 11:53:46] "DELETE /api/e64ff970ae5011eb8687dca6326c6e3f/sensors/2 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:46] "DELETE /api/e64ff970ae5011eb8687dca6326c6e3f/rules/1 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:46] "DELETE /api/e64ff970ae5011eb8687dca6326c6e3f/rules/2 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:46] "GET /api/e64ff970ae5011eb8687dca6326c6e3f HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:46] "DELETE /api/e64ff970ae5011eb8687dca6326c6e3f/schedules/2 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:46] "DELETE /api/e64ff970ae5011eb8687dca6326c6e3f/groups/2 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:46] "DELETE /api/e64ff970ae5011eb8687dca6326c6e3f/schedules/1 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:46] "DELETE /api/e64ff970ae5011eb8687dca6326c6e3f/resourcelinks/1 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:46] "DELETE /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/12 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:46] "DELETE /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/13 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:53:50] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/config HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:00] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/config HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:10] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/config HTTP/1.1" 200 -
{"ok"}
hue app - - [06/May/2021 11:54:20] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/config HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:27] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/capabilities HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:27] "POST /api/e64ff970ae5011eb8687dca6326c6e3f/groups HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:27] "POST /api/e64ff970ae5011eb8687dca6326c6e3f/scenes HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:28] "POST /api/e64ff970ae5011eb8687dca6326c6e3f/scenes HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:28] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/12 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:28] "POST /api/e64ff970ae5011eb8687dca6326c6e3f/sensors HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:28] "POST /api/e64ff970ae5011eb8687dca6326c6e3f/schedules HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:28] "POST /api/e64ff970ae5011eb8687dca6326c6e3f/schedules HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:28] "POST /api/e64ff970ae5011eb8687dca6326c6e3f/rules HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:28] "POST /api/e64ff970ae5011eb8687dca6326c6e3f/rules HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:28] "POST /api/e64ff970ae5011eb8687dca6326c6e3f/resourcelinks HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:28] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/scenes/13 HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:28] "GET /api/e64ff970ae5011eb8687dca6326c6e3f HTTP/1.1" 200 -
hue app - - [06/May/2021 11:54:30] "GET /api/e64ff970ae5011eb8687dca6326c6e3f/config HTTP/1.1" 200 -
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
{"ok"}
```

</details>

**Comment by mariusmotea** [comment]
`{"ok"}` will be added every 30 seconds and it mean the bridge annouce the presence for HueEssentials detection, ignore this. Please check the hour in diyhue container with following command: 

`docker exec -it diyHue date`

**Comment by hackbaellchen** [comment]
Current output: `Thu May  6 14:47:22 CEST 2021` (equals my local time)

**Comment by mariusmotea** [comment]
Good, at the beginning or the container there is any error? I expect some errors in scheduler thread that kill the scheduler and not taks are executed anymore, while the bridge emulator continue to operate fine.

P.S. on Slack we can have a faster debugging session.

**Comment by hackbaellchen** [comment]
At least there's no error when loading an existing config file:

```
Host MAC given as mymac
Docker Setup Initiated
SSL certificate found
Config file found
Docker Setup Complete
```

**Comment by hackbaellchen** [comment]
Thanks!
Got it working by switching to the flask branch.
