### ISSUE TITLE
Ambilight+Hue isn't working 

### ISSUE THREAD

**Issue by op-avo** [diyhue/diyHue#667]
**Describe the issue**

After the proper installation of all diyhue components and the setup of Ambilight+Hue on the TV, no color information is transmitted to the lights. The colors don't change like Ambilight should.
In the past, Ambilight+Hue worked without changing the setup.
During the configuration process on the TV, the lights flash on and can be set up normally. After finishing the setup, nothing happens. The lights stay orange but go out when the TV is switched off.

**Steps you tried**

1. Multiple complete reinstallations (all work, only Ambilight+Hue not)
   - Docker host network mode
   - Docker bridge network mode
   - Automatic install: Master
   - Automatic install: Developer
   - Automatic install: Beta
2. Deleting and restarting the Raspberry Pi
3. Software version adjustment in config.json
4. Reset TV and set up Ambilight+Hue

**How we can help**

- Do you have any idea where the problem might be?
- Which installation method is the best to have the best possible success for Ambilight+Hue?
- Is it possibly due to an software update from the TV (PHILIPS 70PUS7805 / 12)?
- Does a router setting block the data exchange between the TV and the bridge?
- Can I make adjustments in config.json that make Ambilight+Hue work again?

Please tell me if more information is needed. I'm new to GitHub: D

**Logs**

Let me know if and which ones are needed.

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM):  ARMv6
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): Raspberry Pi OS (32-bit)
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry Pi Zero W V1.1

**Checklist**
- [x ] I confirm that this is a help request
- [x ] I confirm that I have completed this template to the best of my ability

**Additional context**

I've tried everything possible for my ability. Ambilight + Hue used to work. The Phillips Hue app (version 3.48.2) works without any problems, including Alexa control. I hope that a setting will activate the data transfer of the changing colors between the TV and the lights. It is inexplicable to me that the lights go out when the TV is switched off and it comes on again during the Ambilight + Hue setup process.

**Comment by mariusmotea** [comment]
Please use docker image of the beta branch and enable debug mode by setting `DEBUG=true` env variable. Show logs during the start of the TV streaming.

**Comment by op-avo** [comment]
Thank you for the fast answer! 

I tried to install the Docker image of the beta branch. The installation process went smoothly, but the container could not be started. 

`driver failed programming external connectivity on endpoint diyHue (...): Bind for 0.0.0.0:2100 failed: port is already allocated`

So I installed the developer branch and read out the log data, as you said. If it is important to use the beta branch, please give me a tip on how I can fix it.

Here are the log data of the developer branch image after I start the TV (192.168.178.74) and Ambilight + Hue should start. I have a total of 5 lights on 3 ESP8622. 

```
2021-07-27 22:35:45,611 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.91:80

2021-07-27 22:35:45,652 - urllib3.connectionpool - DEBUG - http://192.168.178.91:80 "GET /get?light=1 HTTP/1.1" 200 100

2021-07-27 22:35:46,124 - root - DEBUG - Sending M-Search response to 192.168.178.74

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /description.xml HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/lights/4 HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/lights/5 HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/lights/6 HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/lights/7 HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/lights/8 HTTP/1.1" 200 -

192.168.178.24 - - [27/Jul/2021 22:35:46] "GET /api/5fb95f22ef2411eb9eabb827ebe83514/lights HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/config HTTP/1.1" 200 -

192.168.178.24 - - [27/Jul/2021 22:35:46] "GET /api/5fb95f22ef2411eb9eabb827ebe83514/groups HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/groups HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/groups HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/capabilities HTTP/1.1" 200 -

2021-07-27 22:35:46,831 - root - DEBUG - Sending M-Search response to 192.168.178.74

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/groups/0 HTTP/1.1" 200 -

----------------------------------------

Exception happened during processing of request from ('192.168.178.74', 45770)

Traceback (most recent call last):

  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread

    self.finish_request(request, client_address)

  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request

    self.RequestHandlerClass(request, client_address, self)

  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__

    self.handle()

  File "/usr/lib/python3.7/http/server.py", line 426, in handle

    self.handle_one_request()

  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request

    method()

  File "/opt/hue-emulator/HueEmulator3.py", line 1597, in do_GET

    if bridge_config["groups"][group_state]["state"]["any_on"] == True:

KeyError: 'state'

----------------------------------------

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /description.xml HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/groups/1 HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/groups/2 HTTP/1.1" 200 -

192.168.178.74 - - [27/Jul/2021 22:35:46] "GET /api/c3595c7ceeec11ebb251b827ebe83514/groups/3 HTTP/1.1" 200 -
```

The following paragraph is repeated 60 times in a row, with an increasing number of KeyError (KeyError '3' - '63'):

```
----------------------------------------

Exception happened during processing of request from ('192.168.178.74', 45778)

Traceback (most recent call last):

  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread

    self.finish_request(request, client_address)

  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request

    self.RequestHandlerClass(request, client_address, self)

  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__

    self.handle()

  File "/usr/lib/python3.7/http/server.py", line 426, in handle

    self.handle_one_request()

  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request

    method()

  File "/opt/hue-emulator/HueEmulator3.py", line 1613, in do_GET

    self._set_end_headers(bytes(json.dumps(bridge_config[url_pieces[3]][url_pieces[4]],separators=(',', ':'),ensure_ascii=False), "utf8"))

KeyError: '3'

----------------------------------------
```

Is an error recognizable with the information? Otherwise I set up the Pi again and try to get the beta branch running.
