### ISSUE TITLE
Can't connect to HUE App in latest BETA

### ISSUE THREAD

**Issue by PDekker** [diyhue/diyHue#697]
**Describe the bug**
In the latest BETA and the latest HUE app (4.4.0) I can link the bridge, but after that, the app stay on the "connecting...." screen

Possibly recent 4.4 update?

**Steps to Reproduce**

**Expected behavior**
Connect to latest HUE app (and try dynamic scenes)

**Logs**

```
diyHue_test   | 10.0.0.152 - - [13/Sep/2021 12:04:54] "GET /clip/v2/resource/bridge HTTP/1.1" 200 -
diyHue_test   | 10.0.0.152 - - [13/Sep/2021 12:04:54] "GET /eventstream/clip/v2 HTTP/1.1" 200 -
diyHue_test   | [2021-09-13 12:04:55,025] ERROR in app: Exception on /clip/v2/resource [GET]
diyHue_test   | Traceback (most recent call last):
diyHue_test   |   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1950, in full_dispatch_request
diyHue_test   |     rv = self.dispatch_request()
diyHue_test   |   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1936, in dispatch_request
diyHue_test   |     return self.view_functions[rule.endpoint](**req.view_args)
diyHue_test   |   File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 468, in wrapper
diyHue_test   |     resp = resource(*args, **kwargs)
diyHue_test   |   File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 89, in view
diyHue_test   |     return self.dispatch_request(*args, **kwargs)
diyHue_test   |   File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 583, in dispatch_request
diyHue_test   |     resp = meth(*args, **kwargs)
diyHue_test   |   File "/opt/hue-emulator/flaskUI/v2restapi.py", line 223, in get
diyHue_test   |     data.append(group.getV2EntertainmentConfig())
diyHue_test   |   File "/opt/hue-emulator/HueObjects/__init__.py", line 625, in getV2EntertainmentConfig
diyHue_test   |     "x": gradienStripPositions[x][0] if gradientStrip else self.locations[light()][0],
diyHue_test   |   File "/usr/lib/python3.9/weakref.py", line 405, in __getitem__
diyHue_test   |     return self.data[ref(key)]
diyHue_test   | KeyError: <weakref at 0x75d26730; to 'Light' at 0x75d30088>
diyHue_test   | 10.0.0.152 - - [13/Sep/2021 12:04:55] "GET /clip/v2/resource HTTP/1.1" 500 -
diyHue_test   | 10.0.0.158 - - [13/Sep/2021 12:04:59] "GET /api/695f7e52e61511eb98640242ac120002/groups/0 HTTP/1.1" 200 -
diyHue_test   | 10.0.0.158 - - [13/Sep/2021 12:05:04] "GET /api/695f7e52e61511eb98640242ac120002/groups/0 HTTP/1.1" 200 -
```
**Docker Info (please complete the following information):**
 - Architecture (Raspberry PI, ARM)
 - Docker image version (beta:latest)
 - OS (Raspberry pi OS)
 - Hardware (Raspberry Pi 4)

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
There is an error with one light referenced in a group and the light don't exist. If you delete from groups.yaml the entertainment room it will work

**Comment by mariusmotea** [comment]
Thanks. Will do this right now.

**Comment by JG145** [comment]
HI, Sorry to clarify, Adding lights via WLED just act as a rgbw strip when using hue sync. Whereas I would expect it to act as a gradient strip. I am using the Beta branch and have used the WLED Bin file and the DIYhue Ws2812 sketch to flash a NodeMcu.
