### ISSUE TITLE
Exception connecting with philips hue app(3)

### ISSUE THREAD

**Issue by flash447** [diyhue/diyHue#718]
**Describe the bug**

(This is a copy of #713 since I don't have access to add comments to that issue)
Exception connecting with philips hue app

**Steps to Reproduce**

I have setup diyHue with the latest from the beta branch. Initially, I was able to connect with the Philips hue app and setup my lights and it seemed to work. But now when I connect, the hue app stalls and hue emulator generates the following exception over and over:

```
2021-10-24 08:50:29,328 - configManager.argumentHandler - INFO - Using Host 192.168.10.2:80
2021-10-24 08:50:29,349 - configManager.argumentHandler - INFO - Host MAC given as 00c0ba32d190
2021-10-24 08:50:29,349 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2021-10-24 08:50:29,350 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2021-10-24 08:50:29,350 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2021-10-24 08:50:29,354 - configManager.argumentHandler - INFO - Debug logging disabled!
2021-10-24 07:50:30,374 - configManager.configHandler - INFO - Config loaded
Starting remote discovery
2021-10-24 07:50:30,769 - services.stateFetch - INFO - start lights sync
2021-10-24 07:50:30,777 - services.ssdp - INFO - starting ssdp...
2021-10-24 07:50:30,779 - services.ssdp - INFO - start ssdp broadcast
2021-10-24 07:50:30,780 - services.mdns - INFO - <MDNS> listener started
 * Serving Flask app "HueEmulator3" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Serving Flask app "HueEmulator3" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
192.168.10.45 - - [24/Oct/2021 07:50:39] "GET /clip/v2/resource/bridge HTTP/1.1" 200 -
192.168.10.45 - - [24/Oct/2021 07:50:40] "GET /eventstream/clip/v2 HTTP/1.1" 200 -
[2021-10-24 07:50:40,760] ERROR in app: Exception on /clip/v2/resource [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/hue-emulator/flaskUI/v2restapi.py", line 210, in get
    data.append(light.getV2Api())
  File "/opt/hue-emulator/HueObjects/__init__.py", line 307, in getV2Api
    "mirek": self.state["ct"] if self.state["colormode"] == "ct" else None,
KeyError: 'colormode'

```
I have the following lights:
1x Ubisys Universal dimmer D1 (dimmable)
1x Philips LCT015 (RGB, dimmable)
6x Innr Adapter plug SP 120 (on/off switch, non-dimmable)

**Expected behavior**

Not crashing :)

**Logs**

None.

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - Docker image version (Ex: latest, arm-05f043b, 128): 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

Non docker installation. But I doubt my issue is related to this.

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

None.

**Comment by arehsan** [comment]
Hi,

I get the same error message with latest docker beta. Using zigbee2mqtt and several types of lights, LTW001, LWB010 and LST002. Hue app did work earlier, but is now unable to connect. If I reset the app (official hue app on iOS), the bridge is recognized and linked, but stuck on "connecting..."

**Comment by flash447** [comment]
I also still have the same issue running with the latest beta. In what commit id was it suppose to be fixed?

**Comment by mariusmotea** [comment]
Please paste here the error from the logs.

**Comment by flash447** [comment]
```

[2022-01-04 10:16:58,613] ERROR in app: Exception on /clip/v2/resource [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/hue-emulator/flaskUI/v2restapi.py", line 210, in get
    data.append(light.getV2Api())
  File "/opt/hue-emulator/HueObjects/__init__.py", line 307, in getV2Api
    "mirek": self.state["ct"] if self.state["colormode"] == "ct" else None,
KeyError: 'colormode'
```

**Comment by arehsan** [comment]
```
10.0.0.93 - - [04/Jan/2022 11:49:17] "GET /clip/v2/resource/bridge HTTP/1.1" 200 -
10.0.0.93 - - [04/Jan/2022 11:49:17] "GET /eventstream/clip/v2 HTTP/1.1" 200 -
[2022-01-04 11:49:17,128] ERROR in app: Exception on /clip/v2/resource [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/hue-emulator/flaskUI/v2restapi.py", line 224, in get
    data.append(light.getV2Api())
  File "/opt/hue-emulator/HueObjects/__init__.py", line 365, in getV2Api
    "mirek": self.state["ct"] if self.state["colormode"] == "ct" else None,
KeyError: 'colormode'
10.0.0.93 - - [04/Jan/2022 11:49:17] "GET /clip/v2/resource HTTP/1.1" 500 -
```

10.0.0.93 is my iPhone

**Comment by mariusmotea** [comment]
Ok, will made a new release to fix this error.
