### ISSUE TITLE
MQTT or HomeAssistant enabled, container into restart loop ([Errno 113] or [Errno 111])

### ISSUE THREAD

**Issue by JHurk** [diyhue/diyHue#721]
**Describe the issue**

When stopping the container, enabling mqtt in the config and restarting the container, it will not work anymore and restart itself constantly. (OSError: [Errno 113] No route to host)
Edit; just tried to enable HomeAssistant and this gave similar error (Errno 111 Connection Refused), but didn't make the container go into a boot loop.

**Steps you tried**

1. Installed in Docker on Synology
2. Because of trouble with port 80 not being free for DiyHue, I installed Portainer and made a macvlan (as found in the following tutorial, replaced 'pi-hole' with 'DiyHue'
3. Started the container with the following settings:
- always restart
- connection between /docker/diyhue/hue-emulator/export and /opt/hue-emulator/export
- Network DiyHue (macvlan I created with portainer)
- Environment Variables: IP = IP Address I assigned with portainer & MAC = MAC address of Ethernet port I assigned in portainer
4.  After starting the container (with MQTT disabled in config) I can reach the GUI with the assigned IP address (192.168.1.240:80) and I can activate DiyHue on my Hue App on my iPhone.
5. After stopping the container I edit the config file
6. I enable mqtt (enabled: true), I fill in the mqtt IP address (192.168.1.7) and keep the discoveryprefix, port, user and password like it is. I save the config.json file
7. Then I go to Zigbee2MQTT and enable the Home Assistant Integration
8. Then I start the container again (after resetting the settings)
9. The containers goes into a boot loop and in the log file I see the error OSError: [Errno 113] No route to host
10. When I stop the container and disable mqtt in the config, restart the container again, it work again.

The mqtt settings are triple checked (mqtt ip is 192.168.1.7, but also tried localhost and 127.0.0.1 but because of portainer making a new network I assume DiyHue is on a different network/machine so therefor localhost and 127.0.0.1 was expected not to work). Other mqtt settings are default port 1883 and no user and no password.

**How we can help**

Do not know if this is a bug or not, because DiyHue starts and only stops working when I enable mqtt. So it might be a 'network' issue also because of the workaround with port 80 through portainer.

**Logs**

The log is sorted by newest log entry first!
Edit; Log of MQTT enabled
```
2021-10-30 18:30:05	stdout	OSError: [Errno 113] No route to host
2021-10-30 18:30:05	stdout	    sock.connect(sa)
2021-10-30 18:30:05	stdout	  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
2021-10-30 18:30:05	stdout	    raise err
2021-10-30 18:30:05	stdout	  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
2021-10-30 18:30:05	stdout	    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
2021-10-30 18:30:05	stdout	  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
2021-10-30 18:30:05	stdout	    sock = self._create_socket_connection()
2021-10-30 18:30:05	stdout	  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
2021-10-30 18:30:05	stdout	    return self.reconnect()
2021-10-30 18:30:05	stdout	  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 937, in connect
2021-10-30 18:30:05	stdout	    client.connect(config["mqttServer"], config["mqttPort"])
2021-10-30 18:30:05	stdout	  File "/opt/hue-emulator/protocols/mqtt.py", line 246, in mqttServer
2021-10-30 18:30:05	stdout	    mqtt.mqttServer(bridge_config["emulator"]["mqtt"], bridge_config["lights"], bridge_config["lights_address"], bridge_config["sensors"])
2021-10-30 18:30:05	stdout	  File "/opt/hue-emulator/HueEmulator3.py", line 2000, in <module>
2021-10-30 18:30:05	stdout	Traceback (most recent call last):
2021-10-30 18:30:02	stdout	2021-10-30 20:30:02,183 - root - INFO - Config loaded
2021-10-30 18:30:02	stdout	2021-10-30 20:30:02,182 - root - INFO - Online Discovery/Remote API Enabled!
2021-10-30 18:30:02	stdout	2021-10-30 20:30:02,181 - root - INFO - 127.0.0.1
2021-10-30 18:30:02	stdout	2021-10-30 20:30:02,181 - root - INFO - IP range for light discovery: 0-255
2021-10-30 18:30:02	stdout	Docker Setup Complete
2021-10-30 18:30:02	stdout	Config file found
2021-10-30 18:30:02	stdout	SSL certificate found
2021-10-30 18:30:02	stdout	Docker Setup Initiated
2021-10-30 18:30:02	stdout	2021-10-30 20:30:02,180 - root - INFO - 00113247B8E7
2021-10-30 18:30:02	stdout	Host MAC given as 00113247B8E7
2021-10-30 18:30:02	stdout	2021-10-30 20:30:02,179 - root - INFO - Using Host 192.168.1.240:80
```
Edit; Log of HomeAssistant enabled:
```
2021-10-30 19:16:28	stdout	192.168.1.226 - - [30/Oct/2021 19:16:28] "GET /api/4fc384cc399c11ec9a770242c0a801f0/groups HTTP/1.1" 200 -
2021-10-30 19:16:09	stdout	{"ok"}
2021-10-30 19:16:09	stdout	192.168.1.29 - - [30/Oct/2021 19:16:09] "GET /description.xml HTTP/1.1" 200 -
2021-10-30 19:16:09	stdout	ConnectionRefusedError: [Errno 111] Connection refused
2021-10-30 19:16:09	stdout	    self.sock.connect(self.bind_addr)
2021-10-30 19:16:09	stdout	  File "/usr/local/lib/python3.7/dist-packages/ws4py/client/__init__.py", line 217, in connect
2021-10-30 19:16:09	stdout	    homeassistant_ws_client.connect()
2021-10-30 19:16:09	stdout	  File "/opt/hue-emulator/protocols/homeassistant_ws.py", line 224, in create_websocket_client
2021-10-30 19:16:09	stdout	Traceback (most recent call last):
2021-10-30 19:16:09	stdout	ERROR:root:Error connecting to Home Assistant WebSocket
2021-10-30 19:16:09	stdout	WARNING:root:Home Assistant Web Socket Client disconnected trying to (re)connect
2021-10-30 19:16:09	stdout	Docker Setup Complete
2021-10-30 19:16:09	stdout	Config file found
2021-10-30 19:16:09	stdout	SSL certificate found
2021-10-30 19:16:09	stdout	Docker Setup Initiated
2021-10-30 19:16:09	stdout	Host MAC given as 00113247B8E7
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): Synology DS415+ (Avanton)
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): DSM 6.2
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Synology DS415+

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

When I change the mqtt address from the IP address 192.168.1.7 to 127.0.0.1 the error changes from 113 No route to host, to ConnectionRefusedError: [Errno 111] Connection refused

**Comment by mariusmotea** [comment]
This don't seams to be an issue with this project. It is related to how Docker networking is working on Synology. You need to find a way to provide network access to these services.

**Comment by JHurk** [comment]
Did some more research and the devices got discovered. I put the MACVLAN ip-addresss of the NAS in the config file of DiyHue instead of the 'normal' ip address'. So the ip I made in the last step of this tutorial (replace pi-hole with DiyHue)
https://servicemax.com.au/tips/pi-hole-in-docker-on-synology-the-best-way/

So then the mqtt lights where exposed in DiyHue, and after some research I was able to get the Hue Essentials app to find the lights. But then the new challenge started; lights were going on and off all together and no colour changing was possible. So I stopped with that and de-activated DiyHue. Maybe in the future I will try again, but for now I will stick with Domoticz, Zigbee2MQTT and Homebridge setup, which works great but wanted a nice 'lights color and scene app'.

**Comment by mariusmotea** [comment]
Interesting behavior you described. With debug logs probably there was something interesting there. In most of the cases a docker restart fix the problem with all lights control in the same time.

**Comment by JHurk** [comment]
I tried it again and after restarting DiyHue the issue with 'all lights going on and off' was gone.

But now when I try to save a 'scene/effect' on the bridge, via the Hue Essentials-app, I get an error that there is no connection between app (Hue Essentials) and bridge (DiyHue). 
Strange thing is that I am able to control lights with the app. And lights I have not controlled with the app all have the status 'unreachable'. As soon as I click them the connection is established.
So restarting did get rid of the 'all lights on and off' problem, but created a new problem.

**Comment by mariusmotea** [comment]
Ok, i will take a look.
