### ISSUE TITLE
Amazon Alexa won't discover diyhue hub

### ISSUE THREAD

**Issue by gammeflamme** [diyhue/diyHue#75]
**Describe the bug**
Amazon Alexa won't discover diy hue hub

**To Reproduce**

1. open devices in the amazon alexa app
2. press "add device"
3. select other
4. press "activate" in Hue LinkButton web interface
5. press "Discover devices" in amazon alexa

**Expected behavior**

Amazon alexa discovers the diyue hub

**Logs**
not sure if this is of any use
```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "HueEmulator3.py", line 139, in entertainmentService
    serverSocket.bind(('127.0.0.1', 2101))
OSError: [Errno 98] Address already in use

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "HueEmulator3.py", line 1732, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "HueEmulator3.py", line 1745, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by gammeflamme** [comment]
I don't get an output from that command

**Comment by gammeflamme** [comment]
netstat -tulpn
```
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
udp        0      0 0.0.0.0:44391           0.0.0.0:*                           -
udp   165120      0 0.0.0.0:1900            0.0.0.0:*                           -
udp   166272      0 0.0.0.0:1900            0.0.0.0:*                           12345/python3
udp   132096      0 0.0.0.0:1900            0.0.0.0:*                           9073/python3
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           -
udp        0      0 0.0.0.0:55162           0.0.0.0:*                           -
udp        0      0 0.0.0.0:45610           0.0.0.0:*                           12345/python3
udp        0      0 10.55.68.140:2100       0.0.0.0:*                           -
udp        0      0 127.0.0.1:2101          0.0.0.0:*                           -
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -
udp        0      0 0.0.0.0:56597           0.0.0.0:*                           9073/python3
udp        0      0 0.0.0.0:53014           0.0.0.0:*                           -
udp        0      0 0.0.0.0:34622           0.0.0.0:*                           -
udp        0      0 0.0.0.0:45389           0.0.0.0:*                           -
udp6       0      0 :::37275                :::*                                -
udp6       0      0 :::546                  :::*                                -
udp6       0      0 :::5353                 :::*                                -
```

the program using port 2101 is unknown

**Comment by mariusmotea** [comment]
I believe he don't stop the hue-emulator service first.

**Comment by gammeflamme** [comment]
yeha that was the problem. but alexa still wont connect 
```
10.55.68.108 - - [26/Jan/2019 21:04:23] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
10.55.68.108 - - [26/Jan/2019 21:04:38] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
10.55.68.108 - - [26/Jan/2019 21:04:46] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
10.55.68.108 - - [26/Jan/2019 21:04:51] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
10.55.68.108 - - [26/Jan/2019 21:04:53] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
10.55.68.108 - - [26/Jan/2019 21:04:54] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
10.55.68.108 - - [26/Jan/2019 21:05:08] "GET /api/a7161538be80d40b3de98dece6e91f90/ HTTP/1.1" 200 -
10.55.68.108 - - [26/Jan/2019 21:05:16] "GET /description.xml HTTP/1.1" 200 -
10.55.68.108 - - [26/Jan/2019 21:05:16] "GET /description.xml HTTP/1.1" 200 -
10.55.68.108 - - [26/Jan/2019 21:05:16] "GET /description.xml HTTP/1.1" 200 -
```

**Comment by gammeflamme** [comment]
my phones local ip is 10.55.68.116 (the alexa device trying to discover the hub)

**Comment by jorisvanr** [comment]
Are you using Alexa on a Sonos device? I have trouble finding the bridge on Alexa on Sonos (beam and Sonos one). Only when I discover devices on an echo dot I find the bridge. This echo dot now has to be connected to my network and I can control the devices on Sonos Alexa.

**Comment by gammeflamme** [comment]
no i'm using the amazon alexa android app

**Comment by cheesemarathon** [comment]
So you don't have a physical Alexa device?

**Comment by gammeflamme** [comment]
Yes i dont have a physical alexa device, i wanted to try how it interacts first

**Comment by jorisvanr** [comment]
As far as I know it is the Echo Dot that finds the bridge. Not the app.

**Comment by gammeflamme** [comment]
it has the option to add a gen 1 hue hub

**Comment by Nikfinn99** [comment]
The app only tells the Echo to search for devices. Without actual hardware you can not control the bridge. I have an Echo Dot at home, but currently i'm using NodeRed to capure Alexa commands and send them to lights.

**Comment by cheesemarathon** [comment]
I'm going to close this then, as it seems to be a lack of physical Alexa hardware that is the issue.

**Comment by Paalap** [comment]
Instead of opening a new issue, just a short question: should be Alexa (with echo devices) able to discover diyhue? To be detailed: without hue-account (do to the fact I don't have a real bridge). My idea was to connect diyLights in a "lazy" way with ioBroker, i.e. insteaf of creating adaptor or scripts.

**Comment by larsf96** [comment]
I'm currently also having trouble connecting diyHue to Alexa. I've got a couple of Amazon Echo Dot's, so that should not be the problem.
But when activating the Hue Skill, it's telling me that there are no hue bridges in my network. 

netstat -a | grep 2101 ->
`
udp        0      0 localhost:2101          0.0.0.0:*
`

netstat -ulpn 
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 192.168.0.255:137       0.0.0.0:*                           4910/nmbd
udp        0      0 192.168.0.28:137        0.0.0.0:*                           4910/nmbd
udp        0      0 172.17.255.255:137      0.0.0.0:*                           4910/nmbd
udp        0      0 172.17.0.1:137          0.0.0.0:*                           4910/nmbd
udp        0      0 172.30.33.255:137       0.0.0.0:*                           4910/nmbd
udp        0      0 172.30.32.1:137         0.0.0.0:*                           4910/nmbd
udp        0      0 192.168.0.255:137       0.0.0.0:*                           4910/nmbd
udp        0      0 192.168.0.38:137        0.0.0.0:*                           4910/nmbd
udp        0      0 0.0.0.0:137             0.0.0.0:*                           4910/nmbd
udp        0      0 192.168.0.255:138       0.0.0.0:*                           4910/nmbd
udp        0      0 192.168.0.28:138        0.0.0.0:*                           4910/nmbd
udp        0      0 172.17.255.255:138      0.0.0.0:*                           4910/nmbd
udp        0      0 172.17.0.1:138          0.0.0.0:*                           4910/nmbd
udp        0      0 172.30.33.255:138       0.0.0.0:*                           4910/nmbd
udp        0      0 172.30.32.1:138         0.0.0.0:*                           4910/nmbd
udp        0      0 192.168.0.255:138       0.0.0.0:*                           4910/nmbd
udp        0      0 192.168.0.38:138        0.0.0.0:*                           4910/nmbd
udp        0      0 0.0.0.0:138             0.0.0.0:*                           4910/nmbd
udp        0      0 172.30.32.1:5353        0.0.0.0:*                           5904/python3
udp        0      0 192.168.0.28:5353       0.0.0.0:*                           5904/python3
udp        0      0 172.17.0.1:5353         0.0.0.0:*                           5904/python3
udp        0      0 192.168.0.38:5353       0.0.0.0:*                           5904/python3
udp        0      0 127.0.0.1:5353          0.0.0.0:*                           5904/python3
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           5904/python3
udp        0      0 172.30.32.1:5353        0.0.0.0:*                           2927/mdns-repeater
udp        0      0 192.168.0.28:5353       0.0.0.0:*                           2927/mdns-repeater
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           2927/mdns-repeater
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           279/systemd-resolve
udp        0      0 0.0.0.0:5355            0.0.0.0:*                           279/systemd-resolve
udp        0      0 0.0.0.0:51446           0.0.0.0:*                           5904/python3
udp        0      0 0.0.0.0:34581           0.0.0.0:*                           21316/python3
udp     6080      0 0.0.0.0:1900            0.0.0.0:*                           21316/python3
udp        0      0 0.0.0.0:59956           0.0.0.0:*                           5904/python3
udp        0      0 127.0.0.1:2101          0.0.0.0:*                           21316/python3
udp        0      0 0.0.0.0:56890           0.0.0.0:*                           5904/python3
udp        0      0 0.0.0.0:52801           0.0.0.0:*                           5904/python3
udp        0      0 :::51820                :::*                                8059/docker-proxy
udp        0      0 :::5353                 :::*                                279/systemd-resolve
udp        0      0 :::5355                 :::*                                279/systemd-resolve
udp        0      0 fe80::5e4e:cbb4:f1f4:aa9f:546 :::*                                287/NetworkManager
udp        0      0 fe80::ca1:9518:91ab:d5a0:546 :::*                                287/NetworkManager
udp        0      0 :::53                   :::*                                5478/AdGuardHome
```

Any ideas?

**Comment by mariusmotea** [comment]
You need to follow the procedure from here: https://diyhue.readthedocs.io/en/latest/AddFuncts/alexa.html

**Comment by larsf96** [comment]
Hi @mariusmotea,

I've also tried that, but there were no devices found. I got the following logs:
```
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /description.xml HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/1 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/10 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/11 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/12 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/13 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/2 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/3 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/4 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/5 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/6 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/7 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/8 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights/9 HTTP/1.1" 200 -
192.168.0.22 - - [10/Jan/2021 16:22:37] "GET /api/c958adbc535611eb93cfdca63261de47/lights HTTP/1.1" 200 -
```

The ID resolves to a user named "Echo" in my config. Looks like Alexa is searching for devices, but not adding them?

**Comment by mariusmotea** [comment]
Ok, how you install the bridge emulator and what lights are you using?

**Comment by larsf96** [comment]
I use the diyHue Addon for Home Assistant. I have various lights of Philips Hue and some IKEA Tradfri

**Comment by mariusmotea** [comment]
Try a container restart if you did not made it so far. There is a function at startup that fix some keys in lights

**Comment by larsf96** [comment]
I've restarted it a couple of times, but the result is always the same, the lights are not being detected by the Alexa App

**Comment by larsf96** [comment]
I had to reinstall diyHue to get this working. Now the lights are visible in Alexa, but they are being displayed as "unreachable".
Everytime I try to switch a light on or off in the Alexa app, I see the following output in diyhue
```
192.168.0.33 - - [16/Jan/2021 09:41:44] "PUT /api/c0fb6cea535611eb93cfdca63261de47/lights/10/state HTTP/1.1" 200 -
2021-01-16 09:41:44,569 - root - INFO - in PUT method
2021-01-16 09:41:44,570 - root - INFO - /api/c0fb6cea535611eb93cfdca63261de47/lights/10/state
2021-01-16 09:41:44,570 - root - INFO - b'{"on":true}'
```

This pretty much looks like everything is okay, but the light also doesn't change it's state
