### ISSUE TITLE
SSLError Message preventing startup

### ISSUE THREAD

**Issue by spower9991** [diyhue/diyHue#757]
**Describe the issue**
I'm having a real issue launching this program, I'm getting the below code
"Host MAC given as XX-XX-XX-XX-XX-XX

Docker Setup Initiated

SSL certificate found

Config file found

Docker Setup Complete

{"ok"}

Exception in thread Thread-8:

Traceback (most recent call last):

  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/usr/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/opt/hue-emulator/HueEmulator3.py", line 1976, in run

    ctx.load_cert_chain(certfile=_certfile)

ssl.SSLError: [SSL] PEM lib (_ssl.c:3824)"

**Steps you tried**
 I've tried updating Docker, the diyHUE files, even on another machine and im still getting the same issues

**How we can help**
 If someone could take some time out and show me where im going wrong i'd greatly appreciate it

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): x86
 - Docker image version (Ex: latest, arm-05f043b, 128): ?
 - OS (Ex: Windows 10, Ubuntu Buster): Windows 10
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**
 Much appreciated

**Comment by spower9991** [comment]
Fixed this issue
