### ISSUE TITLE
Not Discovering Lights when using Docker

### ISSUE THREAD

**Issue by supersimple33** [diyhue/diyHue#832]
**Describe the bug**

When I run diyHue using docker I the web UI will launch but when I go to discover lights (2 wleds) nothing happens. The logs are below and it seems to be a permission error. When using the local host installation, I am able to add the lights successfully. 

**Steps to Reproduce**

1. Install diyHue using docker. 
2. Connect to webUI3. 
3. Click ```Scan for lights```

**Expected behavior**

The lights should be discovered and added as wled lights using lst002. 

**Logs**

```
2022-06-18 22:56:11,265 - lights.discover - INFO - [
    "10.0.1.7:80",
    "10.0.1.24:80",
    "10.0.1.96:80"
]
10.0.1.197 - - [18/Jun/2022 22:56:11] "GET /lights HTTP/1.1" 200 -
2022-06-18 22:56:13,270 - lights.protocols.native_multi - DEBUG - native: <discover> invoked!
10.0.1.96 - - [18/Jun/2022 22:56:13] "GET /detect HTTP/1.1" 200 -
2022-06-18 22:56:13,364 - lights.protocols.native_multi - INFO - ip 10.0.1.96:80 is unknown device: Expecting value: line 1 column 1 (char 0)
2022-06-18 22:56:13,366 - lights.protocols.tasmota - DEBUG - tasmota: <discover> invoked!
2022-06-18 22:56:13,367 - lights.protocols.tasmota - DEBUG - tasmota: probing ip 10.0.1.7:80
2022-06-18 22:56:13,379 - lights.protocols.tasmota - DEBUG - tasmota: probing ip 10.0.1.24:80
2022-06-18 22:56:13,410 - lights.protocols.tasmota - DEBUG - tasmota: probing ip 10.0.1.96:80
10.0.1.96 - - [18/Jun/2022 22:56:13] "GET /cm?cmnd=Status%200 HTTP/1.1" 200 -
2022-06-18 22:56:13,429 - lights.protocols.tasmota - DEBUG - tasmota: ip 10.0.1.96:80 is unknow device, Expecting value: line 1 column 1 (char 0)
2022-06-18 22:56:13,430 - lights.protocols.wled - INFO - <WLED> discovery started
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 483, in _run_loop
    self.loop = asyncio.new_event_loop()
  File "/usr/lib/python3.9/asyncio/events.py", line 761, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/usr/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
    super().__init__()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 397, in __init__
    self._clock_resolution = time.get_clock_info('monotonic').resolution
PermissionError: [Errno 1] Operation not permitted
Exception ignored in: <function BaseEventLoop.__del__ at 0x75d88388>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/base_events.py", line 681, in __del__
    _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 419, in __repr__
    f'closed={self.is_closed()} debug={self.get_debug()}>'
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1909, in get_debug
    return self._debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): ARM
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): Raspbian
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry pi 4

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

I can use the host install but just wanted to bring this forward.

**Comment by mariusmotea** [comment]
the issue here is clear "PermissionError: [Errno 1] Operation not permitted" 

Are you using Docker installed from SNAP package? That has some permissions issues that still need to be resolved by Ubuntu. Try with Docker-ce instead.

**Comment by saltwotter** [comment]
I was struggling with this. Went down the rabbit hole, it turns out it's something wrong with the Buster version of Raspbian that you can either fix by reinstalling the latest version of Raspbian, or patching your current install by following the instructions from [this comment](https://github.com/freqtrade/freqtrade/issues/6183#issuecomment-1016940306):

> You can also do this to avoid reinstallation :
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
> echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee -a /etc/apt/sources.list.d/buster-backports.list
> sudo apt update
> sudo apt install -t buster-backports libseccomp2

**Comment by saltwotter** [comment]
@Mevel Yes, everything is working correctly now. No more errors when discovering lights or booting up.

**Comment by supersimple33** [comment]
That sounds like the correct fix. I'm a little busy this week but if I find the time I'll check the solution and close this issue.

**Comment by supersimple33** [comment]
Fixed

**Comment by disruptivepatternmaterial** [comment]
I know this is closed, but I am seeing this same behavior on Ubuntu with the Docker image, the scan does nothing...it doesnt find any of my WLED lights, which are all mdns broadcast (I can see them in an mdns tool). I turned on DEBUG and all it tells me is that none were found using mdns. Any ideas on what might something to check?
