### ISSUE TITLE
Hue app doesn't connect.

### ISSUE THREAD

**Issue by foxy82** [diyhue/diyHue#840]
**Describe the bug**

Trying to connect Hue app to diyhue. Diyhue is discovered as a hub. After I click the link button Hue app asks me to name the hub but fails to save the name.

**Steps to Reproduce**

Start Hue App.
Click add hub.
Wait for diyhue to be found and Hue app to ask you to hit the link button.
Hit the link button in Diyhue.
Set a name in Hue app.
Hue app shoes error "Failed to set the Hue Bridge name."

**Expected behavior**

Expected hue app to connect
Expected Hue app to connect to Diyhue.

**Logs**

```
[2022-07-01 16:41:35,211] ERROR in app: Exception on /api/499ff562f95411ec861cb8aeedeaba48/config [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/hue-emulator/flaskUI/restful.py", line 274, in put
    bridgeConfig[resource][key].update(value)
KeyError: 'swupdate2'
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - Docker image version (Ex: latest, arm-05f043b, 128): 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Checklist**
- [X] I confirm that this is a bug report
- [X] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by TRusselo** [comment]
currently working
