### ISSUE TITLE
Unable to run Dev branch

### ISSUE THREAD

**Issue by jimmyeao** [diyhue/diyHue#879]
**Describe the bug**

Unable to run dev branch of DIYHUE

**Steps to Reproduce**

1. chose 2 (dev branch) on intsall
2. Run..
3. See error

**Expected behavior**

**Logs**

```
2023-01-10 13:14:31,992 - configManager.argumentHandler - INFO - Using Host 192.168.0.166:80
2023-01-10 13:14:32,008 - configManager.argumentHandler - INFO - Host MAC given as dca6323b44d3
2023-01-10 13:14:32,009 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2023-01-10 13:14:32,009 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2023-01-10 13:14:32,009 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2023-01-10 13:14:32,017 - configManager.argumentHandler - INFO - Using Host 192.168.0.166:80
2023-01-10 13:14:32,034 - configManager.argumentHandler - INFO - Host MAC given as dca6323b44d3
2023-01-10 13:14:32,034 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2023-01-10 13:14:32,034 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2023-01-10 13:14:32,035 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2023-01-10 13:14:32,037 - configManager.argumentHandler - INFO - Debug logging disabled!
2023-01-10 13:14:32,039 - configManager.configHandler - INFO - Config loaded
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 104, in <module>
    from services import mqtt, deconz, ssdp, mdns, scheduler, remoteApi, remoteDiscover, entertainment, stateFetch, eventStreamer, homeAssistantWS
  File "/opt/hue-emulator/services/mqtt.py", line 1, in <module>
    from sqlalchemy import false, true
ModuleNotFoundError: No module named 'sqlalchemy'
Exception ignored in: <function Group.__del__ at 0xb54c8418>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 956, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Sensor.__del__ at 0xb54ca148>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 1638, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down

```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM):  ARM
 - Docker image version (Ex: latest, arm-05f043b, 128):  N/A
 - OS (Ex: Windows 10, Ubuntu Buster):  Debian
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero):  Raspberry Pi4 (32bit OS)

**Checklist**
- [ X] I confirm that this is a bug report
- [ X] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
Dev branch remain behind to master and need to be recreated. Can you please select master branch?

**Comment by jimmyeao** [comment]
I can, however i cant connect Home assistant to the Master branch version, is this a known issue?

**Comment by mariusmotea** [comment]
I'm not aware but from what i saw on chats some users did not manage directly to connect diyhue to homeassistant. What you see in the logs when you try to pair diyhue with homeassistant?

**Comment by jimmyeao** [comment]
```
2023-01-10 15:27:14.556 ERROR (MainThread) [homeassistant.components.hue.config_flow] Unknown error connecting with Hue bridge at 192.168.0.166
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/config_flow.py", line 170, in async_step_link
    app_key = await create_app_key(
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 56, in create_app_key
    raise exc
  File "/usr/local/lib/python3.10/site-packages/aiohue/util.py", line 47, in create_app_key
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
```

**Comment by jimmyeao** [comment]
```
Jan 10 15:27:12 huepi HueEmulator3.py[17861]: [2023-01-10 15:27:12,682] ERROR in app: Exception on /api/c8f05806903611eda158dca6323b44d3/config [PUT]
Jan 10 15:27:12 huepi HueEmulator3.py[17861]: Traceback (most recent call last):
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:     rv = self.dispatch_request()
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 467, in wrapper
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:     resp = resource(*args, **kwargs)
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 84, in view
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 582, in dispatch_request
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:     resp = meth(*args, **kwargs)
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:   File "/opt/hue-emulator/flaskUI/restful.py", line 274, in put
Jan 10 15:27:12 huepi HueEmulator3.py[17861]:     bridgeConfig[resource][key].update(value)
Jan 10 15:27:12 huepi HueEmulator3.py[17861]: AttributeError: 'bool' object has no attribute 'update'
Jan 10 15:27:12 huepi HueEmulator3.py[17861]: 2023-01-10 15:27:12,685 - werkzeug - INFO - 192.168.0.82 - - [10/Jan/2023 15:27:12] "#033[35m#033[1mPUT /api/c8f05806903611eda158dca6323b44d3/config HTTP/1.1#033[0m" 500 -
Jan 10 15:27:13 huepi HueEmulator3.py[17861]: 2023-01-10 15:27:13,148 - services.stateFetch - WARNING - wledsr_seg0 is unreachable: <urlopen error [Errno 113] No route to host>
Jan 10 15:27:14 huepi HueEmulator3.py[17861]: [2023-01-10 15:27:14,495] ERROR in app: Exception on /api [POST]
Jan 10 15:27:14 huepi HueEmulator3.py[17861]: Traceback (most recent call last):
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     rv = self.dispatch_request()
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 467, in wrapper
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     resp = resource(*args, **kwargs)
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 84, in view
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 582, in dispatch_request
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     resp = meth(*args, **kwargs)
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/opt/hue-emulator/flaskUI/restful.py", line 76, in post
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     last_button_press = bridgeConfig["config"]["linkbutton"]["lastlinkbuttonpushed"]
Jan 10 15:27:14 huepi HueEmulator3.py[17861]: TypeError: 'bool' object is not subscriptable
Jan 10 15:27:14 huepi HueEmulator3.py[17861]: 2023-01-10 15:27:14,499 - werkzeug - INFO - 192.168.0.237 - - [10/Jan/2023 15:27:14] "#033[35m#033[1mPOST /api HTTP/1.1#033[0m" 500 -
Jan 10 15:27:14 huepi HueEmulator3.py[17861]: [2023-01-10 15:27:14,537] ERROR in app: Exception on /api [POST]
Jan 10 15:27:14 huepi HueEmulator3.py[17861]: Traceback (most recent call last):
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     rv = self.dispatch_request()
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 467, in wrapper
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     resp = resource(*args, **kwargs)
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 84, in view
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 582, in dispatch_request
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     resp = meth(*args, **kwargs)
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:   File "/opt/hue-emulator/flaskUI/restful.py", line 76, in post
Jan 10 15:27:14 huepi HueEmulator3.py[17861]:     last_button_press = bridgeConfig["config"]["linkbutton"]["lastlinkbuttonpushed"]
Jan 10 15:27:14 huepi HueEmulator3.py[17861]: TypeError: 'bool' object is not subscriptable
```

**Comment by TRusselo** [comment]
master branch / Home assistant bug is known issue.
pointing this out to dev, that dev branch did work.
