### ISSUE TITLE
Got error when connecting app

### ISSUE THREAD

**Issue by pppranik** [diyhue/diyHue#901]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Install Script

### Home Assistant related?

No

### Description

Hi! I got an error when connecting android app
Here log:

### Errorlog:

```
Mar 29 20:02:14 HueEmulator3.py[32699]: 2023-03-29 20:02:14,153 - werkzeug - INFO - 192.168.1.208 - - [29/Mar/2023 20:02:14] "GET /clip/v2/resource HTTP/1.1" 5
Mar 29 20:02:14 HueEmulator3.py[32699]: 2023-03-29 20:02:14,859 - werkzeug - INFO - 192.168.1.208 - - [29/Mar/2023 20:02:14] "GET /clip/v2/resource/bridge HTTP
Mar 29 20:02:14 HueEmulator3.py[32699]: 2023-03-29 20:02:14,964 - werkzeug - INFO - 192.168.1.208 - - [29/Mar/2023 20:02:14] "GET /eventstream/clip/v2 HTTP/1.1
Mar 29 20:02:15 HueEmulator3.py[32699]: [2023-03-29 20:02:15,050] ERROR in app: Exception on /clip/v2/resource [GET]
Mar 29 20:02:15 HueEmulator3.py[32699]: Traceback (most recent call last):
Mar 29 20:02:15 HueEmulator3.py[32699]:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1516, in full_dispatch_request
Mar 29 20:02:15 HueEmulator3.py[32699]:     rv = self.dispatch_request()
Mar 29 20:02:15 HueEmulator3.py[32699]:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1502, in dispatch_request
Mar 29 20:02:15 HueEmulator3.py[32699]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Mar 29 20:02:15 HueEmulator3.py[32699]:   File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 467, in wrapper
Mar 29 20:02:15 HueEmulator3.py[32699]:     resp = resource(*args, **kwargs)
Mar 29 20:02:15 HueEmulator3.py[32699]:   File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 84, in view
Mar 29 20:02:15 HueEmulator3.py[32699]:     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
Mar 29 20:02:15 HueEmulator3.py[32699]:   File "/usr/local/lib/python3.7/dist-packages/flask_restful/__init__.py", line 582, in dispatch_request
Mar 29 20:02:15 HueEmulator3.py[32699]:     resp = meth(*args, **kwargs)
Mar 29 20:02:15 HueEmulator3.py[32699]:   File "/opt/hue-emulator/flaskUI/v2restapi.py", line 248, in get
Mar 29 20:02:15 HueEmulator3.py[32699]:     data.append(light.getV2Api())
Mar 29 20:02:15 HueEmulator3.py[32699]:   File "/opt/hue-emulator/HueObjects/__init__.py", line 502, in getV2Api
Mar 29 20:02:15 HueEmulator3.py[32699]:     "points_capable": self.protocol_cfg["points_capable"]}
Mar 29 20:02:15 HueEmulator3.py[32699]: KeyError: 'points_capable'
```

### Steps to reproduce

Install diyhue by script, add wled lights by diyhue webui and add it to andrid app

### Please enter your operating system details here

android 13

### What DiyHue version(branch) are you using?

master (latest)

**Comment by mariusmotea** [comment]
Don't use LCX004 modelid. That is Hue Gradient Strip and need to be discovered automatically to add additional keys.

**Comment by pppranik** [comment]
Thank you! What modelid i should use for gradient strip?

**Comment by mariusmotea** [comment]
LST002

**Comment by pppranik** [comment]
Thank you
