### ISSUE TITLE
Groups not being synched with iLightShow

### ISSUE THREAD

**Issue by schumi2004** [diyhue/diyHue#908]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

No

### Description

I have the latest diHue version running in Docker, i have connected it to Home Assistant and all the lights are added in diyHue.
Using Hue Essentials i created groups and organized the lights
All working perfect.

Now, when i connect iLightShow i only see 1 group named Default and not the groups i created using Hue Essentials.

### Errorlog:

I don't see any errors in diyHue but i do see a lot of these messages inthe iLightShow logs, not sure if it is related

2023-05-08T10:32:36.781Z | 1.0 : Android-13 | 59709732bfcbf192 | [ERROR/DeviceDiscoveryHue]: Received empty signup response from hue bridge.
2023-05-08T10:32:36.973Z | 1.0 : Android-13 | 59709732bfcbf192 | [ERROR/DeviceDiscoveryHue]: Received empty signup response from hue bridge.
2023-05-08T10:32:37.068Z | 1.0 : Android-13 | 59709732bfcbf192 | [ERROR/DeviceDiscoveryHue]: Received empty signup response from hue bridge.
2023-05-08T10:32:38.805Z | 1.0 : Android-13 | 59709732bfcbf192 | [ERROR/DeviceDiscoveryHue]: Received empty signup response from hue bridge.

### Steps to reproduce

Setup diyHue using docker, setup your lights using HA and organize them in groups using Hue Essentials

Connect iLightShow when done.

### Please enter your operating system details here

iLightShow for Android v2.1.13
Latest docker image for diyHue
Home Assistant version 2023.5.2 (not related imo)

### What DiyHue version(branch) are you using?

master (latest)

**Comment by mariusmotea** [comment]
Can you show also diyhue logs? I think there are some errors since you get "[ERROR/DeviceDiscoveryHue]: Received empty signup response from hue bridge."

**Comment by schumi2004** [comment]
I think i found what is the root cause.
I created zones in Hue Essentials instead of real rooms, seems to work now.

Will check the logs after modifications and upload if i see something strange.

**Comment by schumi2004** [comment]
Okay. After strugling with certain things and functions not working as expected i eventually ended up with below errors

https://hastebin.com/share/ogidawirej.yaml

This is the most important one:
2023-05-09 10:53:59,587 - services.mdns - INFO - <MDNS> listener started
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-05-09 10:53:59,593 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2023-05-09 10:53:59,593 - werkzeug - INFO -  * Running on http://10.0.0.165:80/ (Press CTRL+C to quit)
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/services/mdns.py", line 26, in mdnsListener
    zeroconf.register_service(info) 
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 574, in register_service
    run_coro_with_timeout(
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/asyncio.py", line 97, in run_coro_with_timeout
    return asyncio.run_coroutine_threadsafe(aw, loop).result(
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/asyncio.py", line 81, in await_awaitable
    task = await aw
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 602, in async_register_service
 * Serving Flask app 'HueEmulator3' (lazy loading)
    await self.async_check_service(info, allow_name_change, cooperating_responders)
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 762, in async_check_service
    raise NonUniqueNameException
zeroconf._exceptions.NonUniqueNameException
 * Environment: production

**Comment by mariusmotea** [comment]
`zeroconf._exceptions.NonUniqueNameException`

I think you are using two diyhue instances in the same network and they made conflict on MDNS name.
