### ISSUE TITLE
Can not connect to HA nor to my mqtt server

### ISSUE THREAD

**Issue by u20p17** [diyhue/diyHue#940]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

Yes

### Description

I am trying to connect to my home assistant (192.168.1.10:8123) and/or mqtt server (192.168.1.11:1883), but both do not work... HA token is correct (renewed and copied the token several times...)

### Errorlog:

Error Log for HA:
```
2023-10-18 20:08:37,472 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2023-10-18 20:08:37,474 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2023-10-18 20:11:02,637 - services.homeAssistantWS - WARNING - Home Assistant Web Socket Client disconnected trying to (re)connect
2023-10-18 20:11:02,640 - services.homeAssistantWS - ERROR - Home Assistant Web Socket Authorisation invalid: {'type': 'auth_invalid', 'message': 'Invalid access token or password'}
2023-10-18 20:11:02,643 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2023-10-18 20:11:02,645 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2023-10-18 20:08:37,468 - services.remoteDiscover - INFO - Starting discovery service
2023-10-18 20:08:37,468 - services.stateFetch - INFO - start lights sync
2023-10-18 20:08:37,469 - services.ssdp - INFO - start ssdp broadcast
2023-10-18 20:08:37,470 - services.ssdp - INFO - starting ssdp...
2023-10-18 20:08:37,470 - services.mdns - INFO - <MDNS> listener started
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-10-18 20:08:37,472 - werkzeug - INFO -  * Running on http://192.168.1.9:80/ (Press CTRL+C to quit)
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-10-18 20:08:37,474 - werkzeug - INFO -  * Running on https://192.168.1.9:443/ (Press CTRL+C to quit)
2023-10-18 20:08:37,815 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:08:37] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:08:42,573 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:08:42] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:08:46,573 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:08:46] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:08:48,469 - services.stateFetch - INFO - start lights sync
2023-10-18 20:08:49,397 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:08:49] "GET /api/40b8e514151c11eea41948210b55d4b7/config/mqtt HTTP/1.1" 200 -
2023-10-18 20:08:49,438 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:08:49] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-18 20:08:50,806 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:08:50] "GET /api/40b8e514151c11eea41948210b55d4b7/config/homeassistant HTTP/1.1" 200 -
2023-10-18 20:08:50,809 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:08:50] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-18 20:08:51,578 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:08:51] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:08:52,722 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:08:52] "GET /api/40b8e514151c11eea41948210b55d4b7/config/mqtt HTTP/1.1" 200 -
2023-10-18 20:08:52,723 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:08:52] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-18 20:08:56,577 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:08:56] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:02,563 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:02] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:04,470 - services.stateFetch - INFO - start lights sync
2023-10-18 20:09:07,570 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:07] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:12,575 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:12] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:17,574 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:17] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:19,471 - services.stateFetch - INFO - start lights sync
2023-10-18 20:09:22,574 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:22] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:27,578 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:27] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:32,577 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:32] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:34,472 - services.stateFetch - INFO - start lights sync
2023-10-18 20:09:37,563 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:37] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:42,569 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:42] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:47,581 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:47] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:49,473 - services.stateFetch - INFO - start lights sync
2023-10-18 20:09:52,571 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:52] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:09:57,576 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:09:57] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:10:31,564 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:10:31] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:10:33,479 - services.stateFetch - INFO - start lights sync
2023-10-18 21:11:02,607 - configManager.argumentHandler - INFO - Using Host 192.168.1.8:80
2023-10-18 21:11:02,607 - configManager.argumentHandler - INFO - Host MAC given as 48210B55D4B7
2023-10-18 21:11:02,607 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2023-10-18 21:11:02,607 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2023-10-18 21:11:02,607 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2023-10-18 21:11:02,608 - configManager.argumentHandler - INFO - Using Host 192.168.1.8:80
2023-10-18 21:11:02,608 - configManager.argumentHandler - INFO - Host MAC given as 48210B55D4B7
2023-10-18 21:11:02,608 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2023-10-18 21:11:02,608 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2023-10-18 21:11:02,608 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2023-10-18 21:11:02,608 - configManager.argumentHandler - INFO - Debug logging disabled!
2023-10-18 20:11:02,615 - configManager.configHandler - INFO - Config loaded
2023-10-18 20:11:02,639 - services.homeAssistantWS - INFO - Home Assistant WebSocket Connection Opened
2023-10-18 20:11:02,639 - services.homeAssistantWS - INFO - Home Assistant Web Socket Client connected
2023-10-18 20:11:02,639 - services.homeAssistantWS - INFO - Home Assistant Web Socket Authorisation required
2023-10-18 20:11:02,639 - services.remoteDiscover - INFO - Starting discovery service
2023-10-18 20:11:02,640 - services.stateFetch - INFO - start lights sync
2023-10-18 20:11:02,641 - services.ssdp - INFO - starting ssdp...
2023-10-18 20:11:02,642 - services.ssdp - INFO - start ssdp broadcast
2023-10-18 20:11:02,642 - services.mdns - INFO - <MDNS> listener started
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-10-18 20:11:02,644 - werkzeug - INFO -  * Running on http://192.168.1.9:80/ (Press CTRL+C to quit)
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-10-18 20:11:02,645 - werkzeug - INFO -  * Running on https://192.168.1.9:443/ (Press CTRL+C to quit)
2023-10-18 20:11:02,665 - services.homeAssistantWS - INFO - Home Assistant WebSocket Connection Closed. Code: 1000 Reason b''

```

Error Log MQTT-Server:
```
text  error  warn  system  array  login  

2023-10-18 20:11:02,643 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2023-10-18 20:11:02,645 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2023-10-18 20:14:41,246 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2023-10-18 20:14:41,248 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
Exception in thread Thread-2 (mqttServer):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/services/mqtt.py", line 446, in mqttServer
    client.connect(bridgeConfig["config"]["mqtt"]["mqttServer"], bridgeConfig["config"]["mqtt"]["mqttPort"])
  File "/usr/local/lib/python3.11/dist-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
 * Debug mode: off
2023-10-18 20:11:02,644 - werkzeug - INFO -  * Running on http://192.168.1.9:80/ (Press CTRL+C to quit)
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-10-18 20:11:02,645 - werkzeug - INFO -  * Running on https://192.168.1.9:443/ (Press CTRL+C to quit)
2023-10-18 20:11:02,665 - services.homeAssistantWS - INFO - Home Assistant WebSocket Connection Closed. Code: 1000 Reason b''
2023-10-18 20:11:31,619 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:11:31] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:11:32,645 - services.stateFetch - INFO - start lights sync
2023-10-18 20:12:31,583 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:12:31] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:12:32,653 - services.stateFetch - INFO - start lights sync
2023-10-18 20:13:31,579 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:13:31] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:13:32,661 - services.stateFetch - INFO - start lights sync
2023-10-18 20:14:15,266 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:15] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:14:16,577 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:16] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:14:16,667 - services.stateFetch - INFO - start lights sync
2023-10-18 20:14:19,080 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:19] "PUT /api/40b8e514151c11eea41948210b55d4b7/config HTTP/1.1" 200 -
2023-10-18 20:14:20,116 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:20] "GET /api/40b8e514151c11eea41948210b55d4b7/config/homeassistant HTTP/1.1" 200 -
2023-10-18 20:14:20,172 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:20] "GET /favicon.ico HTTP/1.1" 200 -
2023-10-18 20:14:21,583 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:21] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:14:21,717 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:21] "PUT /api/40b8e514151c11eea41948210b55d4b7/config HTTP/1.1" 200 -
2023-10-18 20:14:27,584 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:27] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:14:28,667 - services.stateFetch - INFO - start lights sync
2023-10-18 20:14:32,571 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:32] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:14:37,578 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:37] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:14:39,668 - services.stateFetch - INFO - start lights sync
2023-10-18 21:14:41,210 - configManager.argumentHandler - INFO - Using Host 192.168.1.8:80
2023-10-18 21:14:41,210 - configManager.argumentHandler - INFO - Host MAC given as 48210B55D4B7
2023-10-18 21:14:41,210 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2023-10-18 21:14:41,210 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2023-10-18 21:14:41,210 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2023-10-18 21:14:41,211 - configManager.argumentHandler - INFO - Using Host 192.168.1.8:80
2023-10-18 21:14:41,211 - configManager.argumentHandler - INFO - Host MAC given as 48210B55D4B7
2023-10-18 21:14:41,211 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2023-10-18 21:14:41,211 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2023-10-18 21:14:41,211 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2023-10-18 21:14:41,211 - configManager.argumentHandler - INFO - Debug logging disabled!
2023-10-18 20:14:41,218 - configManager.configHandler - INFO - Config loaded
2023-10-18 20:14:41,242 - services.mqtt - INFO - Strting MQTT service...
2023-10-18 20:14:41,242 - services.remoteDiscover - INFO - Starting discovery service
2023-10-18 20:14:41,243 - services.stateFetch - INFO - start lights sync
2023-10-18 20:14:41,244 - services.ssdp - INFO - starting ssdp...
2023-10-18 20:14:41,244 - services.ssdp - INFO - start ssdp broadcast
2023-10-18 20:14:41,244 - services.mdns - INFO - <MDNS> listener started
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-10-18 20:14:41,247 - werkzeug - INFO -  * Running on http://192.168.1.9:80/ (Press CTRL+C to quit)
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-10-18 20:14:41,248 - werkzeug - INFO -  * Running on https://192.168.1.9:443/ (Press CTRL+C to quit)
2023-10-18 20:14:42,933 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:42] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:14:47,578 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:47] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
2023-10-18 20:14:52,574 - werkzeug - INFO - 192.168.1.121 - - [18/Oct/2023 20:14:52] "GET /api/40b8e514151c11eea41948210b55d4b7/groups/0 HTTP/1.1" 200 -
```

### Steps to reproduce

docker run
  -d
  --name='diyHue'
  --net='br0'
  --ip='192.168.1.9'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="UnRaidBirgit"
  -e HOST_CONTAINERNAME="diyHue"
  -e 'TCP_PORT_80'='80'
  -e 'TCP_PORT_443'='443'
  -e 'UDP_PORT_1900'='1900'
  -e 'UDP_PORT_2100'='2100'
  -e 'MAC'='48:21:0B:55:D4:B7'
  -e 'IP'='192.168.1.8'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:80]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/cheesemarathon/docker-templates/master/images/diyhue.png'
  -v '/mnt/user/appdata/diyHue':'/opt/hue-emulator/config/':'rw' 'diyhue/core:latest'
e8fcd284d49cb3279a67546c2187c3131158cf4f8fc0c62a03db10c7065b8e57

The command finished successfully!

### Please enter your operating system details here

Intel NUC (NUC13ANBi7 ) with Unraid 6.12.4

### What DiyHue version(branch) are you using?

master (latest)

**Comment by mariusmotea** [comment]
"OSError: [Errno 113] No route to host" is the mqtt server reachable from the container?

**Comment by u20p17** [comment]
how can I test this? but I think it should be reachable because I can also reach the mqtt server from my laptop (which is in the same ip range as the container (192.168.1.x))

**Comment by u20p17** [comment]
i am using unifi hardware, so could be a firewall issue... what firewall rules I would have to add for the mqtt communication with the docker container?

**Comment by u20p17** [comment]
today i had some time for further debugging and I found out the following:

Test1:
When I run the following docker command mqtt is working fine (bridge mode and i changed the port 80 and 443 (i know this ports must not be changed...) just for testing):

```
docker run
  -d
  --name='diyHue'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="HomeServer"
  -e HOST_CONTAINERNAME="diyHue"
  -e 'MAC'=' 48:21:0B:26:39:5A'
  -e 'IP'='192.168.1.4'
  -e 'DEBUG'='true'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:80]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/cheesemarathon/docker-templates/master/images/diyhue.png'
  -p '81:80/tcp'
  -p '4431:443/tcp'
  -p '1900:1900/udp'
  -p '2100:2100/udp'
  -v '/mnt/user/appdata/diyHue':'/opt/hue-emulator/config/':'rw' 'diyhue/core:latest'
5e811855aedc484aed28d244b8e4b9e4485b7d717a6e6d952e6d5f4a090f54bc
```
![image](https://github.com/diyhue/diyHue/assets/63282286/caacd79f-2de1-4c6b-8748-b822cf78578d)


Test2:
If I use a custom network with the original ports MQTT is not working --> same error as some weeks ago --> OSError: [Errno 113] No route to host

```
docker run
  -d
  --name='diyHue'
  --net='br0'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="HomeServer"
  -e HOST_CONTAINERNAME="diyHue"
  -e 'TCP_PORT_80'='80'
  -e 'TCP_PORT_443'='443'
  -e 'UDP_PORT_1900'='1900'
  -e 'UDP_PORT_2100'='2100'
  -e 'MAC'=' 48:21:0B:26:39:5A'
  -e 'IP'='192.168.1.4'
  -e 'DEBUG'='true'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:80]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/cheesemarathon/docker-templates/master/images/diyhue.png'
  -v '/mnt/user/appdata/diyHue':'/opt/hue-emulator/config/':'rw' 'diyhue/core:latest'
882db02bdba4eca3c3456fde36024f05c1be72deb2ea9f63fcde5d5e420f5124
```
![image](https://github.com/diyhue/diyHue/assets/63282286/ad66c362-e0a7-470c-9c19-08eecd318220)

My mqtt settings in DIYHue were exactly the same in both tests. (mqtt server ip is 192.168.0.2:1883) Why is it not working with br0 network? :(
