### ISSUE TITLE
Device is unreachable: float division by zero in a Tasmota-like lightbulb

### ISSUE THREAD

**Issue by DiegoJp** [diyhue/diyHue#941]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

Yes

### Description

Hello, when adding a [OpenBk](https://github.com/openshwprojects/OpenBK7231T_App) (which is Tasmota-like custom firmware for Tuya devices) lightbulb to diyHue from the webapp sometimes the logs floods with:

`2023-10-21 10:30:19,826 - services.stateFetch - WARNING - ampolleta-velador is unreachable: float division by zero`

In which ampolleta-velador is my device's hostname. Of course this devices is always on and connected to my Wi-Fi network with no issues (I can ping to it with 0% packet loss) 
![imagen](https://github.com/diyhue/diyHue/assets/41808318/a56bd6a5-ba42-4a5f-8474-8bdf25374d8f)

Other lights configured (such as WLED) and disconnected from the network shows as this:

`2023-10-21 10:35:33,429 - services.stateFetch - WARNING - wled-f83867_seg0 is unreachable: <urlopen error [Errno 113] Host is unreachable>` which is different.

This behaviour `_device_ is unreachable: float division by zero` causes Hue Essentials app and Hue Sync windows app to sometimes treat the lightbulbs as it were disconnected but they are actually connected and OK.

I do not know if this issue is related to diyHue or OpenBeken so please guide me on how (and who) to proceed with this. I can be of help

Regards, Diego Jp

### Errorlog:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------

 Add-on: diyHue
 Emulate a Hue Bridge, add lights, sensors etc. from different vendors into one Ecosystem
-----------------------------------------------------------
 Add-on version: 2.0.9
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.0  (amd64 / qemux86-64)
 Home Assistant Core: 2023.10.3
 Home Assistant Supervisor: 2023.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/config/diyhue exists.
Your Architecture is = amd64
Serve HTTPS
2023-10-21 10:30:16,412 - configManager.argumentHandler - INFO - Using Host 192.168.1.190:80
2023-10-21 10:30:16,412 - configManager.argumentHandler - INFO - Host MAC given as 02186852322F
2023-10-21 10:30:16,412 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2023-10-21 10:30:16,412 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2023-10-21 10:30:16,412 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2023-10-21 10:30:16,414 - configManager.argumentHandler - INFO - Using Host 192.168.1.190:80
2023-10-21 10:30:16,415 - configManager.argumentHandler - INFO - Host MAC given as 02186852322F
2023-10-21 10:30:16,415 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2023-10-21 10:30:16,415 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2023-10-21 10:30:16,415 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2023-10-21 10:30:16,416 - configManager.argumentHandler - INFO - Debug logging disabled!
2023-10-21 10:30:16,564 - configManager.configHandler - INFO - Config loaded
2023-10-21 10:30:16,660 - services.mqtt - INFO - Strting MQTT service...
2023-10-21 10:30:16,660 - services.homeAssistantWS - WARNING - Home Assistant Web Socket Client disconnected trying to (re)connect
2023-10-21 10:30:16,663 - services.homeAssistantWS - INFO - Home Assistant WebSocket Connection Opened
2023-10-21 10:30:16,663 - services.homeAssistantWS - INFO - Home Assistant WebSocket Connection Closed. Code: 1006 Reason Going away
2023-10-21 10:30:16,664 - services.homeAssistantWS - ERROR - Error connecting to Home Assistant WebSocket
Traceback (most recent call last):
  File "/opt/hue-emulator/services/homeAssistantWS.py", line 232, in create_websocket_client
    homeassistant_ws_client.connect()
  File "/usr/local/lib/python3.8/site-packages/ws4py/client/__init__.py", line 247, in connect
    self.process(body)
  File "/usr/local/lib/python3.8/site-packages/ws4py/websocket.py", line 462, in process
    self.reading_buffer_size = s.parser.send(bytes) or DEFAULT_READING_SIZE
AttributeError: 'NoneType' object has no attribute 'parser'
2023-10-21 10:30:16,666 - services.remoteDiscover - INFO - Starting discovery service
2023-10-21 10:30:16,675 - services.stateFetch - INFO - start lights sync
2023-10-21 10:30:16,679 - services.ssdp - INFO - starting ssdp...
2023-10-21 10:30:16,680 - services.ssdp - INFO - start ssdp broadcast
2023-10-21 10:30:16,685 - services.mdns - INFO - <MDNS> listener started
2023-10-21 10:30:16,693 - services.mqtt - INFO - Auto discovery message on: homeassistant/light/0xa4c138188c422939/light/config
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-10-21 10:30:16,699 - werkzeug - INFO -  * Running on http://192.168.1.190:80/ (Press CTRL+C to quit)
2023-10-21 10:30:16,699 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-10-21 10:30:16,704 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2023-10-21 10:30:16,704 - werkzeug - INFO -  * Running on https://192.168.1.190:443/ (Press CTRL+C to quit)
2023-10-21 10:30:19,765 - services.stateFetch - WARNING - wled-f83867_seg0 is unreachable: <urlopen error [Errno 113] Host is unreachable>
2023-10-21 10:30:19,826 - services.stateFetch - WARNING - ampolleta-velador is unreachable: float division by zero
2023-10-21 10:30:19,883 - services.stateFetch - WARNING - ampolleta-techo is unreachable: float division by zero
2023-10-21 10:35:30,339 - services.stateFetch - INFO - start lights sync
2023-10-21 10:35:33,429 - services.stateFetch - WARNING - wled-f83867_seg0 is unreachable: <urlopen error [Errno 113] Host is unreachable>
2023-10-21 10:35:33,480 - services.stateFetch - WARNING - ampolleta-velador is unreachable: float division by zero
2023-10-21 10:35:33,537 - services.stateFetch - WARNING - ampolleta-techo is unreachable: float division by zero

### Steps to reproduce

- Add light from webapp, selecting Autodetect in the dropdown menu (shows as this):
![imagen](https://github.com/diyhue/diyHue/assets/41808318/a67a6fbb-8606-4f88-9650-05a7a5ed9aed)

![imagen](https://github.com/diyhue/diyHue/assets/41808318/a439f62d-d04c-4b90-bbc3-7fbb2383495b)

- Then check log and they show as if they are unreachable (they are not!)

- Check Hue Essentials app
![imagen](https://github.com/diyhue/diyHue/assets/41808318/1b531e89-fba6-4e2c-b2c4-559585a53943)
They show as this and sometimes they cannot be controlled of a popup may appear saying I'm not connected to WiFi (which is incorrect) 

If I remove the lightbulbs from diyHue these messages do not appear ever.

### Please enter your operating system details here

The install is a Home Assistant setup addon, hosted in a Proxmox VM in a HP mini PC.

### What DiyHue version(branch) are you using?

master (latest)

**Comment by DiegoJp** [comment]
fixed a long time ago by #1013
