### ISSUE TITLE
Is the certificate server down?

### ISSUE THREAD

**Issue by ToracX** [diyhue/diyHue#942]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Install Script

### Home Assistant related?

Yes

### Description

My cert.pem is empty. Trying to manually create a certificate using

curl "http://mariusmotea.go.ro:9002/gencert?mac=XX:XX:XX:XX:XX:XX"

Gives a timeout:

`curl: (7) Failed to connect to mariusmotea.go.ro port 9002: Timed out`

Any clues or tips how to fix it?

Also using this command curl https://192.168.178.101/api/nouser/config -v -k

```
Trying 192.168.178.101...
TCP_NODELAY set
connect to 192.168.178.101 port 443 failed: Connection refused
Failed to connect to 192.168.178.101 port 443: Connection refused
Closing connection 0
curl: (7) Failed to connect to 192.168.178.101 port 443: Connection refused
```

### Errorlog:

```
* Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
Exception in thread Thread-10:
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2023-10-23 16:58:38,678 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2023-10-23 16:58:38,702 - werkzeug - INFO -  * Running on http://192.168.178.101:80/ (Press CTRL+C to quit)
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/HueEmulator3.py", line 95, in runHttps
    ctx.load_cert_chain(certfile=CONFIG_PATH + "/cert.pem")
ssl.SSLError: [SSL] PEM lib (_ssl.c:4023)


`curl: (7) Failed to connect to mariusmotea.go.ro port 9002: Timed out`

Trying 192.168.178.101...
TCP_NODELAY set
connect to 192.168.178.101 port 443 failed: Connection refused
Failed to connect to 192.168.178.101 port 443: Connection refused
Closing connection 0
curl: (7) Failed to connect to 192.168.178.101 port 443: Connection refused
```

### Steps to reproduce

try curl "http://mariusmotea.go.ro:9002/gencert?mac=XX:XX:XX:XX:XX:XX"

### Please enter your operating system details here

Rpi 3b with hass using the diyhue hass addon.

### What DiyHue version(branch) are you using?

master (latest)

**Comment by mariusmotea** [comment]
Fixed.

**Comment by ToracX** [comment]
Thanks works great now. Except when Im trying to add gradient lights to a new entertainment room hue app doesnt find any lights to add?
