### ISSUE TITLE
Cant start addon anymore getting error

### ISSUE THREAD

**Issue by ToracX** [diyhue/diyHue#975]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

Yes

### Description

Addon wont start. Tries rebooting system reinstalling addon multiple times. 

### Errorlog:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: diyHue
 Emulate a Hue Bridge, add lights, sensors etc. from different vendors into one Ecosystem
-----------------------------------------------------------
 Add-on version: 2.0.10
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2023.10.5
 Home Assistant Supervisor: 2023.11.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/config/diyhue exists.
Your Architecture is = aarch64
Serve HTTPS
2023-12-12 21:55:52,834 - configManager.argumentHandler - INFO - Using Host 192.168.178.101:80
2023-12-12 21:55:52,835 - configManager.argumentHandler - INFO - Host MAC given as B827EB62CE3E
2023-12-12 21:55:52,836 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2023-12-12 21:55:52,836 - configManager.argumentHandler - INFO - Deconz IP given as 192.168.178.101
2023-12-12 21:55:52,837 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2023-12-12 21:55:52,864 - configManager.argumentHandler - INFO - Using Host 192.168.178.101:80
2023-12-12 21:55:52,864 - configManager.argumentHandler - INFO - Host MAC given as B827EB62CE3E
2023-12-12 21:55:52,865 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2023-12-12 21:55:52,866 - configManager.argumentHandler - INFO - Deconz IP given as 192.168.178.101
2023-12-12 21:55:52,867 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2023-12-12 21:55:52,878 - configManager.argumentHandler - INFO - Debug logging disabled!
2023-12-12 20:55:53,534 - configManager.configHandler - ERROR - CRITICAL! Config file was not loaded
Traceback (most recent call last):
  File "/opt/hue-emulator/configManager/configHandler.py", line 142, in load_config
    for scene, data in scenes.items():
AttributeError: 'NoneType' object has no attribute 'items'
CRITICAL! Config file was not loaded
Exception ignored in: <function Light.__del__ at 0x7f86e95670>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 307, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Light.__del__ at 0x7f86e95670>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 307, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Group.__del__ at 0x7f86e97790>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 968, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function EntertainmentConfiguration.__del__ at 0x7f86e95f70>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 703, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function Group.__del__ at 0x7f86e97790>
Traceback (most recent call last):
  File "/opt/hue-emulator/HueObjects/__init__.py", line 968, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
[cmd] ./run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

### Steps to reproduce

Install addon and click start

### Please enter your operating system details here

Newest hass
Pi 3

### What DiyHue version(branch) are you using?

master (latest)

**Comment by mariusmotea** [comment]
i think you need to delete the config files that may be corrupted.

**Comment by ToracX** [comment]
> i think you need to delete the config files that may be corrupted.

Where can i find the config file? Because I have no directory with /opt/ using SSH.

**Comment by ToracX** [comment]
Could you please let us know how to delete that config file? As of now atleast 5 people are not able to use the plugin because of this bug.

**Comment by mariusmotea** [comment]
I'm not an HAOS user but i know the addons need to store the files in a dedicated path. I think this error is happening because of a service stop during config save task that lead to corrupted config and is not related to other HAOS issues reported. Try to see on homeassistant guides how you can erase the storage of the addons.
