### ISSUE TITLE
App keeps crashing after few days

### ISSUE THREAD

**Issue by Maarten-s92** [diyhue/diyHue#999]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Install Script

### Home Assistant related?

Yes

### Description

Hi,

I finally got my DIY HUE running. And everything looks fine, it works like a charm. 
But after a few days, the same crash appears. I tried to reinstall it a few times and the same problem keeps popping up.

What am i doing wrong?

### Errorlog:

-----------------------------------------------------------
 Add-on: diyHue
 Emulate a Hue Bridge, add lights, sensors etc. from different vendors into one Ecosystem
-----------------------------------------------------------
 Add-on version: 2.0.10
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2024.1.6
 Home Assistant Supervisor: 2024.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/config/diyhue exists.
Your Architecture is = aarch64
Serve HTTPS
2024-02-19 18:03:46,598 - configManager.argumentHandler - INFO - Using Host 192.168.1.205:80
2024-02-19 18:03:46,599 - configManager.argumentHandler - INFO - Host MAC given as b827eb3b61fb
2024-02-19 18:03:46,600 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2024-02-19 18:03:46,601 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2024-02-19 18:03:46,601 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2024-02-19 18:03:46,623 - configManager.argumentHandler - INFO - Using Host 192.168.1.205:80
2024-02-19 18:03:46,623 - configManager.argumentHandler - INFO - Host MAC given as b827eb3b61fb
2024-02-19 18:03:46,624 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2024-02-19 18:03:46,625 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2024-02-19 18:03:46,626 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2024-02-19 18:03:46,636 - configManager.argumentHandler - INFO - Debug logging disabled!
2024-02-19 17:03:47,049 - configManager.configHandler - ERROR - CRITICAL! Config file was not loaded
Traceback (most recent call last):
  File "/opt/hue-emulator/configManager/configHandler.py", line 114, in load_config
    self.yaml_config["lights"][light] = Light(data)
  File "/opt/hue-emulator/HueObjects/__init__.py", line 291, in __init__
    "data": [self.getV2Api()],
  File "/opt/hue-emulator/HueObjects/__init__.py", line 531, in getV2Api
    "brightness": round(self.state["bri"] / 2.54, 2),
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
2024-02-19 17:03:47,887 - HueObjects - INFO - Spots Voor Midden light was destroyed.
CRITICAL! Config file was not loaded
[cmd] ./run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

### Steps to reproduce

- 

### Please enter your operating system details here

 Add-on version: 2.0.10
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2024.1.6
 Home Assistant Supervisor: 2024.01.1

### What DiyHue version(branch) are you using?

master (latest)

**Comment by mariusmotea** [comment]
Hi,

For some reason the bri value was updated from integer to none or float. I'm not an expert of HAOS addon but i think there must be a way to access the config files of diyhue. You need to open lights.yaml and look to bri value to every light. If it is not integer but something else put an integer value from 1 to 254.

**Comment by Maarten-s92** [comment]
Hi Marius,

Somehow the bri was set to "null", don't know why it happened and if it will come back. But for now, this did the trick for me. Thanks a lot!

**Comment by Maarten-s92** [comment]
And the problem came back. somehow it keeps happening. 

Add-on: diyHue
 Emulate a Hue Bridge, add lights, sensors etc. from different vendors into one Ecosystem
-----------------------------------------------------------
 Add-on version: 2.0.10
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2024.1.6
 Home Assistant Supervisor: 2024.02.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/config/diyhue exists.
Your Architecture is = aarch64
Serve HTTPS
2024-02-21 09:20:00,470 - configManager.argumentHandler - INFO - Using Host 192.168.1.205:80
2024-02-21 09:20:00,471 - configManager.argumentHandler - INFO - Host MAC given as b827eb3b61fb
2024-02-21 09:20:00,471 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2024-02-21 09:20:00,472 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2024-02-21 09:20:00,473 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2024-02-21 09:20:00,493 - configManager.argumentHandler - INFO - Using Host 192.168.1.205:80
2024-02-21 09:20:00,494 - configManager.argumentHandler - INFO - Host MAC given as b827eb3b61fb
2024-02-21 09:20:00,495 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2024-02-21 09:20:00,495 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2024-02-21 09:20:00,496 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2024-02-21 09:20:00,505 - configManager.argumentHandler - INFO - Debug logging disabled!
2024-02-21 08:20:00,863 - configManager.configHandler - ERROR - CRITICAL! Config file was not loaded
Traceback (most recent call last):
  File "/opt/hue-emulator/configManager/configHandler.py", line 114, in load_config
    self.yaml_config["lights"][light] = Light(data)
  File "/opt/hue-emulator/HueObjects/__init__.py", line 291, in __init__
    "data": [self.getV2Api()],
  File "/opt/hue-emulator/HueObjects/__init__.py", line 531, in getV2Api
    "brightness": round(self.state["bri"] / 2.54, 2),
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
CRITICAL! Config file was not loaded
2024-02-21 08:20:00,880 - HueObjects - INFO - Spots Voor Midden light was destroyed.
[cmd] ./run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by hendriksen-mark** [comment]
what version of diyhue are you using?
`"brightness": round(self.state["bri"] / 2.54, 2),` is not what it is now.
now it is `"brightness": round(float(bri_value) / 2.54, 2),` and is on line 541

**Comment by Maarten-s92** [comment]
> what version of diyhue are you using? `"brightness": round(self.state["bri"] / 2.54, 2),` is not what it is now. now it is `"brightness": round(float(bri_value) / 2.54, 2),` and is on line 541

 2.0.10, i dont know what you mean with the rest. But somehow the BRI values are changed back to "null" after between 24 and 32 hours.

**Comment by hendriksen-mark** [comment]
that is strange.
what it means is the code you are using is old.
in the new code "null" is converted to 1
[https://github.com/diyhue/diyHue/blob/571a0e3ae26db3643e13e9274d88a1e576ae252b/BridgeEmulator/HueObjects/__init__.py#L541](url)

**Comment by Maarten-s92** [comment]
As far is I know this is the latest version available to me. 

https://github.com/diyhue/hassio-addon/blob/master/diyhue/CHANGELOG.md

**Comment by hendriksen-mark** [comment]
I see the code is not copyed to the needed location.
Im working on it.

**Comment by Maarten-s92** [comment]
> I see the code is not copyed to the needed location. Im working on it.

Great! Thanks a lot for that!

**Comment by hendriksen-mark** [comment]
i made a update.
new version is 2.0.12.
please update and let me know if this works.

**Comment by Maarten-s92** [comment]
Thanks Mark! I did the update, will be back with feedback.

**Comment by hendriksen-mark** [comment]
How is it working now?
